use nbs_odse
GO
SELECT -21+count(*) as Query12 FROM sys.objects WHERE name in ('SOURCE_ACT_RELATIONSHIP','SOURCE_CASE_HISTORY','SOURCE_CASE_INVESTIGATION','SOURCE_CASE_MANAGEMENT','SOURCE_CASE_REPEATS',
'SOURCE_CASE_SIGNS','SOURCE_CASE_STD','SOURCE_CONSTANTS','SOURCE_CONTACT_REPEATS','SOURCE_CONTACT_STD','SOURCE_CONTACT','SOURCE_INTERVIEW_REPEATS','SOURCE_INTERVIEW','SOURCE_LAB_REPORT',
'SOURCE_MORBIDITY_REPORT_STD','SOURCE_MORBIDITY_REPORT','SOURCE_ORGANIZATION','SOURCE_PATIENT','SOURCE_PLACE','SOURCE_PROVIDER','SOURCE_TREATMENT')