/**This script migrates non-SAS managed RDB database structure from R4.0 to R4.0.1.**/
/************************ Summary of changes************************/
/* Creates 9 new tables: L_PATIENT, S_PATIENT, D_PATIENT,S_PROVIDER, D_PROVIDER, L_PROVIDER, S_ORGANIZATION, D_ORGANIZATION and L_ORGANIZATION; */
/* Creates 9 primary keys; */
/* Drop and recreate 1 table with 1 primary key: HEP100 */

---------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------
/* civil00019450 DB Request: RDB: Testing RDB for new Patient Dimensions */
/* 19452 - Drop PATIENT_LDF_KEY and PATIENT_GEOCODING_KEY columns both from D_PATIENT and S_PATIENT table */
/* 19462 - Drop PROVIDER_PROVIDER_LDF_KEY from D_PROVIDER TABLE and PROVIDER_PROVIDER_LDF_KEY from S_PROVIDER table */
USE rdb
go
IF OBJECT_ID('dbo.s_patient') IS NOT NULL Drop table rdb.dbo.S_PATIENT;
GO
IF OBJECT_ID('dbo.L_patient') IS NOT NULL Drop table rdb.dbo.L_PATIENT;
GO
IF OBJECT_ID('dbo.D_patient') IS NOT NULL Drop table rdb.dbo.D_PATIENT;
GO
IF OBJECT_ID('DBO.S_PROVIDER') IS NOT NULL DROP TABLE RDB.DBO.S_PROVIDER;
GO
IF OBJECT_ID('DBO.L_PROVIDER') IS NOT NULL DROP TABLE RDB.DBO.L_PROVIDER;
GO
IF OBJECT_ID('DBO.D_PROVIDER') IS NOT NULL DROP TABLE RDB.DBO.D_PROVIDER;
GO
IF OBJECT_ID('DBO.S_ORGANIZATION') IS NOT NULL DROP TABLE RDB.DBO.S_ORGANIZATION;
GO
IF OBJECT_ID('DBO.L_ORGANIZATION') IS NOT NULL DROP TABLE RDB.DBO.L_ORGANIZATION;
GO
IF OBJECT_ID('DBO.D_ORGANIZATION') IS NOT NULL DROP TABLE RDB.DBO.D_ORGANIZATION;
GO

USE rdb 
GO
CREATE TABLE dbo .S_PATIENT (
	PATIENT_UID  			bigint  NOT NULL,
	PATIENT_MPR_UID  		bigint  NULL,
	PATIENT_RECORD_STATUS  		varchar (50) NULL,
	PATIENT_LOCAL_ID  		varchar (50) NULL,
	PATIENT_GENERAL_COMMENTS  	varchar (2000) NULL,
	PATIENT_FIRST_NAME  		varchar (50) NULL,
	PATIENT_MIDDLE_NAME  		varchar (50) NULL,
	PATIENT_LAST_NAME  		varchar (50) NULL,
	PATIENT_NAME_SUFFIX  		varchar (50) NULL,
	PATIENT_ALIAS_NICKNAME  	varchar (50) NULL,
	PATIENT_STREET_ADDRESS_1  	varchar (50) NULL,
	PATIENT_STREET_ADDRESS_2  	varchar (50) NULL,
	PATIENT_CITY  			varchar (50) NULL,
	PATIENT_STATE  			varchar (50) NULL,
	PATIENT_ZIP  			varchar (50) NULL,
	PATIENT_COUNTY  		varchar (50) NULL,
	PATIENT_COUNTRY  		varchar (50) NULL,
	PATIENT_WITHIN_CITY_LIMITS  	varchar (10) NULL,
	PATIENT_PHONE_HOME  		varchar (50) NULL,
	PATIENT_PHONE_EXT_HOME  	varchar (50) NULL,
	PATIENT_PHONE_WORK  		varchar (50) NULL,
	PATIENT_PHONE_EXT_WORK  	varchar (50) NULL,
	PATIENT_PHONE_CELL  		varchar (50) NULL,
	PATIENT_EMAIL  			varchar (100) NULL,
	PATIENT_DOB  			datetime  NULL,
	PATIENT_AGE_REPORTED  		numeric (18, 0) NULL,
	PATIENT_AGE_REPORTED_UNIT  	varchar (20) NULL,
	PATIENT_BIRTH_SEX  		varchar (50) NULL,
	PATIENT_CURRENT_SEX  		varchar (50) NULL,
	PATIENT_DECEASED_INDICATOR  	varchar (50) NULL,
	PATIENT_DECEASED_DATE  		datetime  NULL,
	PATIENT_MARITAL_STATUS  	varchar (50) NULL,
	PATIENT_SSN  			varchar (50) NULL,
	PATIENT_ETHNICITY  		varchar (50) NULL,
	PATIENT_RACE_CALCULATED  	varchar (50) NULL,
	PATIENT_RACE_CALC_DETAILS  	varchar (4000) NULL,
	PATIENT_RACE_AMER_IND_1  	varchar (50) NULL,
	PATIENT_RACE_AMER_IND_2  	varchar (50) NULL,
	PATIENT_RACE_AMER_IND_3  	varchar (50) NULL,
	PATIENT_RACE_AMER_IND_GT3_IND  	varchar (50) NULL,
	PATIENT_RACE_AMER_IND_ALL  	varchar (2000) NULL,
	PATIENT_RACE_ASIAN_1  		varchar (50) NULL,
	PATIENT_RACE_ASIAN_2  		varchar (50) NULL,
	PATIENT_RACE_ASIAN_3  		varchar (50) NULL,
	PATIENT_RACE_ASIAN_GT3_IND  	varchar (50) NULL,
	PATIENT_RACE_ASIAN_ALL  	varchar (2000) NULL,
	PATIENT_RACE_BLACK_1  		varchar (50) NULL,
	PATIENT_RACE_BLACK_2  		varchar (50) NULL,
	PATIENT_RACE_BLACK_3  		varchar (50) NULL,
	PATIENT_RACE_BLACK_GT3_IND  	varchar (50) NULL,
	PATIENT_RACE_BLACK_ALL  	varchar (2000) NULL,
	PATIENT_RACE_NAT_HI_1  		varchar (50) NULL,
	PATIENT_RACE_NAT_HI_2  		varchar (50) NULL,
	PATIENT_RACE_NAT_HI_3  		varchar (50) NULL,
	PATIENT_RACE_NAT_HI_GT3_IND  	varchar (50) NULL,
	PATIENT_RACE_NAT_HI_ALL  	varchar (2000) NULL,
	PATIENT_RACE_WHITE_1  		varchar (50) NULL,
	PATIENT_RACE_WHITE_2  		varchar (50) NULL,
	PATIENT_RACE_WHITE_3  		varchar (50) NULL,
	PATIENT_RACE_WHITE_GT3_IND  	varchar (50) NULL,
	PATIENT_RACE_WHITE_ALL  	varchar (2000) NULL,
	PATIENT_NUMBER  		varchar (50) NULL,
	PATIENT_NUMBER_AUTH  		varchar (50) NULL,
	PATIENT_ENTRY_METHOD  		varchar (50) NULL,
	PATIENT_LAST_CHANGE_TIME  	datetime  NULL,
	PATIENT_ADD_TIME  		datetime  NULL,
	PATIENT_ADDED_BY		varchar (50) NULL,
	PATIENT_LAST_UPDATED_BY 	varchar (50) NULL
	
 CONSTRAINT PK_S_PATIENT  PRIMARY KEY  
(
	PATIENT_UID  ASC
) 
)   
GO
 
CREATE TABLE dbo .L_PATIENT (
	PATIENT_KEY  bigint  NOT NULL,
	PATIENT_UID  bigint  NOT NULL,
 CONSTRAINT PK_L_PATIENT  PRIMARY KEY  
(
	PATIENT_KEY  ASC
)   
)   
GO
 
CREATE TABLE dbo .D_PATIENT (
	PATIENT_KEY  			bigint  NOT NULL,
	PATIENT_MPR_UID  		bigint  NULL,
	PATIENT_RECORD_STATUS  		varchar (50) NULL,
	PATIENT_LOCAL_ID  		varchar (50) NULL,
	PATIENT_GENERAL_COMMENTS  	varchar (2000) NULL,
	PATIENT_FIRST_NAME  		varchar (50) NULL,
	PATIENT_MIDDLE_NAME  		varchar (50) NULL,
	PATIENT_LAST_NAME  		varchar (50) NULL,
	PATIENT_NAME_SUFFIX  		varchar (50) NULL,
	PATIENT_ALIAS_NICKNAME  	varchar (50) NULL,
	PATIENT_STREET_ADDRESS_1  	varchar (50) NULL,
	PATIENT_STREET_ADDRESS_2  	varchar (50) NULL,
	PATIENT_CITY  			varchar (50) NULL,
	PATIENT_STATE  			varchar (50) NULL,
	PATIENT_ZIP  			varchar (50) NULL,
	PATIENT_COUNTY  		varchar (50) NULL,
	PATIENT_COUNTRY  		varchar (50) NULL,
	PATIENT_WITHIN_CITY_LIMITS  	varchar (10) NULL,
	PATIENT_PHONE_HOME  		varchar (50) NULL,
	PATIENT_PHONE_EXT_HOME  	varchar (50) NULL,
	PATIENT_PHONE_WORK  		varchar (50) NULL,
	PATIENT_PHONE_EXT_WORK  	varchar (50) NULL,
	PATIENT_PHONE_CELL  		varchar (50) NULL,
	PATIENT_EMAIL  			varchar (100) NULL,
	PATIENT_DOB  			datetime  NULL,
	PATIENT_AGE_REPORTED  		numeric (18, 0) NULL,
	PATIENT_AGE_REPORTED_UNIT  	varchar (20) NULL,
	PATIENT_BIRTH_SEX  		varchar (50) NULL,
	PATIENT_CURRENT_SEX  		varchar (50) NULL,
	PATIENT_DECEASED_INDICATOR  	varchar (50) NULL,
	PATIENT_DECEASED_DATE  		datetime  NULL,
	PATIENT_MARITAL_STATUS  	varchar (50) NULL,
	PATIENT_SSN  			varchar (50) NULL,
	PATIENT_ETHNICITY  		varchar (50) NULL,
	PATIENT_RACE_CALCULATED  	varchar (50) NULL,
	PATIENT_RACE_CALC_DETAILS  	varchar (4000) NULL,
	PATIENT_RACE_AMER_IND_1  	varchar (50) NULL,
	PATIENT_RACE_AMER_IND_2  	varchar (50) NULL,
	PATIENT_RACE_AMER_IND_3  	varchar (50) NULL,
	PATIENT_RACE_AMER_IND_GT3_IND  	varchar (50) NULL,
	PATIENT_RACE_AMER_IND_ALL  	varchar (2000) NULL,
	PATIENT_RACE_ASIAN_1  		varchar (50) NULL,
	PATIENT_RACE_ASIAN_2  		varchar (50) NULL,
	PATIENT_RACE_ASIAN_3  		varchar (50) NULL,
	PATIENT_RACE_ASIAN_GT3_IND  	varchar (50) NULL,
	PATIENT_RACE_ASIAN_ALL  	varchar (2000) NULL,
	PATIENT_RACE_BLACK_1  		varchar (50) NULL,
	PATIENT_RACE_BLACK_2  		varchar (50) NULL,
	PATIENT_RACE_BLACK_3  		varchar (50) NULL,
	PATIENT_RACE_BLACK_GT3_IND  	varchar (50) NULL,
	PATIENT_RACE_BLACK_ALL  	varchar (2000) NULL,
	PATIENT_RACE_NAT_HI_1  		varchar (50) NULL,
	PATIENT_RACE_NAT_HI_2  		varchar (50) NULL,
	PATIENT_RACE_NAT_HI_3  		varchar (50) NULL,
	PATIENT_RACE_NAT_HI_GT3_IND  	varchar (50) NULL,
	PATIENT_RACE_NAT_HI_ALL  	varchar (2000) NULL,
	PATIENT_RACE_WHITE_1  		varchar (50) NULL,
	PATIENT_RACE_WHITE_2  		varchar (50) NULL,
	PATIENT_RACE_WHITE_3  		varchar (50) NULL,
	PATIENT_RACE_WHITE_GT3_IND  	varchar (50) NULL,
	PATIENT_RACE_WHITE_ALL  	varchar (2000) NULL,
	PATIENT_NUMBER  		varchar (50) NULL,
	PATIENT_NUMBER_AUTH  		varchar (50) NULL,
	PATIENT_ENTRY_METHOD  		varchar (50) NULL,
	PATIENT_LAST_CHANGE_TIME  	datetime  NULL,
	PATIENT_UID  			bigint  NULL,
	PATIENT_ADD_TIME  		datetime  NULL,
	PATIENT_ADDED_BY		varchar (50) NULL,
	PATIENT_LAST_UPDATED_BY 	varchar (50) NULL
 CONSTRAINT PK_D_PATIENT  PRIMARY KEY  
(
	PATIENT_KEY  ASC
)   
)   
GO

CREATE TABLE dbo .S_PROVIDER (
	PROVIDER_UID  			bigint  NOT NULL,
	PROVIDER_LOCAL_ID  		varchar (50) NULL,
	PROVIDER_RECORD_STATUS  	varchar (50) NULL,
	PROVIDER_NAME_PREFIX  		varchar (50) NULL,
	PROVIDER_FIRST_NAME  		varchar (50) NULL,
	PROVIDER_MIDDLE_NAME  		varchar (50) NULL,
	PROVIDER_LAST_NAME  		varchar (50) NULL,
	PROVIDER_NAME_SUFFIX  		varchar (50) NULL,
	PROVIDER_NAME_DEGREE  		varchar (50) NULL,
	PROVIDER_GENERAL_COMMENTS  	varchar (2000) NULL,
	PROVIDER_QUICK_CODE  		varchar (50) NULL,
	PROVIDER_REGISTRATION_NUM  	varchar (50) NULL,
	PROVIDER_REGISRATION_NUM_AUTH  	varchar (50) NULL,
	PROVIDER_STREET_ADDRESS_1  	varchar (50) NULL,
	PROVIDER_STREET_ADDRESS_2  	varchar (50) NULL,
	PROVIDER_CITY  			varchar (50) NULL,
	PROVIDER_STATE  		varchar (50) NULL,
	PROVIDER_ZIP  			varchar (50) NULL,
	PROVIDER_COUNTY  		varchar (50) NULL,
	PROVIDER_COUNTRY  		varchar (50) NULL,
	PROVIDER_ADDRESS_COMMENTS  	varchar (2000) NULL,
	PROVIDER_PHONE_WORK  		varchar (50) NULL,
	PROVIDER_PHONE_EXT_WORK  	varchar (50) NULL,
	PROVIDER_EMAIL_WORK  		varchar (50) NULL,
	PROVIDER_PHONE_COMMENTS  	varchar (2000) NULL,
	PROVIDER_PHONE_CELL  		varchar (50) NULL,
	PROVIDER_ENTRY_METHOD  		varchar (50) NULL,
	PROVIDER_LAST_CHANGE_TIME  	datetime  NULL,
	PROVIDER_ADD_TIME  		datetime  NULL,
	PROVIDER_ADDED_BY 		varchar (50) NULL,
	PROVIDER_LAST_UPDATED_BY	varchar (50) NULL,
 CONSTRAINT PK_S_PROVIDER  PRIMARY KEY  
(
	PROVIDER_UID  ASC
)   
)   
GO
 
CREATE TABLE dbo .D_PROVIDER (
	PROVIDER_UID  				bigint  NULL,
	PROVIDER_KEY  				bigint  NOT NULL,
	PROVIDER_LOCAL_ID  			varchar (50) NULL,
	PROVIDER_RECORD_STATUS  		varchar (50) NULL,
	PROVIDER_NAME_PREFIX  			varchar (50) NULL,
	PROVIDER_FIRST_NAME  			varchar (50) NULL,
	PROVIDER_MIDDLE_NAME  			varchar (50) NULL,
	PROVIDER_LAST_NAME  			varchar (50) NULL,
	PROVIDER_NAME_SUFFIX  			varchar (50) NULL,
	PROVIDER_NAME_DEGREE  			varchar (50) NULL,
	PROVIDER_GENERAL_COMMENTS  		varchar (2000) NULL,
	PROVIDER_QUICK_CODE  			varchar (50) NULL,
	PROVIDER_REGISTRATION_NUM  		varchar (50) NULL,
	PROVIDER_REGISRATION_NUM_AUTH  		varchar (50) NULL,
	PROVIDER_STREET_ADDRESS_1  		varchar (50) NULL,
	PROVIDER_STREET_ADDRESS_2  		varchar (50) NULL,
	PROVIDER_CITY  				varchar (50) NULL,
	PROVIDER_STATE  			varchar (50) NULL,
	PROVIDER_ZIP  				varchar (50) NULL,
	PROVIDER_COUNTY  			varchar (50) NULL,
	PROVIDER_COUNTRY  			varchar (50) NULL,
	PROVIDER_ADDRESS_COMMENTS  		varchar (2000) NULL,
	PROVIDER_PHONE_WORK  			varchar (50) NULL,
	PROVIDER_PHONE_EXT_WORK  		varchar (50) NULL,
	PROVIDER_EMAIL_WORK  			varchar (50) NULL,
	PROVIDER_PHONE_COMMENTS  		varchar (2000) NULL,
	PROVIDER_PHONE_CELL  			varchar (50) NULL,
	PROVIDER_ENTRY_METHOD  			varchar (50) NULL,
	PROVIDER_LAST_CHANGE_TIME  		datetime  NULL,
	PROVIDER_ADD_TIME  			datetime  NULL,
	PROVIDER_ADDED_BY 			varchar (50) NULL,
	PROVIDER_LAST_UPDATED_BY		varchar (50) NULL,
 CONSTRAINT PK_D_PROVIDER  PRIMARY KEY  
(
	PROVIDER_KEY  ASC
)   
)   
GO
 
CREATE TABLE dbo .L_PROVIDER (
	PROVIDER_KEY  bigint  NOT NULL,
	PROVIDER_UID  bigint  NOT NULL,
 CONSTRAINT PK_L_PROVIDER  PRIMARY KEY  
(
	PROVIDER_KEY  ASC
)   
)   
GO
 
CREATE TABLE dbo .S_ORGANIZATION (
	ORGANIZATION_UID  			bigint  NOT NULL,
	ORGANIZATION_LOCAL_ID  			varchar (50) NULL,
	ORGANIZATION_RECORD_STATUS  		varchar (50) NULL,
	ORGANIZATION_NAME  			varchar (50) NULL,
	ORGANIZATION_GENERAL_COMMENTS  		varchar (2000) NULL,
	ORGANIZATION_QUICK_CODE  		varchar (50) NULL,
	ORGANIZATION_STAND_IND_CLASS  		varchar (50) NULL,
	ORGANIZATION_FACILITY_ID  		varchar (50) NULL,
	ORGANIZATION_FACILITY_ID_AUTH  		varchar (50) NULL,	
	ORGANIZATION_STREET_ADDRESS_1  		varchar (50) NULL,
	ORGANIZATION_STREET_ADDRESS_2  		varchar (50) NULL,
	ORGANIZATION_CITY  			varchar (50) NULL,
	ORGANIZATION_STATE  			varchar (50) NULL,
	ORGANIZATION_ZIP  			varchar (10) NULL,
	ORGANIZATION_COUNTY  			varchar (50) NULL,
	ORGANIZATION_COUNTRY  			varchar (50) NULL,
	ORGANIZATION_ADDRESS_COMMENTS  		varchar (2000) NULL,
	ORGANIZATION_PHONE_WORK  		varchar (50) NULL,
	ORGANIZATION_PHONE_EXT_WORK  		varchar (50) NULL,
	ORGANIZATION_EMAIL  			varchar (50) NULL,
	ORGANIZATION_PHONE_COMMENTS  		varchar (2000) NULL,
	ORGANIZATION_ENTRY_METHOD  		varchar (50) NULL,
	ORGANIZATION_LAST_CHANGE_TIME  		datetime  NULL,
	ORGANIZATION_ADD_TIME  			datetime  NULL,
	ORGANIZATION_ADDED_BY			varchar (50) NULL,
	ORGANIZATION_LAST_UPDATED_BY		varchar (50) NULL,
 CONSTRAINT PK_S_ORGANIZATION  PRIMARY KEY  
(
	ORGANIZATION_UID  ASC
)   
)   
GO
 
CREATE TABLE dbo .L_ORGANIZATION (
	ORGANIZATION_KEY  bigint  NOT NULL,
	ORGANIZATION_UID  bigint  NOT NULL,
 CONSTRAINT PK_L_ORGANIZATION  PRIMARY KEY  
(
	ORGANIZATION_KEY  ASC
)   
)   
GO
 
CREATE TABLE dbo .D_ORGANIZATION (
	ORGANIZATION_KEY  			bigint  NOT NULL,
	ORGANIZATION_UID  			bigint  NULL,
	ORGANIZATION_LOCAL_ID  			varchar (50) NULL,
	ORGANIZATION_RECORD_STATUS  		varchar (50) NULL,
	ORGANIZATION_NAME  			varchar (50) NULL,
	ORGANIZATION_GENERAL_COMMENTS  		varchar (2000) NULL,
	ORGANIZATION_QUICK_CODE  		varchar (50) NULL,
	ORGANIZATION_STAND_IND_CLASS  		varchar (50) NULL,
	ORGANIZATION_FACILITY_ID  		varchar (50) NULL,
	ORGANIZATION_FACILITY_ID_AUTH  		varchar (50) NULL,	
	ORGANIZATION_STREET_ADDRESS_1  		varchar (50) NULL,
	ORGANIZATION_STREET_ADDRESS_2  		varchar (50) NULL,
	ORGANIZATION_CITY  			varchar (50) NULL,
	ORGANIZATION_STATE  			varchar (50) NULL,
	ORGANIZATION_ZIP  			varchar (10) NULL,
	ORGANIZATION_COUNTY  			varchar (50) NULL,
	ORGANIZATION_COUNTRY  			varchar (50) NULL,
	ORGANIZATION_ADDRESS_COMMENTS  		varchar (2000) NULL,
	ORGANIZATION_PHONE_WORK  		varchar (50) NULL,
	ORGANIZATION_PHONE_EXT_WORK  		varchar (50) NULL,
	ORGANIZATION_EMAIL  			varchar (50) NULL,
	ORGANIZATION_PHONE_COMMENTS  		varchar (2000) NULL,
	ORGANIZATION_ENTRY_METHOD  		varchar (50) NULL,
	ORGANIZATION_LAST_CHANGE_TIME  		datetime  NULL,
	ORGANIZATION_ADD_TIME  			datetime  NULL,
	ORGANIZATION_ADDED_BY			varchar (50) NULL,
	ORGANIZATION_LAST_UPDATED_BY		varchar (50) NULL,
 CONSTRAINT PK_D_ORGANIZATION  PRIMARY KEY  
(
	ORGANIZATION_KEY  ASC
)   
)   
GO





---------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------
/* civil00019497 DB Request: RDB: recreate the HEP100 due to data type inconsistencies(KEYS and Uids) */
use rdb
GO
IF OBJECT_ID('dbo.HEP100') IS NOT NULL Drop table rdb.dbo.HEP100;
GO
CREATE   TABLE rdb.dbo .HEP100  (
    PATIENT_LOCAL_ID varchar  ( 50 )   NOT   NULL,
    PATIENT_FIRST_NM varchar  ( 50 )   NULL,
    PATIENT_MIDDLE_NM varchar  ( 50 )   NULL,
    PATIENT_LAST_NM varchar  ( 50 )   NULL,
    PATIENT_DOB datetime  NULL,
    PATIENT_REPORTEDAGE numeric  ( 8 ,  0 )   NULL,
    PATIENT_REPORTED_AGE_UNITS varchar  ( 50 )   NULL,
    ADDR_USE_CD_DESC varchar  ( 300 )   NULL,
    ADDR_CD_DESC varchar  ( 300 )   NULL,
    PATIENT_ADDRESS varchar  ( 725 )   NULL,
    PATIENT_CITY varchar  ( 100 )   NULL,
    PATIENT_COUNTY varchar  ( 300 )   NULL,
    PATIENT_ZIP_CODE varchar  ( 20 )   NULL,
    PATIENT_CURR_GENDER varchar ( 50 )   NULL,
    PATIENT_ELECTRONIC_IND varchar  ( 50 )   NULL,
    RACE varchar  ( 500 )   NULL,
    CONDITION_CD varchar  ( 50 )   NULL,
    CONDITION varchar  ( 50 )   NULL,
    PROGRAM_JURISDICTION_OID numeric  ( 20 ,  0 )   NULL,
    INV_LOCAL_ID varchar  ( 50 )   NOT   NULL,
    INVESTIGATION_STATUS varchar  ( 50 )   NULL,
    INV_CASE_STATUS varchar  ( 50 )   NULL,
    INV_JURISDICTION_NM varchar  ( 100 )   NULL,
    RPT_SRC_CD_DESC varchar  ( 100 )   NULL,
    REPORTING_SOURCE varchar  ( 100 )   NULL,
    REPORTING_SOURCE_COUNTY varchar  ( 255 )   NULL,
    REPORTING_SOURCE_CITY varchar  ( 100 )   NULL,
    REPORTING_SOURCE_STATE varchar  ( 100 )   NULL,
    REPORTING_SOURCE_ADDRESS_USE varchar  ( 300 )   NULL,
    REPORTING_SOURCE_ADDRESS_TYPE varchar  ( 300 )   NULL,
    PHYSICIAN_NAME varchar  ( 152 )   NULL,
    PHYSICIAN_COUNTY varchar  ( 255 )   NULL,
    PHYSICIAN_CITY varchar  ( 100 )   NULL,
    PHYSICIAN_STATE varchar  ( 100 )   NULL,
    PHYSICIAN_ADDRESS_USE_DESC varchar  ( 300 )   NULL,
    PHYSICIAN_ADDRESS_TYPE_DESC varchar  ( 300 )   NULL,
    INVESTIGATOR_NAME varchar  ( 152 )   NULL,
    HEP_A_TOTAL_ANTIBODY varchar  ( 50 )   NULL,
    HEP_A_IGM_ANTIBODY varchar  ( 50 )   NULL,
    HEP_B_SURFACE_ANTIGEN varchar  ( 50 )   NULL,
    HEP_B_TOTAL_ANTIBODY varchar  ( 50 )   NULL,
    HEP_B_IGM_ANTIBODY varchar  ( 50 )   NULL,
    HEP_C_TOTAL_ANTIBODY varchar  ( 50 )   NULL,
    HEP_D_TOTAL_ANTIBODY varchar  ( 50 )   NULL,
    HEP_E_TOTAL_ANTIBODY varchar  ( 50 )   NULL,
    ANTIHCV_SIGNAL_TO_CUTOFF_RATIO varchar  ( 2000 )   NULL,
    ANTIHCV_SUPPLEMENTAL_ASSAY varchar  ( 50 )   NULL,
    HCV_RNA varchar  ( 50 )   NULL,
    ALT_SGPT_RESULT numeric  ( 11 ,  0 )   NULL,
    ALT_SGPT_RESULT_UPPER_LIMIT numeric  ( 11 ,  0 )   NULL,
    AST_SGOT_RESULT numeric  ( 11 ,  0 )   NULL,
    AST_SGOT_RESULT_UPPER_LIMIT numeric  ( 11 ,  0 )   NULL,
    ALT_RESULT_DT datetime  NULL,
    AST_RESULT_DT datetime  NULL,
    INV_START_DT datetime  NULL,
    INV_RPT_DT datetime  NULL,
    EARLIEST_RPT_TO_CNTY_DT datetime  NULL,
    EARLIEST_RPT_TO_STATE_DT datetime  NULL,
    DIE_FRM_THIS_ILLNESS_IND varchar  ( 50 )   NULL,
    ILLNESS_ONSET_DT datetime  NULL,
    DIAGNOSIS_DT datetime  NULL,
    HSPTLIZD_IND varchar  ( 50 )   NULL,
    HSPTL_ADMISSION_DT datetime  NULL,
    HSPTL_DISCHARGE_DT datetime  NULL,
    HSPTL_DURATION_DAYS numeric  ( 20 ,  0 )   NULL,
    OUTBREAK_IND varchar  ( 50 )   NULL,
    TRANSMISSION_MODE varchar  ( 50 )   NULL,
    DISEASE_IMPORTED_IND varchar  ( 50 )   NULL,
    IMPORT_FROM_COUNTRY varchar  ( 50 )   NULL,
    IMPORT_FROM_STATE varchar  ( 50 )   NULL,
    IMPORT_FROM_COUNTY varchar  ( 50 )   NULL,
    IMPORT_FROM_CITY varchar  ( 2000 )   NULL,
    INV_COMMENTS varchar  ( 2000 )   NULL,
    CASE_RPT_MMWR_WEEK numeric  ( 8 ,  0 )   NULL,
    CASE_RPT_MMWR_YEAR numeric  ( 8 ,  0 )   NULL,
    PATIENT_SYMPTOMATIC_IND varchar  ( 50 )   NULL,
    PATIENT_JUNDICED_IND varchar  ( 50 )   NULL,
    PATIENT_PREGNANT_IND varchar  ( 50 )   NULL,
    PATIENT_PREGNANCY_DUE_DT datetime  NULL,
    HEP_A_EPLINK_IND varchar  ( 50 )   NULL,
    HEP_A_CONTACTED_IND varchar  ( 50 )   NULL,
    D_N_P_EMPLOYEE_IND varchar  ( 50 )   NULL,
    D_N_P_HOUSEHOLD_CONTACT_IND varchar  ( 50 )   NULL,
    HEP_A_KEYENT_IN_CHILDCARE_IND varchar  ( 50 )   NULL,
    HEPA_MALE_SEX_PARTNER_NBR varchar  ( 50 )   NULL,
    HEPA_FEMALE_SEX_PARTNER_NBR varchar  ( 50 )   NULL,
    STREET_DRUG_INJECTED_IN_2_6_WK varchar  ( 50 )   NULL,
    STREET_DRUG_USED_IN_2_6_WK varchar  ( 50 )   NULL,
    TRAVEL_OUT_USA_CAN_IND varchar  ( 50 )   NULL,
    HOUSEHOLD_NPP_OUT_USA_CAN varchar  ( 50 )   NULL,
    PART_OF_AN_OUTBRK_IND varchar  ( 50 )   NULL,
    ASSOCIATED_OUTBRK_TYPE varchar  ( 50 )   NULL,
    FOODBORNE_OUTBRK_FOOD_ITEM varchar  ( 2000 )   NULL,
    FOODHANDLER_2_WK_PRIOR_ONSET varchar  ( 50 )   NULL,
    HEP_A_VACC_RECEIVED_IND varchar  ( 50 )   NULL,
    HEP_A_VACC_RECEIVED_DOSE varchar  ( 50 )   NULL,
    HEP_A_VACC_LAST_RECEIVED_YR numeric  ( 11 ,  0 )   NULL,
    IMMUNE_GLOBULIN_RECEIVED_IND varchar  ( 50 )   NULL,
    GLOBULIN_LAST_RECEIVED_YR datetime  NULL,
    HEP_B_CONTACTED_IND varchar  ( 50 )   NULL,
    HEPB_STD_TREATED_IND varchar  ( 50 )   NULL,
    HEPB_STD_LAST_TREATMENT_YR numeric  ( 11 ,  0 )   NULL,
    STREET_DRUG_INJECTED_IN6WKMON varchar  ( 50 )   NULL,
    STREET_DRUG_USED_IN6WKMON varchar  ( 50 )   NULL,
    HEPB_FEMALE_SEX_PARTNER_NBR varchar  ( 50 )   NULL,
    HEPB_MALE_SEX_PARTNER_NBR varchar  ( 50 )   NULL,
    HEMODIALYSIS_IN_LAST_6WKMON varchar  ( 50 )   NULL,
    BLOOD_CONTAMINATION_IN6WKMON varchar  ( 50 )   NULL,
    HEPB_BLOOD_RECEIVED_IN6WKMON varchar  ( 50 )   NULL,
    HEPB_BLOOD_RECEIVED_DT datetime  NULL,
    OUTPATIENT_IV_INFUSION_IN6WKMO varchar  ( 50 )   NULL,
    BLOOD_EXPOSURE_IN_LAST6WKMON varchar  ( 50 )   NULL,
    BLOOD_EXPOSURE_IN6WKMON_OTHER varchar  ( 2000 )   NULL,
    HEPB_MED_DEN_EMPLOYEE_IN6WKMON varchar  ( 50 )   NULL,
    HEPB_MED_DEN_BLOOD_CONTACT_FRQ varchar  ( 50 )   NULL,
    HEPB_PUB_SAFETY_WORKER_IN6WKMO varchar  ( 50 )   NULL,
    HEPB_PUBSAFETY_BLOODCONTACTFRQ varchar  ( 50 )   NULL,
    TATTOOED_IN6WKMON_BEFORE_ONSET varchar  ( 50 )   NULL,
    PIERCING_IN6WKMON_BEFORE_ONSET varchar  ( 50 )   NULL,
    DEN_WORK_OR_SURGERY_IN6WKMON varchar  ( 50 )   NULL,
    NON_ORAL_SURGERY_IN6WKMON varchar  ( 50 )   NULL,
    HSPTLIZD_IN6WKMON_BEFORE_ONSET varchar  ( 50 )   NULL,
    LONGTERMCARE_RESIDENT_IN6WKMON varchar  ( 50 )   NULL,
    B_INCARCERATED24PLUSHRSIN6WKMO varchar  ( 50 )   NULL,
    B_INCARCERATED_6PLUS_MON_IND varchar  ( 50 )   NULL,
    B_LAST6PLUSMON_INCARCERATE_YR numeric  ( 8 ,  0 )   NULL,
    BLAST6PLUSMO_INCARCERATEPERIOD numeric  ( 8 ,  0 )   NULL,
    B_LAST_INCARCERATE_PERIOD_UNIT varchar  ( 50 )   NULL,
    HEP_B_VACC_RECEIVED_IND varchar  ( 50 )   NULL,
    HEP_B_VACC_SHOT_RECEIVED_NBR varchar  ( 50 )   NULL,
    HEP_B_VACC_LAST_RECEIVED_YR numeric  ( 8 ,  0 )   NULL,
    ANTI_HBSAG_TESTED_IND varchar  ( 50 )   NULL,
    ANTI_HBS_POSITIVE_REACTIVE_IND varchar  ( 50 )   NULL,
    HEP_C_CONTACTED_IND varchar  ( 50 )   NULL,
    MED_DEN_EMPLOYEE_IN_2WK6MO varchar  ( 50 )   NULL,
    HEPC_MED_DEN_BLOOD_CONTACT_FRQ varchar  ( 50 )   NULL,
    PUBLIC_SAFETY_WORKER_IN_2WK6MO varchar  ( 50 )   NULL,
    HEPC_PUBSAFETY_BLOODCONTACTFRQ varchar  ( 50 )   NULL,
    TATTOOED_IN2WK6MO_BEFORE_ONSET varchar  ( 50 )   NULL,
    TATTOOED_IN2WK6MO_LOCATION varchar  ( 50 )   NULL,
    PIERCING_IN2WK6MO_BEFORE_ONSET varchar  ( 50 )   NULL,
    PIERCING_IN2WK6MO_LOCATION varchar  ( 50 )   NULL,
    STREET_DRUG_INJECTED_IN_2WK6MO varchar  ( 50 )   NULL,
    STREET_DRUG_USED_IN_2WK6MO varchar  ( 50 )   NULL,
    HEMODIALYSIS_IN_LAST_2WK6MO varchar  ( 50 )   NULL,
    BLOOD_CONTAMINATION_IN_2WK6MO varchar  ( 50 )   NULL,
    HEPC_BLOOD_RECEIVED_IN_2WK6MO varchar  ( 50 )   NULL,
    HEPC_BLOOD_RECEIVED_DT datetime  NULL,
    BLOOD_EXPOSURE_IN_LAST2WK6MO varchar  ( 50 )   NULL,
    BLOOD_EXPOSURE_IN2WK6MO_OTHER varchar  ( 2000 )   NULL,
    DEN_WORK_OR_SURGERY_IN2WK6MO varchar  ( 50 )   NULL,
    NON_ORAL_SURGERY_IN2WK6MO varchar  ( 50 )   NULL,
    HSPTLIZD_IN2WK6MO_BEFORE_ONSET varchar  ( 50 )   NULL,
    LONGTERMCARE_RESIDENT_IN2WK6MO varchar  ( 50 )   NULL,
    INCARCERATED_24PLUSHRSIN2WK6MO varchar  ( 50 )   NULL,
    HEPC_FEMALE_SEX_PARTNER_NBR varchar  ( 50 )   NULL,
    HEPC_MALE_SEX_PARTNER_NBR varchar  ( 50 )   NULL,
    C_INCARCERATED_6PLUS_MON_IND varchar  ( 50 )   NULL,
    C_LAST6PLUSMON_INCARCERATE_YR numeric  ( 11 ,  0 )   NULL,
    CLAST6PLUSMO_INCARCERATEPERIOD numeric  ( 11 ,  0 )   NULL,
    C_LAST_INCARCERATE_PERIOD_UNIT varchar  ( 50 )   NULL,
    HEPC_STD_TREATED_IND varchar  ( 50 )   NULL,
    HEPC_STD_LAST_TREATMENT_YR numeric  ( 11 ,  0 )   NULL,
    BLOOD_TRANSFUSION_BEFORE_1992 varchar  ( 50 )   NULL,
    ORGAN_TRANSPLANT_BEFORE_1992 varchar  ( 50 )   NULL,
    CLOT_FACTOR_CONCERN_BEFORE1987 varchar  ( 50 )   NULL,
    LONGTERM_HEMODIALYSIS_IND varchar  ( 50 )   NULL,
    EVER_INJECT_NONPRESCRIBED_DRUG varchar  ( 50 )   NULL,
    LIFETIME_SEX_PARTNER_NBR numeric  ( 15 ,  5 )   NULL,
    EVER_INCARCERATED_IND varchar  ( 50 )   NULL,
    HEPATITIS_CONTACTED_IND varchar  ( 50 )   NULL,
    HEPATITIS_CONTACT_TYPE varchar  ( 50 )   NULL,
    HEPATITIS_OTHER_CONTACT_TYPE varchar  ( 2000 )   NULL,
    HEPC_MED_DEN_EMPLOYEE_IND varchar  ( 50 )   NULL,
    OUTPATIENT_IV_INFUSIONIN2WK6MO varchar  ( 50 )   NULL,
    EVENT_DATE datetime  NULL,
    HEP_MULTI_VAL_GRP_KEY bigint  NULL,
    INVESTIGATION_KEY bigint  NOT   NULL,
    HEP_B_E_ANTIGEN varchar  ( 50 )   NULL,    
    HEP_B_DNA varchar  ( 50 )   NULL,
    PHYSICIAN_UID  BIGINT NULL,
    INVESTIGATOR_UID BIGINT NULL,
    PATIENT_UID 	BIGINT NOT NULL,
    REFRESH_DATETIME	datetime NULL,
    CASE_UID BIGINT NOT NULL,
    REPORTING_SOURCE_UID BIGINT NULL
    
    CONSTRAINT PK_HEP100 PRIMARY   KEY (INVESTIGATION_KEY) 
);
GO



