[Environment]
active_environment=TEST10

[test1]
baseURL=http://35.170.137.196:7001/nbs/login
server_name=35.170.137.196
hostname=35.170.137.196

[test2]
baseURL=http://35.170.137.196:7001/nbs/login
server_name=34.234.68.3
hostname=34.234.68.3

[test3]
baseURL=http://35.170.137.196:7001/nbs/login
server_name=test3
hostname=test3

[test4]
baseURL=http://35.170.137.196:7001/nbs/login
server_name=test4
hostname=test4

[test5]
baseURL=http://35.170.137.196:7001/nbs/login
server_name=test5
hostname=test5

[test6]
baseURL=http://35.170.137.196:7001/nbs/login
server_name=35.170.137.196
hostname=35.170.137.196

[test7]
baseURL=http://35.170.137.196:7001/nbs/login
server_name=34.234.68.3
hostname=34.234.68.3

[test8]
baseURL=http://35.170.137.196:7001/nbs/login
server_name=test3
hostname=test3

[test9]
baseURL=http://35.170.137.196:7001/nbs/login
server_name=test4
hostname=test4

[TEST10]
baseURL=http://54.82.253.77:7001/nbs/login
server_name=54.82.253.77
hostname=54.82.253.77


[TEST11]
baseURL=http://75.101.247.231:7001/nbs/login
server_name=75.101.247.231
hostname=75.101.247.231

[test64-2]
baseURL=http://35.170.137.196:7001/nbs/login
server_name=34.234.68.3
hostname=34.234.68.3

[test64-8]
baseURL=http://35.170.137.196:7001/nbs/login
server_name=test3
hostname=test3

[dev1]
baseURL=http://35.170.137.196:7001/nbs/login
server_name=test4
hostname=test4

[dev2]
baseURL=http://35.170.137.196:7001/nbs/login
server_name=test5
hostname=test5

[dev3]
baseURL=http://35.170.137.196:7001/nbs/login
server_name=test5
hostname=test5

[deploy1]
baseURL=http://35.170.137.196:7001/nbs/login
server_name=test5
hostname=test5

[deploy2]
baseURL=http://35.170.137.196:7001/nbs/login
server_name=test5
hostname=test5

[commonInfo]
#baseURL=http://54.82.253.77:7001/nbs/login
username=pks
password=pks

[DatabaseInfo]
#server_name=54.82.253.77
database_name=nbs_odse
db_username=nbs_ods
db_password=ods
db_driver = sql server


[RemoteServer]
#hostname=75.101.247.231
username=TestAutomation
password=Welcome2gdit
local_file_path = C:\TEMP\abc.txt
remote_file_path = C:\TEMP\abc.txt

[JenkinsInfo]
jenkins_url=http://ec2-54-160-52-228.compute-1.amazonaws.com:8080/
jenkins_username=krishna-gdit
jenkins_password=Welcome2gdit
job_phcrimporter=PHCRImporter
job_dedupsimilar=DeDuplicationSimilarBatchProcess


[Misc]
remote_path=C:/TEMP/PHDC_2019NovelCoronaVirus.xml
batch_file_path=D:/wildfly-10.0.0.Final/nedssdomain/Nedss/PHCRImporter.bat


