INSERT INTO DATA_SOURCE ( DATA_SOURCE_UID, COLUMN_MAX_LEN, CONDITION_SECURITY, DATA_SOURCE_NAME,DATA_SOURCE_TITLE, DATA_SOURCE_TYPE_CODE, DESC_TXT, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,JURISDICTION_SECURITY, ORG_ACCESS_PERMIS, PROG_AREA_ACCESS_PERMIS, STATUS_CD,STATUS_TIME ) 
VALUES ( 1, NULL, 'N', 'nbs_ods.PHCDemographic', 'Disease Counts by County', NULL, 'Disease Counts by County sumarized to the Case Level', NULL, NULL, 'N', NULL, NULL, 'A',  NULL); 
 
