INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 1, NULL, 'public_health_case_uid', 'Investigation ID', 'INTEGER', 1, 'Investigation ID', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME )
VALUES ( 2, NULL, 'person_uid', 'Person ID', 'INTEGER', 1, 'Person ID', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 3, NULL, 'diagnosis_date', 'Diagnosis Date', 'DATETIME', 1, 'Diagnosis Date', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 4, 40, 'PHC_code', 'Condition Code', 'STRING', 1, 'Condition Code', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 5, 50, 'PHC_code_short_desc', 'Condition', 'STRING', 1, 'Condition', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 6, 80, 'PHC_code_desc', 'Condition Description', 'STRING', 1, 'Condition Description', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 7, 30, 'state_cd', 'State Code', 'STRING', 1, 'State Code', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 8, 50, 'State', 'State', 'STRING', 1, 'State', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 9, 25, 'cnty_cd', 'County Code', 'STRING', 1, 'County Code', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 10, 255, 'County', 'County', 'STRING', 1, 'County', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 11, 20, 'case_class_cd', 'Case Status', 'STRING', 1, 'Case Class Code', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 12, 20, 'cd_system_cd', 'Code System Code', 'STRING', 1, 'Code System Code', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 13, 20, 'cd_system_desc_txt', 'Code System', 'STRING', 1, 'Code System', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 14, 20, 'confidentiality_cd', 'Confidentiality Code', 'STRING', 1, 'Confidentiality Code', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 15, 80, 'confidentiality_desc_txt', 'Confidentiality', 'STRING', 1, 'Confidentiality', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 16, 20, 'detection_method_cd', 'Detection Method Code', 'STRING', 1, 'Detection Method Code', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 17, 80, 'detection_method_desc_txt', 'Detection Method', 'STRING', 1, 'Detection Method', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 18, 5, 'disease_imported_cd', 'Disease Imported Code', 'STRING', 1, 'Disease Imported Code', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 19, 80, 'disease_imported_desc_txt', 'Disease Imported', 'STRING', 1, 'Disease Imported', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 20, NULL, 'group_case_cnt', 'Group Case Count', 'INTEGER', 1, 'Group Case Count', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 21, 20, 'investigation_status_cd', 'Investigation Status Code', 'STRING', 1, 'Investigation Status Code', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 22, 20, 'jurisdiction_cd', 'Jurisdiction Code', 'STRING', 1, 'Jurisdiction Code', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 23, 4, 'mmwr_week', 'MMWR Week', 'STRING', 1, 'MMWR Week', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 24, 4, 'mmwr_year', 'MMWR Year', 'STRING', 1, 'MMWR Year', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 25, 1, 'outbreak_ind', 'Outbreak Indicator', 'STRING', 1, 'Outbreak Indicator', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 26, NULL, 'outbreak_from_time', 'Outbreak From Time', 'DATETIME', 1, 'Outbreak From Time', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 27, NULL, 'outbreak_to_time', 'Outbreak To Time', 'DATETIME', 1, 'Outbreak To Time', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 28, 80, 'outbreak_name', 'Outbreak Name', 'STRING', 1, 'Outbreak Name', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 29, 20, 'outcome_cd', 'Outcome Code', 'STRING', 1, 'Outcome Code', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 30, 3, 'pat_age_at_onset', 'Patient Age At Onset', 'STRING', 1, 'Patient Age At Onset', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 31, 20, 'pat_age_at_onset_unit_cd', 'Patient Age At Onset Unit Code', 'STRING', 1, 'Patient Age At Onset Unit Code', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 32, 20, 'prog_area_cd', 'Program Area Code', 'STRING', 1, 'Program Area Code', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 33, 20, 'record_status_cd', 'Record Status Code', 'STRING', 1, 'Record Status Code', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 34, 20, 'rpt_cnty_cd', 'Reporting County Code', 'STRING', 1, 'Reporting County Code', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 35, NULL, 'rpt_form_cmplt_time', 'Report Form Completion Time', 'DATETIME', 1, 'Report Form Completion Time', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 36, 20, 'rpt_source_cd', 'Report Source Code', 'STRING', 1, 'Report Source Code', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 37, 80, 'rpt_source_desc_txt', 'Report Source Type', 'STRING', 1, 'Report Source Type', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 38, NULL, 'rpt_to_county_time', 'Report To County Time', 'DATETIME', 1, 'Report To County Time', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 39, NULL, 'rpt_to_state_time', 'Report To State Time', 'DATETIME', 1, 'Report To State Time', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 40, 1, 'status_cd', 'PHC Status Code', 'STRING', 1, 'PHC Status Code', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 41, 40, 'awareness_cd', 'Awarness Code', 'STRING', 1, 'Awarness Code', 'N', NULL, NULL, 'N', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 42, 80, 'awareness_desc_txt', 'Awarness', 'STRING', 1, 'Awarness', 'N', NULL, NULL, 'N', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 43, NULL, 'adults_in_house_nbr', 'Number of Adults in House', 'INTEGER', 1, 'Number of Adults in House', 'N', NULL, NULL, 'N', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 44, 20, 'age_category_cd', 'Age Category Code', 'STRING', 1, 'Age Category Code', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 45, 3, 'age_reported', 'Age Reported', 'STRING', 1, 'Age Reported', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 46, NULL, 'age_reported_time', 'Age Reported Time', 'DATETIME', 1, 'Age Reported Time', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 47, 5, 'age_reported_unit_cd', 'Age Reported Unit Code', 'STRING', 1, 'Age Reported Unit Code', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 48, 1, 'birth_gender_cd', 'Birth Gender Code', 'STRING', 1, 'Birth Gender Code', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 49, NULL, 'birth_order_nbr', 'Birth Order Number', 'INTEGER', 1, 'Birth Order Number', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 50, NULL, 'birth_time', 'Birth Time', 'DATETIME', 1, 'Birth Time', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 51, NULL, 'birth_time_calc', 'Birth Time Calculated', 'DATETIME', 1, 'Birth Time Calculated', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 53, 80, 'Person_code_desc', 'Person Code Description', 'STRING', 1, 'Person Code Description', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 54, NULL, 'children_in_house_nbr', 'Number of Children in House', 'INTEGER', 1, 'Number of Children in House', 'N', NULL, NULL, 'N', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 55, 1, 'curr_sex_cd', 'Current Sex Code', 'STRING', 1, 'Current Sex Code', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 56, 1, 'deceased_ind_cd', 'Deceased Indicator Code', 'STRING', 1, 'Deceased Indicator Code', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 57, NULL, 'deceased_time', 'Deceased Time', 'DATETIME', 1, 'Deceased Time', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 58, 20, 'education_level_cd', 'Education Level Code', 'STRING', 1, 'Education Level Code', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 59, 80, 'education_level_desc_txt', 'Education Level', 'STRING', 1, 'Education Level', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 60, 6, 'ethnic_group_ind', 'Ethnic Group Indicator', 'STRING', 1, 'Ethnic Group Indicator', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 61, 50, 'Ethnic_group_ind_desc', 'Ethnic Group', 'STRING', 1, 'Ethnic Group', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 62, 20, 'marital_status_cd', 'Marital Status Code', 'STRING', 1, 'Marital Status Code', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 63, 80, 'marital_status_desc_txt', 'Marital Status', 'STRING', 1, 'Marital Status', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 64, 1, 'multiple_birth_ind', 'Multiple Birth Indicator', 'STRING', 1, 'Multiple Birth Indicator', 'N', NULL, NULL, 'N', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 65, 20, 'occupation_cd', 'Occupation Code', 'STRING', 1, 'Occupation Code', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 66, 20, 'prim_lang_cd', 'Primary Language Code', 'STRING', 1, 'Primary Language Code', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 67, 80, 'prim_lang_desc_txt', 'Primary Language', 'STRING', 1, 'Primary Language', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 68, NULL, 'ELP_from_time', 'ELP From Time', 'DATETIME', 1, 'ELP From Time', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 69, NULL, 'ELP_to_time', 'ELP To Time', 'DATETIME', 1, 'ELP To Time', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 70, 7, 'ELP_class_cd', 'ELP Class Code', 'STRING', 1, 'ELP Class Code', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 71, 20, 'ELP_use_cd', 'ELP Use Code', 'STRING', 1, 'Entity Locator Type such as H for home, WP for work place...', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 72, NULL, 'postal_locator_uid', 'Postal Locator ID', 'INTEGER', 1, 'Postal Locator ID', 'N', NULL, NULL, 'N', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 73, 20, 'census_block_cd', 'Census Block Code', 'STRING', 1, 'Census Block Code', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 74, 20, 'census_minor_civil_division_cd', 'Census Minor Civil Division Cd', 'STRING', 1, 'Census Minor Civil Division Cd', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 75, 20, 'census_track_cd', 'Census Track Code', 'STRING', 1, 'Census Track Code', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 76, 25, 'city_cd', 'City Code', 'STRING', 1, 'City Code', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 77, 80, 'city_desc_txt', 'City', 'STRING', 1, 'City', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 78, 60, 'cntry_cd', 'Country Code', 'STRING', 1, 'Country Code', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 79, 48, 'region_district_cd', 'Region District Code', 'STRING', 1, 'Region District Code', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 80, 20, 'MSA_congress_district_cd', 'MSA Congress District Code', 'STRING', 1, 'MSA Congress District Code', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 81, 10, 'zip_cd', 'Zip Code', 'STRING', 1, 'Zip Code', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 82, NULL, 'PST_record_status_time', 'Postal Record Status Time', 'DATETIME', 1, 'Postal Record Status Time', 'N', NULL, NULL, 'N', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 83, 20, 'PST_record_status_cd', 'Postal Record Status Code', 'STRING', 1, 'Postal Record Status Code', 'N', NULL, NULL, 'N', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 84, NULL, 'event_date', 'Report Date', 'DATETIME', 1, 'Event Date', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 85, NULL, 'OnSetDate', 'OnSet Date', 'DATETIME', 1, 'OnSet Date', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 86, NULL, 'NotificationDate', 'Notification Date', 'DATETIME', 1, 'Notification Sent Date', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 87, NULL, 'mart_record_creation_time', 'Record Load Time', 'DATETIME', 1, 'Record Load Time', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 88, NULL, 'firstNotificationSendDate', 'First Notification Date', 'DATETIME', 1, 'First Notification Sent Date', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 89, NULL, 'firstNotificationSubmittedBy', 'First Notification Submitted By', 'INTEGER', 1, 'User Who Sent the First Notification', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 90, NULL, 'lastNotificationSendDate', 'Last Notification Sent Date', 'DATETIME', 1, 'Last Notification Sent Date', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 91, NULL, 'lastNotificationSubmittedBy', 'Last Notification Submitted By', 'INTEGER', 1, 'User Who Sent the Last Notification', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 92, NULL, 'notifSentCount', 'Number of Notification Sent', 'INTEGER', 1, 'Number of Notification Sent', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 93, NULL, 'notifCreatedCount', 'Number of Notification Created', 'INTEGER', 1, 'Number of Notification Created', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 94, NULL, 'confirmation_method_time', 'Confirmation Method Time', 'DATETIME', 1, 'Confirmation Method Time', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 95, 20, 'confirmation_method_cd', 'Confirmation Method Code', 'STRING', 1, 'Confirmation Method Code', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 96, NULL, 'investigatorAssignedDate', 'Investigator Assigned Date', 'DATETIME', 1, 'Investigator Assigned Date', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 97, 1, 'case_type_cd', 'Case Type Code', 'STRING', 1, 'Case Type as in  Summary or Individual', 'Y', NULL, NULL, 'Y', 'A', NULL); 

INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 98, 102, 'providerName', 'Physician Name', 'STRING', 1, 'Physician or Provider Name', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 99, 102, 'patientName', 'Patient Name', 'STRING', 1, 'Patient Name', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 100, 102, 'investigatorName', 'Investigator Name', 'STRING', 1, 'Investigator Name', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 102, 50, 'jurisdiction', 'Jurisdiction', 'STRING', 1, 'Jurisdiction', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 104, 20, 'firstNotificationStatus', 'First Notification Status', 'STRING', 1, 'First Notification Status', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 106, NULL, 'investigationStartDate', 'Investigation Start Date', 'DATETIME', 1, 'Investigation Start Date', 'Y', NULL, NULL, 'Y', 'A', NULL); 
INSERT INTO DATA_SOURCE_COLUMN ( COLUMN_UID, COLUMN_MAX_LEN, COLUMN_NAME, COLUMN_TITLE,COLUMN_TYPE_CODE, DATA_SOURCE_UID, DESC_TXT, DISPLAYABLE, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTERABLE, STATUS_CD, STATUS_TIME ) 
VALUES ( 108, 100, 'organizationName', 'Report Source Name', 'STRING', 1, 'Reporting Source Organization Name', 'Y', NULL, NULL, 'Y', 'A', NULL); 



--commit;
 
