INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 2, 7, 1, 1, 2, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 3, 8, 1, 1, 3, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 13, 5, 1, 2, 6, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 16, 7, 1, 3, 2, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 18, 10, 1, 3, 4, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 22, 79, 1, 4, 1, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 24, 8, 1, 4, 3, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 29, 79, 1, 5, 1, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 31, 8, 1, 5, 3, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 43, 79, 1, 7, 1, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 50, 79, 1, 8, 1, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 57, 4, 1, 1, 8, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 4, 10, 1, 1, 4, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 11, 10, 1, 2, 4, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 21, 84, 1, 3, 7, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 27, 5, 1, 4, 6, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 28, 84, 1, 4, 7, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 36, 79, 1, 6, 1, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 38, 8, 1, 6, 3, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 40, 9, 1, 6, 5, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 41, 5, 1, 6, 6, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 42, 84, 1, 6, 7, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 47, 9, 1, 7, 5, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 51, 7, 1, 8, 2, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 55, 5, 1, 8, 6, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 59, 4, 1, 3, 8, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 63, 4, 1, 7, 8, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 65, 20, 1, 1, 9, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 66, 20, 1, 2, 9, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 67, 20, 1, 3, 9, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 68, 20, 1, 4, 9, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 69, 20, 1, 5, 9, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 70, 20, 1, 6, 9, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 71, 20, 1, 7, 9, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 72, 20, 1, 8, 9, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 1, 79, 1, 1, 1, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 6, 5, 1, 1, 6, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 10, 8, 1, 2, 3, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 15, 79, 1, 3, 1, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 17, 8, 1, 3, 3, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 20, 5, 1, 3, 6, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 23, 7, 1, 4, 2, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 25, 10, 1, 4, 4, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 26, 9, 1, 4, 5, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 32, 10, 1, 5, 4, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 33, 9, 1, 5, 5, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 34, 5, 1, 5, 6, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 35, 84, 1, 5, 7, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 37, 7, 1, 6, 2, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 39, 10, 1, 6, 4, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 45, 8, 1, 7, 3, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 60, 4, 1, 4, 8, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 61, 4, 1, 5, 8, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 62, 4, 1, 6, 8, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 5, 9, 1, 1, 5, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 7, 84, 1, 1, 7, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 8, 79, 1, 2, 1, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 9, 7, 1, 2, 2, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 12, 9, 1, 2, 5, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 14, 84, 1, 2, 7, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 19, 9, 1, 3, 5, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 30, 7, 1, 5, 2, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 44, 7, 1, 7, 2, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 46, 10, 1, 7, 4, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 48, 5, 1, 7, 6, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 49, 84, 1, 7, 7, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 52, 8, 1, 8, 3, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 53, 10, 1, 8, 4, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 54, 9, 1, 8, 5, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 56, 84, 1, 8, 7, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 58, 4, 1, 2, 8, 'A', NULL); 
INSERT INTO DISPLAY_COLUMN ( DISPLAY_COLUMN_UID, COLUMN_UID, DATA_SOURCE_UID, REPORT_UID,SEQUENCE_NBR, STATUS_CD, STATUS_TIME ) 
VALUES ( 64, 4, 1, 8, 8, 'A', NULL); 
--commit;
 
