INSERT INTO FILTER_CODE ( FILTER_UID, CODE_TABLE, DESC_TXT, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTER_CODE, FILTER_CODE_SET_NM, FILTER_TYPE, FILTER_NAME, STATUS_CD,STATUS_TIME ) 
VALUES ( 1, 'nbs_srt..code_value_general', 'Basic Condition Filter', NULL, NULL, 'C_D01', 'PHC_TYPE', 'BAS_CON_LIST', 'Diseases', 'A', NULL); 
INSERT INTO FILTER_CODE ( FILTER_UID, CODE_TABLE, DESC_TXT, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTER_CODE, FILTER_CODE_SET_NM, FILTER_TYPE, FILTER_NAME, STATUS_CD,STATUS_TIME ) 
VALUES ( 2, 'nbs_srt..state_code', 'Basic Jurisdiction Filter for State', NULL, NULL, 'J_S01', 'STATE_CCD', 'BAS_JUR_LIST', 'States', 'A', NULL); 
INSERT INTO FILTER_CODE ( FILTER_UID, CODE_TABLE, DESC_TXT, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTER_CODE, FILTER_CODE_SET_NM, FILTER_TYPE, FILTER_NAME, STATUS_CD,STATUS_TIME ) 
VALUES ( 3, 'nbs_srt..state_county_code', 'Basic Jurisdiction Filter for County', NULL, NULL, 'J_C01', 'COUNTY_CCD', 'BAS_JUR_LIST', 'Counties', 'A', NULL); 
INSERT INTO FILTER_CODE ( FILTER_UID, CODE_TABLE, DESC_TXT, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTER_CODE, FILTER_CODE_SET_NM, FILTER_TYPE, FILTER_NAME, STATUS_CD,STATUS_TIME ) 
VALUES ( 4, 'nbs_srt..state_county_code', 'Basic Jurisdiction Filter for Region', NULL, NULL, 'J_R01', 'COUNTY_CCD', 'BAS_JUR_LIST', 'Regions', 'A', NULL); 
INSERT INTO FILTER_CODE ( FILTER_UID, CODE_TABLE, DESC_TXT, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTER_CODE, FILTER_CODE_SET_NM, FILTER_TYPE, FILTER_NAME, STATUS_CD,STATUS_TIME ) 
VALUES ( 5, 'NONE', 'Basic Time Filter for Time Range accepts MM/YYYY to MM/YYYY', NULL, NULL, 'T_T01', NULL, 'BAS_TIM_RANGE', 'Time Range', 'A', NULL); 
INSERT INTO FILTER_CODE ( FILTER_UID, CODE_TABLE, DESC_TXT, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTER_CODE, FILTER_CODE_SET_NM, FILTER_TYPE, FILTER_NAME, STATUS_CD,STATUS_TIME ) 
VALUES ( 6, 'NONE', 'Basic Time Filter for Time Period Has two drop downs for YYYY to YYYY', NULL, NULL, 'T_T02', NULL, 'BAS_TIM_RANGE_LIST', 'Time Period', 'A', NULL); 
INSERT INTO FILTER_CODE ( FILTER_UID, CODE_TABLE, DESC_TXT, EFFECTIVE_FROM_TIME, EFFECTIVE_TO_TIME,FILTER_CODE, FILTER_CODE_SET_NM, FILTER_TYPE, FILTER_NAME, STATUS_CD,STATUS_TIME ) 
VALUES ( 7, 'NONE', 'Advanced filter representing the Where Clause Builder', NULL, NULL, 'A_W01', NULL, 'ADV_WCB', 'Where Clause Builder', 'A', NULL); 
--commit;
 
