INSERT INTO REPORT_FILTER ( REPORT_FILTER_UID, REPORT_UID, DATA_SOURCE_UID, FILTER_UID, STATUS_CD,MAX_VALUE_CNT, MIN_VALUE_CNT, COLUMN_UID ) 
VALUES ( 12, 5, 1, 1, 'A', 1, 1, 4); 
INSERT INTO REPORT_FILTER ( REPORT_FILTER_UID, REPORT_UID, DATA_SOURCE_UID, FILTER_UID, STATUS_CD,MAX_VALUE_CNT, MIN_VALUE_CNT, COLUMN_UID ) 
VALUES ( 13, 5, 1, 5, 'A', 2, 1, 84); 
INSERT INTO REPORT_FILTER ( REPORT_FILTER_UID, REPORT_UID, DATA_SOURCE_UID, FILTER_UID, STATUS_CD,MAX_VALUE_CNT, MIN_VALUE_CNT, COLUMN_UID ) 
VALUES ( 20, 8, 1, 1, 'A', 1, 1, 4); 
INSERT INTO REPORT_FILTER ( REPORT_FILTER_UID, REPORT_UID, DATA_SOURCE_UID, FILTER_UID, STATUS_CD,MAX_VALUE_CNT, MIN_VALUE_CNT, COLUMN_UID ) 
VALUES ( 23, 9, 1, 1, 'A', -1, 1, 4); 
INSERT INTO REPORT_FILTER ( REPORT_FILTER_UID, REPORT_UID, DATA_SOURCE_UID, FILTER_UID, STATUS_CD,MAX_VALUE_CNT, MIN_VALUE_CNT, COLUMN_UID ) 
VALUES ( 24, 9, 1, 2, 'A', 1, 1, 7); 
INSERT INTO REPORT_FILTER ( REPORT_FILTER_UID, REPORT_UID, DATA_SOURCE_UID, FILTER_UID, STATUS_CD,MAX_VALUE_CNT, MIN_VALUE_CNT, COLUMN_UID ) 
VALUES ( 25, 9, 1, 3, 'A', -1, 1, 9); 
INSERT INTO REPORT_FILTER ( REPORT_FILTER_UID, REPORT_UID, DATA_SOURCE_UID, FILTER_UID, STATUS_CD,MAX_VALUE_CNT, MIN_VALUE_CNT, COLUMN_UID ) 
VALUES ( 26, 9, 1, 5, 'A', 2, 1, 84); 
INSERT INTO REPORT_FILTER ( REPORT_FILTER_UID, REPORT_UID, DATA_SOURCE_UID, FILTER_UID, STATUS_CD,MAX_VALUE_CNT, MIN_VALUE_CNT, COLUMN_UID ) 
VALUES ( 28, 2, 1, 7, 'A', -1, 0, NULL); 
INSERT INTO REPORT_FILTER ( REPORT_FILTER_UID, REPORT_UID, DATA_SOURCE_UID, FILTER_UID, STATUS_CD,MAX_VALUE_CNT, MIN_VALUE_CNT, COLUMN_UID ) 
VALUES ( 32, 6, 1, 7, 'A', -1, 0, NULL); 
INSERT INTO REPORT_FILTER ( REPORT_FILTER_UID, REPORT_UID, DATA_SOURCE_UID, FILTER_UID, STATUS_CD,MAX_VALUE_CNT, MIN_VALUE_CNT, COLUMN_UID ) 
VALUES ( 33, 7, 1, 7, 'A', -1, 0, NULL); 
INSERT INTO REPORT_FILTER ( REPORT_FILTER_UID, REPORT_UID, DATA_SOURCE_UID, FILTER_UID, STATUS_CD,MAX_VALUE_CNT, MIN_VALUE_CNT, COLUMN_UID ) 
VALUES ( 34, 8, 1, 7, 'A', -1, 0, NULL); 
INSERT INTO REPORT_FILTER ( REPORT_FILTER_UID, REPORT_UID, DATA_SOURCE_UID, FILTER_UID, STATUS_CD,MAX_VALUE_CNT, MIN_VALUE_CNT, COLUMN_UID ) 
VALUES ( 35, 9, 1, 7, 'A', -1, 0, NULL); 
INSERT INTO REPORT_FILTER ( REPORT_FILTER_UID, REPORT_UID, DATA_SOURCE_UID, FILTER_UID, STATUS_CD,MAX_VALUE_CNT, MIN_VALUE_CNT, COLUMN_UID ) 
VALUES ( 5, 2, 1, 1, 'A', -1, 1, 4); 
INSERT INTO REPORT_FILTER ( REPORT_FILTER_UID, REPORT_UID, DATA_SOURCE_UID, FILTER_UID, STATUS_CD,MAX_VALUE_CNT, MIN_VALUE_CNT, COLUMN_UID ) 
VALUES ( 6, 2, 1, 2, 'A', 1, 1, 7); 
INSERT INTO REPORT_FILTER ( REPORT_FILTER_UID, REPORT_UID, DATA_SOURCE_UID, FILTER_UID, STATUS_CD,MAX_VALUE_CNT, MIN_VALUE_CNT, COLUMN_UID ) 
VALUES ( 7, 3, 1, 1, 'A', -1, 1, 4); 
INSERT INTO REPORT_FILTER ( REPORT_FILTER_UID, REPORT_UID, DATA_SOURCE_UID, FILTER_UID, STATUS_CD,MAX_VALUE_CNT, MIN_VALUE_CNT, COLUMN_UID ) 
VALUES ( 9, 4, 1, 1, 'A', 1, 1, 4); 
INSERT INTO REPORT_FILTER ( REPORT_FILTER_UID, REPORT_UID, DATA_SOURCE_UID, FILTER_UID, STATUS_CD,MAX_VALUE_CNT, MIN_VALUE_CNT, COLUMN_UID ) 
VALUES ( 1, 1, 1, 1, 'A', -1, 1, 4); 
INSERT INTO REPORT_FILTER ( REPORT_FILTER_UID, REPORT_UID, DATA_SOURCE_UID, FILTER_UID, STATUS_CD,MAX_VALUE_CNT, MIN_VALUE_CNT, COLUMN_UID ) 
VALUES ( 27, 1, 1, 7, 'A', -1, 0, NULL); 
INSERT INTO REPORT_FILTER ( REPORT_FILTER_UID, REPORT_UID, DATA_SOURCE_UID, FILTER_UID, STATUS_CD,MAX_VALUE_CNT, MIN_VALUE_CNT, COLUMN_UID ) 
VALUES ( 3, 1, 1, 3, 'A', -1, 1, 9); 
INSERT INTO REPORT_FILTER ( REPORT_FILTER_UID, REPORT_UID, DATA_SOURCE_UID, FILTER_UID, STATUS_CD,MAX_VALUE_CNT, MIN_VALUE_CNT, COLUMN_UID ) 
VALUES ( 4, 1, 1, 5, 'A', 2, 1, 84); 
INSERT INTO REPORT_FILTER ( REPORT_FILTER_UID, REPORT_UID, DATA_SOURCE_UID, FILTER_UID, STATUS_CD,MAX_VALUE_CNT, MIN_VALUE_CNT, COLUMN_UID ) 
VALUES ( 2, 1, 1, 2, 'A', 1, 1, 7); 
INSERT INTO REPORT_FILTER ( REPORT_FILTER_UID, REPORT_UID, DATA_SOURCE_UID, FILTER_UID, STATUS_CD,MAX_VALUE_CNT, MIN_VALUE_CNT, COLUMN_UID ) 
VALUES ( 555, 5, 1, 2, 'A', 1, 1, 7); 
INSERT INTO REPORT_FILTER ( REPORT_FILTER_UID, REPORT_UID, DATA_SOURCE_UID, FILTER_UID, STATUS_CD,MAX_VALUE_CNT, MIN_VALUE_CNT, COLUMN_UID ) 
VALUES ( 10, 4, 1, 2, 'A', 1, 1, 7); 
INSERT INTO REPORT_FILTER ( REPORT_FILTER_UID, REPORT_UID, DATA_SOURCE_UID, FILTER_UID, STATUS_CD,MAX_VALUE_CNT, MIN_VALUE_CNT, COLUMN_UID ) 
VALUES ( 18, 7, 1, 2, 'A', 1, 1, 7); 
INSERT INTO REPORT_FILTER ( REPORT_FILTER_UID, REPORT_UID, DATA_SOURCE_UID, FILTER_UID, STATUS_CD,MAX_VALUE_CNT, MIN_VALUE_CNT, COLUMN_UID ) 
VALUES ( 19, 7, 1, 6, 'A', 2, 1, 84); 
INSERT INTO REPORT_FILTER ( REPORT_FILTER_UID, REPORT_UID, DATA_SOURCE_UID, FILTER_UID, STATUS_CD,MAX_VALUE_CNT, MIN_VALUE_CNT, COLUMN_UID ) 
VALUES ( 8, 3, 1, 2, 'A', 1, 1, 7); 
INSERT INTO REPORT_FILTER ( REPORT_FILTER_UID, REPORT_UID, DATA_SOURCE_UID, FILTER_UID, STATUS_CD,MAX_VALUE_CNT, MIN_VALUE_CNT, COLUMN_UID ) 
VALUES ( 14, 6, 1, 1, 'A', 1, 1, 4); 
INSERT INTO REPORT_FILTER ( REPORT_FILTER_UID, REPORT_UID, DATA_SOURCE_UID, FILTER_UID, STATUS_CD,MAX_VALUE_CNT, MIN_VALUE_CNT, COLUMN_UID ) 
VALUES ( 15, 6, 1, 2, 'A', 1, 1, 7); 
INSERT INTO REPORT_FILTER ( REPORT_FILTER_UID, REPORT_UID, DATA_SOURCE_UID, FILTER_UID, STATUS_CD,MAX_VALUE_CNT, MIN_VALUE_CNT, COLUMN_UID ) 
VALUES ( 16, 6, 1, 6, 'A', 2, 1, 84); 
INSERT INTO REPORT_FILTER ( REPORT_FILTER_UID, REPORT_UID, DATA_SOURCE_UID, FILTER_UID, STATUS_CD,MAX_VALUE_CNT, MIN_VALUE_CNT, COLUMN_UID ) 
VALUES ( 21, 8, 1, 3, 'A', -1, 1, 9); 
INSERT INTO REPORT_FILTER ( REPORT_FILTER_UID, REPORT_UID, DATA_SOURCE_UID, FILTER_UID, STATUS_CD,MAX_VALUE_CNT, MIN_VALUE_CNT, COLUMN_UID ) 
VALUES ( 22, 8, 1, 6, 'A', 2, 1, 84); 
INSERT INTO REPORT_FILTER ( REPORT_FILTER_UID, REPORT_UID, DATA_SOURCE_UID, FILTER_UID, STATUS_CD,MAX_VALUE_CNT, MIN_VALUE_CNT, COLUMN_UID ) 
VALUES ( 30, 4, 1, 7, 'A', -1, 0, NULL); 
INSERT INTO REPORT_FILTER ( REPORT_FILTER_UID, REPORT_UID, DATA_SOURCE_UID, FILTER_UID, STATUS_CD,MAX_VALUE_CNT, MIN_VALUE_CNT, COLUMN_UID ) 
VALUES ( 888, 8, 1, 2, 'A', 1, 1, 7); 
INSERT INTO REPORT_FILTER ( REPORT_FILTER_UID, REPORT_UID, DATA_SOURCE_UID, FILTER_UID, STATUS_CD,MAX_VALUE_CNT, MIN_VALUE_CNT, COLUMN_UID ) 
VALUES ( 17, 7, 1, 1, 'A', -1, 1, 4); 
INSERT INTO REPORT_FILTER ( REPORT_FILTER_UID, REPORT_UID, DATA_SOURCE_UID, FILTER_UID, STATUS_CD,MAX_VALUE_CNT, MIN_VALUE_CNT, COLUMN_UID ) 
VALUES ( 29, 3, 1, 7, 'A', -1, 0, NULL); 
INSERT INTO REPORT_FILTER ( REPORT_FILTER_UID, REPORT_UID, DATA_SOURCE_UID, FILTER_UID, STATUS_CD,MAX_VALUE_CNT, MIN_VALUE_CNT, COLUMN_UID ) 
VALUES ( 31, 5, 1, 7, 'A', -1, 0, NULL); 
INSERT INTO REPORT_FILTER ( REPORT_FILTER_UID, REPORT_UID, DATA_SOURCE_UID, FILTER_UID, STATUS_CD,MAX_VALUE_CNT, MIN_VALUE_CNT, COLUMN_UID ) 
VALUES ( 11, 4, 1, 5, 'A', 2, 1, 84); 
INSERT INTO REPORT_FILTER ( REPORT_FILTER_UID, REPORT_UID, DATA_SOURCE_UID, FILTER_UID, STATUS_CD,MAX_VALUE_CNT, MIN_VALUE_CNT, COLUMN_UID ) 
VALUES ( 36, 10, 1, 1, 'A', -1, 1, 4); 
INSERT INTO REPORT_FILTER ( REPORT_FILTER_UID, REPORT_UID, DATA_SOURCE_UID, FILTER_UID, STATUS_CD,MAX_VALUE_CNT, MIN_VALUE_CNT, COLUMN_UID ) 
VALUES ( 37, 10, 1, 5, 'A', 2, 1, 84); 
INSERT INTO REPORT_FILTER ( REPORT_FILTER_UID, REPORT_UID, DATA_SOURCE_UID, FILTER_UID, STATUS_CD,MAX_VALUE_CNT, MIN_VALUE_CNT, COLUMN_UID ) 
VALUES ( 38, 10, 1, 7, 'A', -1, 0, NULL); 
--commit;
 
