SELECT DISTINCT 
					'PHDC' AS DOC_TYPE_CD,
					'1.3' AS DOC_TYPE_VERSION_TXT,
				  CASE
				  WHEN A.QUESTION_OID IS NULL THEN '2.16.840.1.114222.4.5.1'
				  WHEN A.QUESTION_OID IS NOT NULL THEN A.QUESTION_OID
				  END AS QUES_CODE_SYSTEM_CD,
					CASE
					WHEN A.QUESTION_OID_SYSTEM_TXT IS NULL THEN 'NEDSS Base System'
					WHEN A.QUESTION_OID_SYSTEM_TXT IS NOT NULL THEN A.QUESTION_OID_SYSTEM_TXT
					END AS QUES_CODE_SYSTEM_DESC_TXT, UPPER(A.DATA_TYPE) AS DATA_TYPE,
					A.QUESTION_IDENTIFIER AS QUESTION_IDENTIFIER, A.QUESTION_LABEL AS QUES_DISPLAY_NAME, D.question_label AS SECTION_NM, 'NBS' AS SENDING_SYSTEM_CD
		   FROM NBS_ODSE.NBS_QUESTION  A
				INNER JOIN
				NBS_ODSE.NBS_UI_METADATA  C
				ON A.NBS_QUESTION_UID = C.NBS_QUESTION_UID
				LEFT OUTER JOIN
				NBS_ODSE.NND_METADATA B
				ON A.QUESTION_IDENTIFIER = B.QUESTION_IDENTIFIER AND 
				(UPPER(A.DATA_LOCATION) NOT LIKE '%ANSWER_TXT' AND UPPER(A.DATA_LOCATION) NOT LIKE 'CONFIRMATION_METHOD%' AND  UPPER(A.DATA_LOCATION) NOT LIKE 'CASE_MANAGEMENT%')
				LEFT OUTER JOIN (SELECT DISTINCT INVESTIGATION_FORM_CD, QUESTION_LABEL, question_group_seq_nbr FROM NBS_ODSE.NBS_UI_METADATA WHERE question_group_seq_nbr IS NOT NULL AND nbs_ui_component_uid=1016) D ON
				C.investigation_form_cd = D.investigation_form_cd AND C.question_group_seq_nbr = D.question_group_seq_nbr  where c.question_identifier not like 'MSG%' 
				ORDER BY A.QUESTION_IDENTIFIER
				