SELECT DISTINCT
       UPPER(CODE_VALUE_GENERAL.CODE) AS ANS_FROM_CODE,
       CODE_VALUE_GENERAL.CODE_SYSTEM_CD AS ANS_FROM_CODE_SYSTEM_CD,
       CODE_VALUE_GENERAL.CODE_SYSTEM_DESC_TXT AS ANS_FROM_CODE_SYSTEM_DESC_TXT,
       CODE_VALUE_GENERAL.CODE_SHORT_DESC_TXT AS ANS_FROM_DISPLAY_NM,
       CODE_VALUE_GENERAL.CONCEPT_CODE AS ANS_TO_CODE,
       CODE_VALUE_GENERAL.CODE_SYSTEM_CD AS ANS_TO_CODE_SYSTEM_CD,
       CODE_VALUE_GENERAL.CODE_SYSTEM_DESC_TXT AS ANS_TO_CODE_SYSTEM_DESC_TXT,
       CODE_VALUE_GENERAL.CONCEPT_PREFERRED_NM AS ANS_TO_DISPLAY_NM,
       CASE
           WHEN CODE_VALUE_GENERAL.CODE = CODE_VALUE_GENERAL.CONCEPT_CODE
           THEN 'NO'
           ELSE 'YES'
       END AS CODE_TRANSLATION_REQUIRED,
       'PHDC' AS DOC_TYPE_CD,
       '1.3' AS DOC_TYPE_VERSION_TXT,
       CASE
           WHEN NBS_ui_metadata.QUESTION_OID IS NULL
           THEN '2.16.840.1.114222.4.5.1'
           WHEN NBS_ui_metadata.QUESTION_OID IS NOT NULL
           THEN NBS_ui_metadata.QUESTION_OID
       END AS QUES_CODE_SYSTEM_CD,
       QUESTION_IDENTIFIER,
       'NBS' AS SENDING_SYSTEM_CD
FROM NBS_ODSE..NBS_ui_metadata
     INNER JOIN NBS_SRTE..CODESET ON NBS_ui_metadata.CODE_SET_GROUP_ID = CODESET.CODE_SET_GROUP_ID
     INNER JOIN NBS_SRTE..CODE_VALUE_GENERAL ON CODE_VALUE_GENERAL.CODE_SET_NM = CODESET.CODE_SET_NM
WHERE NBS_ui_metadata.DATA_TYPE IN('CODED')
     AND (UPPER(NBS_ui_metadata.DATA_LOCATION) NOT LIKE '%ANSWER_TXT'
          AND UPPER(NBS_ui_metadata.DATA_LOCATION) NOT LIKE 'CONFIRMATION_METHOD%'
          AND UPPER(NBS_ui_metadata.DATA_LOCATION) NOT LIKE 'CASE_MANAGEMENT%')
UNION
SELECT DISTINCT
       UPPER(A.CODE) AS ANS_FROM_CODE,
       A.CODE_SYSTEM_CD AS ANS_FROM_CODE_SYSTEM_CD,
       A.CODE_SYSTEM_DESC_TXT AS ANS_FROM_CODE_SYSTEM_DESC_TXT,
       A.CODE_DESC_TXT AS ANS_FROM_DISPLAY_NM,
       A.CODE AS ANS_TO_CODE,
       A.CODE_SYSTEM_CD AS ANS_TO_CODE_SYSTEM_CD,
       A.CODE_SYSTEM_DESC_TXT AS ANS_TO_CODE_SYSTEM_DESC_TXT,
       A.CODE_DESC_TXT AS ANS_TO_DISPLAY_NM,
       'YES' AS CODE_TRANSLATION_REQUIRED,
       'PHDC' AS DOC_TYPE_CD,
       '1.3' AS DOC_TYPE_VERSION_TXT,
       '2.16.840.1.114222.4.5.1' AS QUES_CODE_SYSTEM_CD,
       'COUNTY' AS QUESTION_IDENTIFIER,
       'NBS' AS SENDING_SYSTEM_CD
FROM NBS_SRTE..STATE_COUNTY_CODE_VALUE AS A
UNION
SELECT DISTINCT
       UPPER(A.CODE_DESC_TXT) AS ANS_FROM_CODE,
       A.CODE_SYSTEM_CD AS ANS_FROM_CODE_SYSTEM_CD,
       A.CODE_SYSTEM_DESC_TXT AS ANS_FROM_CODE_SYSTEM_DESC_TXT,
       A.CODE_DESC_TXT AS ANS_FROM_DISPLAY_NM,
       A.CODE AS ANS_TO_CODE,
       A.CODE_SYSTEM_CD AS ANS_TO_CODE_SYSTEM_CD,
       A.CODE_SYSTEM_DESC_TXT AS ANS_TO_CODE_SYSTEM_DESC_TXT,
       A.CODE_DESC_TXT AS ANS_TO_DISPLAY_NM,
       'YES' AS CODE_TRANSLATION_REQUIRED,
       'PHDC' AS DOC_TYPE_CD,
       '1.3' AS DOC_TYPE_VERSION_TXT,
       '2.16.840.1.114222.4.5.1' AS QUES_CODE_SYSTEM_CD,
       'COUNTY' AS QUESTION_IDENTIFIER,
       'NBS' AS SENDING_SYSTEM_CD
FROM NBS_SRTE..STATE_COUNTY_CODE_VALUE AS A
UNION
SELECT DISTINCT
       UPPER(A.CONDITION_CD) AS ANS_FROM_CODE,
       A.CODE_SYSTEM_CD AS ANS_FROM_CODE_SYSTEM_CD,
       A.CODE_SYSTEM_DESC_TXT AS ANS_FROM_CODE_SYSTEM_DESC_TXT,
       A.CONDITION_SHORT_NM AS ANS_FROM_DISPLAY_NM,
       A.CONDITION_CD AS ANS_TO_CODE,
       A.CODE_SYSTEM_CD AS ANS_TO_CODE_SYSTEM_CD,
       A.CODE_SYSTEM_DESC_TXT AS ANS_TO_CODE_SYSTEM_DESC_TXT,
       A.CONDITION_SHORT_NM AS ANS_TO_DISPLAY_NM,
       'YES' AS CODE_TRANSLATION_REQUIRED,
       'PHDC' AS DOC_TYPE_CD,
       '1.3' AS DOC_TYPE_VERSION_TXT,
       CASE
           WHEN B.QUESTION_OID IS NULL
           THEN '2.16.840.1.114222.4.5.1'
           WHEN B.QUESTION_OID IS NOT NULL
           THEN B.QUESTION_OID
       END AS QUES_CODE_SYSTEM_CD,
       B.QUESTION_IDENTIFIER,
       'NBS' AS SENDING_SYSTEM_CD
FROM NBS_SRTE..CONDITION_CODE AS A
     INNER JOIN NBS_SRTE..CODESET AS C ON A.CONDITION_CODESET_NM = C.CODE_SET_NM
     INNER JOIN NBS_ODSE..NBS_ui_metadata AS B ON B.CODE_SET_GROUP_ID = C.CODE_SET_GROUP_ID
                                                  AND (UPPER(B.DATA_LOCATION) NOT LIKE '%ANSWER_TXT'
                                                       AND UPPER(B.DATA_LOCATION) NOT LIKE 'CONFIRMATION_METHOD%'
                                                      AND UPPER(B.DATA_LOCATION) NOT LIKE 'CASE_MANAGEMENT%')
UNION
SELECT DISTINCT
       UPPER(state_nm) AS ANS_FROM_CODE,
       CODE_SYSTEM_CD AS ANS_FROM_CODE_SYSTEM_CD,
       CODE_SYSTEM_DESC_TXT AS ANS_FROM_CODE_SYSTEM_DESC_TXT,
       CODE_DESC_TXT AS ANS_FROM_DISPLAY_NM,
       State_cd AS ANS_TO_CODE,
       CODE_SYSTEM_CD AS ANS_TO_CODE_SYSTEM_CD,
       CODE_SYSTEM_DESC_TXT AS ANS_TO_CODE_SYSTEM_DESC_TXT,
       CODE_DESC_TXT AS ANS_TO_DISPLAY_NM,
       'YES' AS CODE_TRANSLATION_REQUIRED,
       'PHDC' AS DOC_TYPE_CD,
       '1.3' AS DOC_TYPE_VERSION_TXT,
       '2.16.840.1.114222.4.5.1' AS QUES_CODE_SYSTEM_CD,
       'STATE' AS QUESTION_IDENTIFIER,
       'NBS' AS SENDING_SYSTEM_CD
FROM NBS_SRTE..State_code
UNION
SELECT DISTINCT
       UPPER(State_cd) AS ANS_FROM_CODE,
       CODE_SYSTEM_CD AS ANS_FROM_CODE_SYSTEM_CD,
       CODE_SYSTEM_DESC_TXT AS ANS_FROM_CODE_SYSTEM_DESC_TXT,
       CODE_DESC_TXT AS ANS_FROM_DISPLAY_NM,
       State_cd AS ANS_TO_CODE,
       CODE_SYSTEM_CD AS ANS_TO_CODE_SYSTEM_CD,
       CODE_SYSTEM_DESC_TXT AS ANS_TO_CODE_SYSTEM_DESC_TXT,
       CODE_DESC_TXT AS ANS_TO_DISPLAY_NM,
       'YES' AS CODE_TRANSLATION_REQUIRED,
       'PHDC' AS DOC_TYPE_CD,
       '1.3' AS DOC_TYPE_VERSION_TXT,
       '2.16.840.1.114222.4.5.1' AS QUES_CODE_SYSTEM_CD,
       'STATE' AS QUESTION_IDENTIFIER,
       'NBS' AS SENDING_SYSTEM_CD
FROM NBS_SRTE..State_code
UNION
SELECT DISTINCT
       UPPER(CODE_VALUE_GENERAL.CODE) AS ANS_FROM_CODE,
       CODE_VALUE_GENERAL.CODE_SYSTEM_CD AS ANS_FROM_CODE_SYSTEM_CD,
       CODE_VALUE_GENERAL.CODE_SYSTEM_DESC_TXT AS ANS_FROM_CODE_SYSTEM_DESC_TXT,
       CODE_VALUE_GENERAL.CODE_SHORT_DESC_TXT AS ANS_FROM_DISPLAY_NM,
       CODE_VALUE_GENERAL.CONCEPT_CODE AS ANS_TO_CODE,
       CODE_VALUE_GENERAL.CODE_SYSTEM_CD AS ANS_TO_CODE_SYSTEM_CD,
       CODE_VALUE_GENERAL.CODE_SYSTEM_DESC_TXT AS ANS_TO_CODE_SYSTEM_DESC_TXT,
       CODE_VALUE_GENERAL.CONCEPT_PREFERRED_NM AS ANS_TO_DISPLAY_NM,
       CASE
           WHEN CODE_VALUE_GENERAL.CODE = CODE_VALUE_GENERAL.CONCEPT_CODE
           THEN 'NO'
           ELSE 'YES'
       END AS CODE_TRANSLATION_REQUIRED,
       'PHDC' AS DOC_TYPE_CD,
       '1.3' AS DOC_TYPE_VERSION_TXT,
       '2.16.840.1.114222.4.5.1' AS QUES_CODE_SYSTEM_CD,
       'COUNTRY' AS QUESTION_IDENTIFIER,
       'NBS' AS SENDING_SYSTEM_CD
FROM NBS_SRTE..code_value_general where code_set_nm='PSL_CNTRY'
UNION
SELECT DISTINCT
	  CODE_VALUE_GENERAL.CONCEPT_CODE AS ANS_FROM_CODE ,
       CODE_VALUE_GENERAL.CODE_SYSTEM_CD AS ANS_FROM_CODE_SYSTEM_CD,
       CODE_VALUE_GENERAL.CODE_SYSTEM_DESC_TXT AS ANS_FROM_CODE_SYSTEM_DESC_TXT,
       CODE_VALUE_GENERAL.CODE_SHORT_DESC_TXT AS ANS_FROM_DISPLAY_NM,
       CODE_VALUE_GENERAL.CONCEPT_CODE AS ANS_TO_CODE,
       CODE_VALUE_GENERAL.CODE_SYSTEM_CD AS ANS_TO_CODE_SYSTEM_CD,
       CODE_VALUE_GENERAL.CODE_SYSTEM_DESC_TXT AS ANS_TO_CODE_SYSTEM_DESC_TXT,
       CODE_VALUE_GENERAL.CONCEPT_PREFERRED_NM AS ANS_TO_DISPLAY_NM,
       'NO' AS CODE_TRANSLATION_REQUIRED,
       'PHDC' AS DOC_TYPE_CD,
       '1.3' AS DOC_TYPE_VERSION_TXT,
       '2.16.840.1.114222.4.5.1' AS QUES_CODE_SYSTEM_CD,
       'COUNTRY' AS QUESTION_IDENTIFIER,
       'NBS' AS SENDING_SYSTEM_CD
FROM NBS_SRTE..code_value_general where code_set_nm='PSL_CNTRY' and CODE_VALUE_GENERAL.CONCEPT_CODE not in( select Alpha2_to_code from NBS_SRTE..country_xref)
UNION
SELECT DISTINCT
       UPPER(Alpha2_to_code) AS ANS_FROM_CODE,
       to_code_system_cd AS ANS_FROM_CODE_SYSTEM_CD,
       to_code_desc_txt AS ANS_FROM_CODE_SYSTEM_DESC_TXT,
       from_code_desc_txt AS ANS_FROM_DISPLAY_NM,
       to_code AS ANS_TO_CODE,
       to_code_system_cd AS ANS_TO_CODE_SYSTEM_CD,
       to_code_desc_txt AS ANS_TO_CODE_SYSTEM_DESC_TXT,
       to_code_desc_txt AS ANS_TO_DISPLAY_NM,
       'YES' AS CODE_TRANSLATION_REQUIRED,
       'PHDC' AS DOC_TYPE_CD,
       '1.3' AS DOC_TYPE_VERSION_TXT,
       '2.16.840.1.114222.4.5.1' AS QUES_CODE_SYSTEM_CD,
       'COUNTRY' AS QUESTION_IDENTIFIER,
       'NBS' AS SENDING_SYSTEM_CD
FROM NBS_SRTE..country_xref
UNION
SELECT DISTINCT
       'false' AS ANS_FROM_CODE,
       '2.16.840.1.113883.12.136' AS ANS_FROM_CODE_SYSTEM_CD,
       'Yes/No Indicator (HL7)' AS ANS_FROM_CODE_SYSTEM_DESC_TXT,
       'False' AS ANS_FROM_DISPLAY_NM,
       'N' AS ANS_TO_CODE,
       '2.16.840.1.113883.12.136' AS ANS_TO_CODE_SYSTEM_CD,
       'Yes/No Indicator (HL7)' AS ANS_TO_CODE_SYSTEM_DESC_TXT,
       'No' AS ANS_TO_DISPLAY_NM,
       'YES' AS CODE_TRANSLATION_REQUIRED,
       'PHDC' AS DOC_TYPE_CD,
       '1.3' AS DOC_TYPE_VERSION_TXT,
       '2.16.840.1.114222.4.5.1' AS QUES_CODE_SYSTEM_CD,
       'DEM127' AS QUESTION_IDENTIFIER,
       'NBS' AS SENDING_SYSTEM_CD
UNION
SELECT DISTINCT
       'true' AS ANS_FROM_CODE,
       '2.16.840.1.113883.12.136' AS ANS_FROM_CODE_SYSTEM_CD,
       'Yes/No Indicator (HL7)' AS ANS_FROM_CODE_SYSTEM_DESC_TXT,
       'False' AS ANS_FROM_DISPLAY_NM,
       'Y' AS ANS_TO_CODE,
       '2.16.840.1.113883.12.136' AS ANS_TO_CODE_SYSTEM_CD,
       'Yes/No Indicator (HL7)' AS ANS_TO_CODE_SYSTEM_DESC_TXT,
       'Yes' AS ANS_TO_DISPLAY_NM,
       'YES' AS CODE_TRANSLATION_REQUIRED,
       'PHDC' AS DOC_TYPE_CD,
       '1.3' AS DOC_TYPE_VERSION_TXT,
       '2.16.840.1.114222.4.5.1' AS QUES_CODE_SYSTEM_CD,
       'DEM127' AS QUESTION_IDENTIFIER,
       'NBS' AS SENDING_SYSTEM_CD
UNION
SELECT DISTINCT
       '77386006' AS ANS_FROM_CODE,
       '2.16.840.1.113883.6.96' AS ANS_FROM_CODE_SYSTEM_CD,
       'SNOMED-CT' AS ANS_FROM_CODE_SYSTEM_DESC_TXT,
       'False' AS ANS_FROM_DISPLAY_NM,
       'Y' AS ANS_TO_CODE,
       '2.16.840.1.113883.12.136' AS ANS_TO_CODE_SYSTEM_CD,
       'Yes/No Indicator (HL7)' AS ANS_TO_CODE_SYSTEM_DESC_TXT,
       'Yes' AS ANS_TO_DISPLAY_NM,
       'YES' AS CODE_TRANSLATION_REQUIRED,
       'PHDC' AS DOC_TYPE_CD,
       '1.3' AS DOC_TYPE_VERSION_TXT,
       '2.16.840.1.114222.4.5.1' AS QUES_CODE_SYSTEM_CD,
       'INV178' AS QUESTION_IDENTIFIER,
       'NBS' AS SENDING_SYSTEM_CD





	   