####################################################################################################
# DAILY - Process will be executed at the specified time of day (HH:MM)				   #
# HOURLY - Process will be executed every X hours (HH) (Must be a two digit number 00 - 23)	   #
# MINUTE - Process will be executed every X minutes (MM) (Must be a two digit number 00 - 59)      #
#												   #
####################################################################################################


ELR_IMPORTER_SCHEDULE_TO_RUN=NO
ELR_IMPORTER_SCHEDULE_TIMEGAP_IN_MINUTES=2
ELR_IMPORTER_SCHEDULE_HOURlY_OR_DAILY_OR_MINUTE=DAILY
ELR_IMPORTER_SCHEDULE_TIME_IN_HOUR=17
ELR_IMPORTER_SCHEDULE_TIME_IN_MINUTE=00

#####################USER_PROFILE####################
USER_PROFILE_SCHEDULE_TO_RUN=NO
USER_PROFILE_SCHEDULE_TIMEGAP_IN_MINUTES=2
POPULATE_FLAG=ODS_AND_HTML
USER_PROFILE_USER_NAME=PAA
USER_PROFILE_SCHEDULE_HOURLY_OR_DAILY_OR_MINUTE=DAILY
USER_PROFILE_SCHEDULE_TIME_IN_HOUR=22
USER_PROFILE_SCHEDULE_TIME_IN_MINUTE=00

#####################MSGOUT####################
MSGOUT_SCHEDULE_TO_RUN=NO
MSGOUT_SCHEDULE_TIMEGAP_IN_MINUTES=2
MSGOUT_SCHEDULE_HOURLY_OR_DAILY_OR_MINUTE=DAILY
MSGOUT_SCHEDULE_TIME_IN_HOUR=20
MSGOUT_SCHEDULE_TIME_IN_MINUTE=00

################PHCMART#####################
PHCMART_SCHEDULE_TO_RUN=NO
PHCMART_SCHEDULE_TIMEGAP_IN_MINUTES=2
PHCMART_SCHEDULE_TO_RUN_SCHEDULE_HOURLY_OR_DAILY_OR_MINUTE=DAILY
PHCMART_SCHEDULE_TO_RUN_SCHEDULE_TIME_IN_HOUR=21
PHCMART_SCHEDULE_TO_RUN_SCHEDULE_TIME_IN_MINUTE=00

###################DEDUPLICATION SAME#######################
DEDUPLICATION_SAME_SCHEDULE_TO_RUN=NO
DEDUPLICATION_SAME_SCHEDULE_TIMEGAP_IN_MINUTES=2
DEDUPLICATION_SAME_SCHEDULE_HOURLY_OR_DAILY_OR_MINUTE=DAILY
DEDUPLICATION_SAME_SCHEDULE_TIME_IN_HOUR=18
DEDUPLICATION_SAME_SCHEDULE_TIME_IN_MINUTE=00

###################DEDUPLICATION SIMILAR#######################
DEDUPLICATION_SIMILAR_SCHEDULE_TO_RUN=NO
DEDUPLICATION_SIMILAR_SCHEDULE_TIMEGAP_IN_MINUTES=2
DEDUPLICATION_SIMILAR_SCHEDULE_HOURLY_OR_DAILY_OR_MINUTE=DAILY
DEDUPLICATION_SIMILAR_SCHEDULE_TIME_IN_HOUR=18
DEDUPLICATION_SIMILAR_SCHEDULE_TIME_IN_MINUTE=00

###################GEOCODING#######################
GEOCODING_SCHEDULE_TO_RUN=NO
GEOCODING_SCHEDULE_TIMEGAP_IN_MINUTES=2
GEOCODING_SCHEDULE_HOURLY_OR_DAILY_OR_MINUTE=DAILY
GEOCODING_SCHEDULE_TIME_IN_HOUR=18
GEOCODING_SCHEDULE_TIME_IN_MINUTE=30

######################MASTERETL##############################
MASTERETL_ETL_PROCESS=FULL
MASTER_ETL_SCHEDULE_TO_RUN=NO
MASTER_ETL_SCHEDULE_TIMEGAP_IN_MINUTES=30
MASTERETL_SCHEDULE_HOURLY_OR_DAILY_OR_MINUTE=DAILY
MASTERETL_SCHEDULE_TIME_IN_HOUR=11
MASTERETL_SCHEDULE_TIME_IN_MINUTE=04

###########################NNDLSFEXTRACTION######################
NND_LDF_EXTRACTION_SCHEDULE_TO_RUN=NO
NND_LDF_EXTRACTION_SCHEDULE_TIMEGAP_IN_MINUTES=2
NND_LDF_EXT_SCHEDULE_TO_RUN_SCHEDULE_HOURLY_OR_DAILY_OR_MINUTE=DAILY
NND_LDF_EXT_SCHEDULE_TO_RUN_SCHEDULE_TIME_IN_HOUR=19
NND_LDF_EXT_SCHEDULE_TO_RUN_SCHEDULE_TIME_IN_MINUTE=00
###########################ALERT_ADMIN##########################
ALERT_EMAIL_SCHEDULE_TO_RUN=NO
ALERT_EMAIL_SCHEDULE_TIMEGAP_IN_MINUTES=2
ALERT_EMAIL_SCHEDULE_HOURLY_OR_DAILY_OR_MINUTE=MINUTE
ALERT_EMAIL_SCHEDULE_TIME_IN_HOUR=10
ALERT_EMAIL_SCHEDULE_TIME_IN_MINUTE=4
ALERT_EMAIL_USER_NAME=PAA
#####################PHCR_IMPORTER_PROCESS########################
PHCR_IMPORTER_SCHEDULE_TO_RUN=NO
PHCR_IMPORTER_SCHEDULE_TIMEGAP_IN_MINUTES=2
PHCR_IMPORTER_USER_NAME=PKS
PHCR_IMPORTER_SCHEDULE_HOURLY_OR_DAILY_OR_MINUTE=DAILY
PHCR_IMPORTER_SCHEDULE_TIME_IN_HOUR=11
PHCR_IMPORTER_SCHEDULE_TIME_IN_MINUTE=30
