PROC SQL;

CREATE TABLE 
	PLACE_INIT 
AS SELECT 
	ACT_UID,
	ANSWER_TXT , question_identifier
FROM 
	NBS_ODS.NBS_CASE_ANSWER 
INNER JOIN 	NBS_ODS.NBS_QUESTION 
ON 
NBS_QUESTION.NBS_QUESTION_UID =NBS_CASE_ANSWER.NBS_QUESTION_UID 
WHERE 
	question_identifier 
IN  ('NBS243','NBS290');
QUIT;
DATA PLACE_INIT;
  SET PLACE_INIT;
  LENGTH TYPE_OF_PLACE $200;
  	PLACE=SCAN(ANSWER_TXT,1,'^');
  	POSTAL=SCAN(ANSWER_TXT,2,'^');
  	TELE=SCAN(ANSWER_TXT,3,'^');
  	PLACE_UID= input(PLACE,12.); 
  	POSTAL_UID= input(POSTAL,12.); 
  	TELE_UID= input(TELE,12.); 
  	if(question_identifier='NBS243') then TYPE_OF_PLACE='Meeting Place';
	if(question_identifier='NBS290') then TYPE_OF_PLACE='Place to have Sex';


  DROP PLACE
  	   POSTAL
	   TELE;
RUN;
PROC SQL;
CREATE TABLE
	INV_PLACE_DATAMART_INIT
AS SELECT 
	PLACE_INIT.*,
	PLACE_STREET_ADDRESS_1, PLACE_STREET_ADDRESS_2, PLACE_CITY, PLACE_STATE_CODE,PLACE_STATE, Place_zip, 
	INVESTIGATION.INVESTIGATION_KEY,
	D_PLACE.PLACE_KEY AS PLACE_FLOAT_KEY 'PLACE_FLOAT_KEY', 
	D_PLACE.NAME as PLACE_NAME 'PLACE_NAME',
	D_PLACE_POSTAL.PLACE_POSTAL_KEY,
	D_PLACE_TELE.PLACE_TELE_KEY
FROM
	PLACE_INIT
INNER JOIN
	NBS_RDB.INVESTIGATION
ON
	PLACE_INIT.ACT_UID=INVESTIGATION.CASE_UID
INNER JOIN
	NBS_RDB.D_PLACE
ON
	PLACE_INIT.PLACE_UID=D_PLACE.PLACE_UID
LEFT OUTER JOIN
	NBS_RDB.D_PLACE_POSTAL
ON
	PLACE_INIT.POSTAL_UID=D_PLACE_POSTAL.POSTAL_UID
LEFT OUTER JOIN
	NBS_RDB.D_PLACE_TELE
ON
	PLACE_INIT.TELE_UID=D_PLACE_TELE.TELE_LOCATOR_UID;
quit;
data INV_PLACE_DATAMART_INIT;
set INV_PLACE_DATAMART_INIT;
length PLACE_ADDRESS $4000;
length PLACE_ZIPSTR $10;
PLACE_ZIPSTR = Place_zip;
format PLACE_KEY 20.;
*IF LENGTHN(TRIM(PATIENT_STREET_ADDRESS_2))>0 THEN PATIENT_ADDRESS=TRIM(PATIENT_ADDRESS) ||',' ||TRIM(PATIENT_STREET_ADDRESS_2);
PLACE_KEY=input(put(PLACE_FLOAT_KEY, 14.), 20.);
if LENGTHN(TRIM(PLACE_STREET_ADDRESS_1))>0 then PLACE_ADDRESS  =TRIM(PLACE_STREET_ADDRESS_1);
if LENGTHN(TRIM(PLACE_STREET_ADDRESS_2))>0 then PLACE_ADDRESS  =TRIM(PLACE_ADDRESS)  ||',' || TRIM(PLACE_STREET_ADDRESS_2);
if LENGTHN(TRIM(PLACE_CITY))>0 then PLACE_ADDRESS  =TRIM(PLACE_ADDRESS)  ||',' || TRIM(PLACE_CITY);
if LENGTHN(TRIM(PLACE_STATE))>0 then PLACE_ADDRESS  =TRIM(PLACE_ADDRESS)  ||',' || TRIM(PLACE_STATE);
if LENGTHN(TRIM(PLACE_ZIPSTR))>0  then PLACE_ADDRESS  =TRIM(PLACE_ADDRESS)  ||',' || TRIM(PLACE_ZIP);
DROP PLACE_STREET_ADDRESS_1 PLACE_STREET_ADDRESS_2 PLACE_CITY PLACE_STATE_CODE PLACE_STATE Place_zip;
run;
proc sql;
DROP TABLE NBS_RDB.INV_PLACE_REPEAT_DATAMART;
CREATE TABLE NBS_RDB.INV_PLACE_REPEAT_DATAMART AS SELECT
INV_PLACE_DATAMART_INIT.*, D_PLACE.*FROM INV_PLACE_DATAMART_INIT
INNER JOIN NBS_RDB.D_PLACE
on D_PLACE.PLACE_KEY =INV_PLACE_DATAMART_INIT.PLACE_KEY;

QUIT;
