PROC SQL;
DROP TABLE NBS_RDB.LDF_VACCINE_PREVENT_DISEASES;

CREATE TABLE BASE_VACCINE_PREVENT_DISEASES AS 
SELECT * FROM LDF_DIMENSIONAL_DATA WHERE  PHC_CD IN(SELECT CONDITION_CD FROM 
		NBS_RDB.LDF_DATAMART_TABLE_REF WHERE DATAMART_NAME = 'LDF_VACCINE_PREVENT_DISEASES');

CREATE TABLE LINKED_VAC_PREVENT_MEASLES AS 
	SELECT GEN_LDF.*, 
		INV.INVESTIGATION_KEY, 
		INV.INV_LOCAL_ID AS INVESTIGATION_LOCAL_ID 'INVESTIGATION_LOCAL_ID', 
		INV.CASE_OID AS PROGRAM_JURISDICTION_OID 'PROGRAM_JURISDICTION_OID',
		GEN.PATIENT_KEY,
		PATIENT.PATIENT_LOCAL_ID AS PATIENT_LOCAL_ID 'PATIENT_LOCAL_ID',
		CONDITION.CONDITION_SHORT_NM AS DISEASE_NAME 'DISEASE_NAME',
		CONDITION.CONDITION_CD,
		GEN_LDF.PHC_CD 
	FROM
		BASE_VACCINE_PREVENT_DISEASES GEN_LDF
		INNER JOIN  NBS_RDB.INVESTIGATION INV
	ON  
		GEN_LDF.INVESTIGATION_UID=INV.CASE_UID 
	INNER JOIN NBS_RDB.MEASLES_CASE GEN
	ON 
		GEN.INVESTIGATION_KEY=INV.INVESTIGATION_KEY
	INNER JOIN NBS_RDB.CONDITION
	ON 
		CONDITION.CONDITION_KEY= GEN.CONDITION_KEY
	INNER JOIN NBS_RDB.D_PATIENT PATIENT 
	ON 
		PATIENT.PATIENT_KEY=GEN.PATIENT_KEY
	ORDER BY 
		PATIENT_KEY;

CREATE TABLE LINKED_VAC_PREVENT_PERTUSSIS AS 
	SELECT GEN_LDF.*, 
		INV.INVESTIGATION_KEY, 
		INV.INV_LOCAL_ID AS INVESTIGATION_LOCAL_ID 'INVESTIGATION_LOCAL_ID', 
		INV.CASE_OID AS PROGRAM_JURISDICTION_OID 'PROGRAM_JURISDICTION_OID',
		GEN.PATIENT_KEY,
		PATIENT.PATIENT_LOCAL_ID AS PATIENT_LOCAL_ID 'PATIENT_LOCAL_ID',
		CONDITION.CONDITION_SHORT_NM AS DISEASE_NAME 'DISEASE_NAME',
		CONDITION.CONDITION_CD,
		GEN_LDF.PHC_CD 
	FROM
		BASE_VACCINE_PREVENT_DISEASES GEN_LDF
		INNER JOIN  NBS_RDB.INVESTIGATION INV
	ON  
		GEN_LDF.INVESTIGATION_UID=INV.CASE_UID 
	INNER JOIN NBS_RDB.PERTUSSIS_CASE GEN
	ON 
		GEN.INVESTIGATION_KEY=INV.INVESTIGATION_KEY
	INNER JOIN NBS_RDB.CONDITION
	ON 
		CONDITION.CONDITION_KEY= GEN.CONDITION_KEY
	INNER JOIN NBS_RDB.D_PATIENT  PATIENT
	ON 
		PATIENT.PATIENT_KEY=GEN.PATIENT_KEY
	ORDER BY 
		PATIENT_KEY;

CREATE TABLE LINKED_VAC_PREVENT_RUBELLA AS 
	SELECT GEN_LDF.*, 
		INV.INVESTIGATION_KEY, 
		INV.INV_LOCAL_ID AS INVESTIGATION_LOCAL_ID 'INVESTIGATION_LOCAL_ID', 
		INV.CASE_OID AS PROGRAM_JURISDICTION_OID 'PROGRAM_JURISDICTION_OID',
		GEN.PATIENT_KEY,
		PATIENT.PATIENT_LOCAL_ID AS PATIENT_LOCAL_ID 'PATIENT_LOCAL_ID',
		CONDITION.CONDITION_SHORT_NM AS DISEASE_NAME 'DISEASE_NAME',
		CONDITION.CONDITION_CD,
		GEN_LDF.PHC_CD 
	FROM
		BASE_VACCINE_PREVENT_DISEASES GEN_LDF
		INNER JOIN  NBS_RDB.INVESTIGATION INV
	ON  
		GEN_LDF.INVESTIGATION_UID=INV.CASE_UID 
	INNER JOIN NBS_RDB.RUBELLA_CASE GEN
	ON 
		GEN.INVESTIGATION_KEY=INV.INVESTIGATION_KEY
	INNER JOIN NBS_RDB.CONDITION
	ON 
		CONDITION.CONDITION_KEY= GEN.CONDITION_KEY
	INNER JOIN NBS_RDB.D_PATIENT PATIENT
	ON 
		PATIENT.PATIENT_KEY=GEN.PATIENT_KEY
	ORDER BY 
		PATIENT_KEY;

CREATE TABLE LINKED_VAC_PREVENT_CRS AS 
	SELECT GEN_LDF.*, 
		INV.INVESTIGATION_KEY, 
		INV.INV_LOCAL_ID AS INVESTIGATION_LOCAL_ID 'INVESTIGATION_LOCAL_ID', 
		INV.CASE_OID AS PROGRAM_JURISDICTION_OID 'PROGRAM_JURISDICTION_OID',
		GEN.PATIENT_KEY,
		PATIENT.PATIENT_LOCAL_ID AS PATIENT_LOCAL_ID 'PATIENT_LOCAL_ID',
		CONDITION.CONDITION_SHORT_NM AS DISEASE_NAME 'DISEASE_NAME',
		CONDITION.CONDITION_CD,
		GEN_LDF.PHC_CD 
	FROM
		BASE_VACCINE_PREVENT_DISEASES GEN_LDF
		INNER JOIN  NBS_RDB.INVESTIGATION INV
	ON  
		GEN_LDF.INVESTIGATION_UID=INV.CASE_UID 
	INNER JOIN NBS_RDB.CRS_CASE GEN
	ON 
		GEN.INVESTIGATION_KEY=INV.INVESTIGATION_KEY
	INNER JOIN NBS_RDB.CONDITION
	ON 
		CONDITION.CONDITION_KEY= GEN.CONDITION_KEY
	INNER JOIN NBS_RDB.D_PATIENT PATIENT
	ON 
		PATIENT.PATIENT_KEY=GEN.PATIENT_KEY
	ORDER BY 
		PATIENT_KEY;

QUIT;
DATA ALL_VAC_PREVENT_MERGED ;
MERGE LINKED_VAC_PREVENT_MEASLES LINKED_VAC_PREVENT_CRS LINKED_VAC_PREVENT_PERTUSSIS LINKED_VAC_PREVENT_RUBELLA;
BY PATIENT_KEY;
RUN;
proc sql;
CREATE TABLE ALL_VAC_PREVENT_DIS AS 
	SELECT A.*, 
	B.DATAMART_COLUMN_NM AS DM 'DM'
	FROM 	NBS_RDB.LDF_DATAMART_COLUMN_REF  B 
	FULL OUTER JOIN ALL_VAC_PREVENT_MERGED A 
	ON A.LDF_UID= B.LDF_UID WHERE
	(B.LDF_PAGE_SET ='VPD'
	OR B.CONDITION_CD IN (SELECT CONDITION_CD FROM 
		NBS_RDB.LDF_DATAMART_TABLE_REF WHERE DATAMART_NAME = 'LDF_VACCINE_PREVENT_DISEASES') 
	)
	ORDER BY 
		INVESTIGATION_UID;
quit;
DATA ALL_VAC_PREVENT_DIS;
SET ALL_VAC_PREVENT_DIS;
	IF  LENGTH(COMPRESS(CONDITION_CD))>1 
		THEN DISEASE_CD= CONDITION_CD;
	ELSE DISEASE_CD= PHC_CD;
	IF  LENGTH(DISEASE_NM)<2 
		THEN DISEASE_NM= PAGE_SET;
	IF  LENGTH(DM)>2 
		THEN DATAMART_COLUMN_NM=DM;
RUN;
PROC SORT DATA=ALL_VAC_PREVENT_DIS NODUPKEY OUT=ALL_VAC_PREVENT_DIS; BY INVESTIGATION_KEY DATAMART_COLUMN_NM; RUN;
PROC SQL;
CREATE TABLE ALL_VAC_PREVENT_DIS_SHORT_COL AS
SELECT * FROM ALL_VAC_PREVENT_DIS WHERE data_type IN ('CV', 'ST');

CREATE TABLE ALL_VAC_PREVENT_DIS_TA AS
SELECT * FROM ALL_VAC_PREVENT_DIS WHERE data_type IN ('LIST_ST');

QUIT;
DATA ALL_VAC_PREVENT_DIS_TA;
SET ALL_VAC_PREVENT_DIS_TA;
LENGTH ANSWERCOL $2000;
ANSWERCOL=COL1;
DROP COL1;
RUN;
DATA ALL_VAC_PREVENT_DIS_SHORT_COL;
SET ALL_VAC_PREVENT_DIS_SHORT_COL;
LENGTH ANSWERCOL $200;
ANSWERCOL=COL1;
DROP COL1;
RUN;
PROC TRANSPOSE DATA=  ALL_VAC_PREVENT_DIS_TA  OUT=  VAC_PREVENT_DIS_TA;
    BY   INVESTIGATION_KEY;
   	COPY INVESTIGATION_KEY INVESTIGATION_LOCAL_ID PROGRAM_JURISDICTION_OID PATIENT_KEY PATIENT_LOCAL_ID DISEASE_NAME DISEASE_CD;
    ID DATAMART_COLUMN_NM;
	VAR ANSWERCOL;
RUN;
PROC TRANSPOSE DATA=  ALL_VAC_PREVENT_DIS_SHORT_COL  OUT=  VAC_PREVENT_DIS_SHORT_COL;
    BY   INVESTIGATION_KEY;
   	COPY INVESTIGATION_KEY INVESTIGATION_LOCAL_ID PROGRAM_JURISDICTION_OID PATIENT_KEY PATIENT_LOCAL_ID DISEASE_NAME DISEASE_CD;
    ID DATAMART_COLUMN_NM;
	VAR ANSWERCOL;
RUN;
PROC SQL;
DELETE * FROM VAC_PREVENT_DIS_TA WHERE _NAME_ IS NULL;
DELETE * FROM VAC_PREVENT_DIS_SHORT_COL WHERE _NAME_ IS NULL;
QUIT;
DATA VACCINE_PREVENT_DISEASES;
   MERGE  VAC_PREVENT_DIS_SHORT_COL VAC_PREVENT_DIS_TA;
   BY   INVESTIGATION_KEY;
RUN;
DATA VACCINE_PREVENT_DISEASES;
SET VACCINE_PREVENT_DISEASES;
DROP _NAME_;
RUN;
PROC SQL;
DELETE * FROM VACCINE_PREVENT_DISEASES WHERE INVESTIGATION_KEY IS NULL;
QUIT;
PROC SQL;
CREATE TABLE  NBS_RDB.LDF_VACCINE_PREVENT_DISEASES AS SELECT * FROM VACCINE_PREVENT_DISEASES;
QUIT;
PROC DATASETS LIBRARY = WORK NOLIST;
DELETE 
BASE_VACCINE_PREVENT_DISEASES
LINKED_VACCINE_PREVENT_DISEASES
ALL_VAC_PREVENT_DIS
VACCINE_PREVENT_DISEASES;
RUN;
QUIT;
