%PROCESS_STAGING_DATA
	(S_INV_ADMINISTRATIVE, 'D_INV_ADMINISTRATIVE');
%PROCESS_STAGING_DATA
	(S_INV_CLINICAL,'D_INV_CLINICAL');
%PROCESS_STAGING_DATA
	(S_INV_COMPLICATION,'D_INV_COMPLICATION');
%PROCESS_STAGING_DATA
	(S_INV_CONTACT,'D_INV_CONTACT');
%PROCESS_STAGING_DATA
	(S_INV_DEATH,'D_INV_DEATH');
%PROCESS_STAGING_DATA
	(S_INV_EPIDEMIOLOGY,'D_INV_EPIDEMIOLOGY');
%PROCESS_STAGING_DATA
	(S_INV_HIV,'D_INV_HIV');
proc sql; 
	CREATE TABLE 
		S_EHARDS_DATA as 
	select 
		ehars_id as HIV_STATE_CASE_ID 'HIV_STATE_CASE_ID', 
		act_uid as PAGE_CASE_UID 'PAGE_CASE_UID',
		person.last_chg_time
	from 
		nbs_ods.person inner join nbs_ods.nbs_act_entity 
	on
		person.person_uid=nbs_act_entity.entity_uid
	where 
		HIV_STATE_CASE_ID is not null 
	and 
		type_cd='SubjOfPHC' 
	order by 
		PAGE_CASE_UID;
quit;
DATA S_INV_HIV;
MERGE  nbs_rdb.S_INV_HIV(IN=in1) S_EHARDS_DATA(IN=in2);
BY PAGE_CASE_UID;
RUN;
PROC SQL;
DROP TABLE NBS_RDB.S_INV_HIV;
QUIT;
%DBLOAD (S_INV_HIV, S_INV_HIV); 
	
%PROCESS_STAGING_DATA
	(S_INV_PATIENT_OBS,'D_INV_PATIENT_OBS');
%PROCESS_STAGING_DATA
	(S_INV_ISOLATE_TRACKING,'D_INV_ISOLATE_TRACKING');
%PROCESS_STAGING_DATA
	(S_INV_LAB_FINDING,'D_INV_LAB_FINDING');
%PROCESS_STAGING_DATA
	(S_INV_MEDICAL_HISTORY,'D_INV_MEDICAL_HISTORY');
%PROCESS_STAGING_DATA
	(S_INV_MOTHER,'D_INV_MOTHER');
%PROCESS_STAGING_DATA
	(S_INV_OTHER,'D_INV_OTHER');
%PROCESS_STAGING_DATA
	(S_INV_PREGNANCY_BIRTH,'D_INV_PREGNANCY_BIRTH');
%PROCESS_STAGING_DATA
	(S_INV_RESIDENCY,'D_INV_RESIDENCY');
%PROCESS_STAGING_DATA
	(S_INV_RISK_FACTOR,'D_INV_RISK_FACTOR');
%PROCESS_STAGING_DATA
	(S_INV_SOCIAL_HISTORY,'D_INV_SOCIAL_HISTORY');
%PROCESS_STAGING_DATA
	(S_INV_SYMPTOM,'D_INV_SYMPTOM');
%PROCESS_STAGING_DATA
	(S_INV_TREATMENT,'D_INV_TREATMENT');
%PROCESS_STAGING_DATA
	(S_INV_TRAVEL,'D_INV_TRAVEL');
%PROCESS_STAGING_DATA
	(S_INV_UNDER_CONDITION,'D_INV_UNDER_CONDITION');
%PROCESS_STAGING_DATA
	(S_INV_VACCINATION,'D_INV_VACCINATION');
/*
commented out code after discussing with Christi: no dimension exists with this this value
	%PROCESS_STAGING_DATA
	(S_INV_STD,'D_INV_STD');
*/
