PROC SQL;
DROP TABLE NBS_RDB.F_S_INV_CASE;
CREATE TABLE 
	PAGE_CASE_ENTITY 
AS SELECT 
	* 
FROM 
	NBS_ODS.NBS_ACT_ENTITY 
WHERE 
	ACT_UID 
IN 
	(
		SELECT 
			PUBLIC_HEALTH_CASE_UID 
		FROM 
			NBS_ODS.PUBLIC_HEALTH_CASE 
		WHERE 
			PUBLIC_HEALTH_CASE_UID 
		IN 
			(
				SELECT 
					PAGE_CASE_UID 
				FROM 
					PHC_CASE_UIDS
			)
	);  
/*WHERE CD IN (
SELECT  CONDITION_CD FROM NBS_SRT.CONDITION_CODE WHERE 
INVESTIGATION_FORM_CD NOT IN ( 'INV_FORM_BMDGAS','INV_FORM_BMDGBS','INV_FORM_BMDGEN','INV_FORM_BMDNM','INV_FORM_BMDSP',
	'INV_FORM_GEN','INV_FORM_HEPA','INV_FORM_HEPBV','INV_FORM_HEPCV','INV_FORM_HEPGEN','INV_FORM_MEA','INV_FORM_PER',
	'INV_FORM_RUB','INV_FORM_RVCT','INV_FORM_VAR')
)) order by act_uid;*/
QUIT;
PROC SORT DATA=PAGE_CASE_ENTITY; BY ACT_UID; RUN;


PROC TRANSPOSE DATA=PAGE_CASE_ENTITY OUT=PAGE_CASE_ENTITY;
    BY ACT_UID;
	COPY LAST_CHG_TIME ADD_TIME;
	ID TYPE_CD;
	VAR ENTITY_UID;
RUN;
DATA F_S_INV_CASE;
SET PAGE_CASE_ENTITY;
if InvestgrOfPHC ~=. then INVESTIGATOR_uid=InvestgrOfPHC;
if OrgAsReporterOfPHC ~=. then ORG_AS_REPORTER_UID=OrgAsReporterOfPHC;
if HospOfADT ~=. then HOSPITAL_UID=HospOfADT;
if PerAsReporterOfPHC ~=. then PERSON_AS_REPORTER_UID=PerAsReporterOfPHC;
if SubjOfPHC ~=. then patient_uid=SubjOfPHC;
if PhysicianOfPHC~=. then PHYSICIAN_UID=PhysicianOfPHC;
if ACT_UID ~=. then page_case_uid=ACT_UID;
if SubjOfPHC>0 then 
 do; 
  output F_S_INV_CASE;
 end;
 drop InvestgrOfPHC;
 drop OrgAsReporterOfPHC;
 drop HospOfADT;
 drop PerAsReporterOfPHC;
 drop SubjOfPHC;
 drop PhysicianOfPHC;
 drop act_uid;	
run;
DATA F_S_INV_CASE;
SET F_S_INV_CASE;
DROP _NAME_;
DROP _LABEL_;
RUN;
%DBLOAD (F_S_INV_CASE, F_S_INV_CASE);

