%PAGE_LOOKUP (L_INV_ADMINISTRATIVE, S_INV_ADMINISTRATIVE,S_INV_ADMINISTRATIVE.PAGE_CASE_UID,D_INV_ADMINISTRATIVE_KEY);

%PAGE_LOOKUP (L_INV_CLINICAL, S_INV_CLINICAL,S_INV_CLINICAL.PAGE_CASE_UID,D_INV_CLINICAL_KEY);

%PAGE_LOOKUP (L_INV_COMPLICATION, S_INV_COMPLICATION,S_INV_COMPLICATION.PAGE_CASE_UID,D_INV_COMPLICATION_KEY);

%PAGE_LOOKUP (L_INV_CONTACT, S_INV_CONTACT,S_INV_CONTACT.PAGE_CASE_UID,D_INV_CONTACT_KEY);

%PAGE_LOOKUP (L_INV_DEATH, S_INV_DEATH,S_INV_DEATH.PAGE_CASE_UID,D_INV_DEATH_KEY);

%PAGE_LOOKUP (L_INV_EPIDEMIOLOGY, S_INV_EPIDEMIOLOGY,S_INV_EPIDEMIOLOGY.PAGE_CASE_UID,D_INV_EPIDEMIOLOGY_KEY);

%PAGE_LOOKUP (L_INV_HIV, S_INV_HIV,S_INV_HIV.PAGE_CASE_UID,D_INV_HIV_KEY);

%PAGE_LOOKUP (L_INV_PATIENT_OBS, S_INV_PATIENT_OBS,S_INV_PATIENT_OBS.PAGE_CASE_UID,D_INV_PATIENT_OBS_KEY);

%PAGE_LOOKUP (L_INV_ISOLATE_TRACKING, S_INV_ISOLATE_TRACKING,S_INV_ISOLATE_TRACKING.PAGE_CASE_UID,D_INV_ISOLATE_TRACKING_KEY);

%PAGE_LOOKUP (L_INV_LAB_FINDING, S_INV_LAB_FINDING,S_INV_LAB_FINDING.PAGE_CASE_UID,D_INV_LAB_FINDING_KEY);

%PAGE_LOOKUP (L_INV_MEDICAL_HISTORY, S_INV_MEDICAL_HISTORY,S_INV_MEDICAL_HISTORY.PAGE_CASE_UID,D_INV_MEDICAL_HISTORY_KEY);

%PAGE_LOOKUP (L_INV_MOTHER, S_INV_MOTHER,S_INV_MOTHER.PAGE_CASE_UID,D_INV_MOTHER_KEY);

%PAGE_LOOKUP (L_INV_OTHER, S_INV_OTHER,S_INV_OTHER.PAGE_CASE_UID,D_INV_OTHER_KEY);

%PAGE_LOOKUP (L_INV_PREGNANCY_BIRTH, S_INV_PREGNANCY_BIRTH,S_INV_PREGNANCY_BIRTH.PAGE_CASE_UID,D_INV_PREGNANCY_BIRTH_KEY);

%PAGE_LOOKUP (L_INV_RESIDENCY, S_INV_RESIDENCY,S_INV_RESIDENCY.PAGE_CASE_UID,D_INV_RESIDENCY_KEY);

%PAGE_LOOKUP (L_INV_RISK_FACTOR, S_INV_RISK_FACTOR,S_INV_RISK_FACTOR.PAGE_CASE_UID,D_INV_RISK_FACTOR_KEY);

%PAGE_LOOKUP (L_INV_SOCIAL_HISTORY, S_INV_SOCIAL_HISTORY,S_INV_SOCIAL_HISTORY.PAGE_CASE_UID,D_INV_SOCIAL_HISTORY_KEY);

%PAGE_LOOKUP (L_INV_SYMPTOM, S_INV_SYMPTOM,S_INV_SYMPTOM.PAGE_CASE_UID,D_INV_SYMPTOM_KEY);

%PAGE_LOOKUP (L_INV_TREATMENT, S_INV_TREATMENT,S_INV_TREATMENT.PAGE_CASE_UID,D_INV_TREATMENT_KEY);

%PAGE_LOOKUP (L_INV_TRAVEL, S_INV_TRAVEL,S_INV_TRAVEL.PAGE_CASE_UID,D_INV_TRAVEL_KEY);

%PAGE_LOOKUP (L_INV_UNDER_CONDITION, S_INV_UNDER_CONDITION,S_INV_UNDER_CONDITION.PAGE_CASE_UID,D_INV_UNDER_CONDITION_KEY);

%PAGE_LOOKUP (L_INV_VACCINATION, S_INV_VACCINATION,S_INV_VACCINATION.PAGE_CASE_UID,D_INV_VACCINATION_KEY);
/*
commented out code after discussing with Christi: no dimension exists with this this value

%PAGE_LOOKUP (L_INV_STD, S_INV_STD,S_INV_STD.PAGE_CASE_UID,D_INV_STD_KEY);
*/
