 
PROC SQL;
CREATE TABLE 
	PHC_UIDS AS  
SELECT 	
	PUBLIC_HEALTH_CASE_UID LENGTH =8 AS PAGE_CASE_UID 'PAGE_CASE_UID', 
	INVESTIGATION_FORM_CD, CD, LAST_CHG_TIME 
FROM 
	NBS_ODS.PUBLIC_HEALTH_CASE, NBS_SRT.CONDITION_CODE
WHERE 
	CONDITION_CODE.CONDITION_CD= PUBLIC_HEALTH_CASE.CD
AND 
	INVESTIGATION_FORM_CD 
NOT IN 
	('INV_FORM_BMDGAS','INV_FORM_BMDGBS','INV_FORM_BMDGEN','INV_FORM_BMDNM','INV_FORM_BMDSP','INV_FORM_GEN','INV_FORM_HEPA','INV_FORM_HEPBV','INV_FORM_HEPCV','INV_FORM_HEPGEN','INV_FORM_MEA','INV_FORM_PER','INV_FORM_RUB','INV_FORM_RVCT','INV_FORM_VAR');
QUIT;
PROC SQL;
CREATE TABLE
	TEXT_METADATA AS
SELECT DISTINCT NUIM.QUESTION_GROUP_SEQ_NBR, NUIM.NBS_QUESTION_UID, NUIM.CODE_SET_GROUP_ID,  
	RDB_COLUMN_NM,NUIM.INVESTIGATION_FORM_CD, NUIM.BLOCK_NM,
	NUIM.QUESTION_GROUP_SEQ_NBR
FROM  
	NBS_ODS.NBS_RDB_METADATA NRDBM 
 INNER JOIN 
	NBS_ODS.NBS_UI_METADATA NUIM
ON 
	NUIM.NBS_UI_METADATA_UID=NRDBM.NBS_UI_METADATA_UID
	INNER JOIN NBS_SRT.CODE_VALUE_GENERAL CVG 
ON 
	UPCASE(CVG.CODE)=UPCASE(NUIM.DATA_TYPE) 
WHERE 		CVG.CODE_SET_NM = 'NBS_DATA_TYPE' AND CODE = 'TEXT' AND QUESTION_GROUP_SEQ_NBR IS NOT NULL
ORDER BY 	NBS_QUESTION_UID;
DATA TEXT_METADATA;
SET TEXT_METADATA;
RDB_COLUMN_NM = COMPRESS(RDB_COLUMN_NM);
RUN;
PROC SQL;
create index NBS_QUESTION_UID on TEXT_METADATA(NBS_QUESTION_UID);
quit;
PROC SQL;
CREATE TABLE NBS_CASE_ANSWER AS SELECT NCA.*,INVESTIGATION_FORM_CD FROM  
	NBS_ODS.NBS_CASE_ANSWER NCA INNER JOIN PHC_UIDS ON
	PHC_UIDS.PAGE_CASE_UID = NCA.ACT_UID;
QUIT;
PROC SQL;
CREATE TABLE 
	TEXT_DATA AS
SELECT DISTINCT  NBS_CASE_ANSWER_UID, PA.ANSWER_GROUP_SEQ_NBR,TRANSLATE(ANSWER_TXT,' ' ,'0D0A'x)	'ANSWER_TXT' as ANSWER_TXT,
ACT_UID LENGTH =8 AS PAGE_CASE_UID 'PAGE_CASE_UID',
	PA.RECORD_STATUS_CD, A.*	
FROM  
	TEXT_METADATA A LEFT OUTER JOIN 
	NBS_CASE_ANSWER PA 
ON 
	A.NBS_QUESTION_UID =PA.NBS_QUESTION_UID 
	AND A.INVESTIGATION_FORM_CD=PA.INVESTIGATION_FORM_CD
	AND ANSWER_GROUP_SEQ_NBR IS NOT NULL
ORDER BY 	ACT_UID;
QUIT;
/*PROC SORT DATA=TEXT_DATA NODUPKEY OUT=TEXT_DATA; BY PAGE_CASE_UID,NBS_QUESTION_UID, ANSWER_GROUP_SEQ_NBR ; RUN;*/
PROC SORT  DATA= TEXT_DATA; BY INVESTIGATION_FORM_CD PAGE_CASE_UID BLOCK_NM ANSWER_GROUP_SEQ_NBR; RUN;
PROC TRANSPOSE 
	DATA=TEXT_DATA OUT=TEXT_DATA_PIVOT;
	BY INVESTIGATION_FORM_CD PAGE_CASE_UID BLOCK_NM ANSWER_GROUP_SEQ_NBR;
	ID 	RDB_COLUMN_NM; 	VAR	ANSWER_TXT;
	COPY NBS_CASE_ANSWER_UID;
RUN; 
PROC SQL;
CREATE TABLE TEXT_DATA_OUT 
	AS SELECT * FROM TEXT_DATA_PIVOT 
	WHERE LENGTHN(_NAME_)>0 AND PAGE_CASE_UID>0;
QUIT;
PROC SQL;
CREATE TABLE 
	CODED_METADATA AS
SELECT DISTINCT NUIM.QUESTION_GROUP_SEQ_NBR, NUIM.NBS_QUESTION_UID, NUIM.CODE_SET_GROUP_ID,  
	UPCASE(NRDBM.RDB_COLUMN_NM) AS RDB_COLUMN_NM,
	NUIM.QUESTION_GROUP_SEQ_NBR, NUIM.INVESTIGATION_FORM_CD, NUIM.BLOCK_NM, NUIM.OTHER_VALUE_IND_CD
FROM  
	NBS_ODS.NBS_RDB_METADATA NRDBM 
 INNER JOIN 
	NBS_ODS.NBS_UI_METADATA NUIM
ON 
	NUIM.NBS_UI_METADATA_UID=NRDBM.NBS_UI_METADATA_UID
	INNER JOIN NBS_SRT.CODE_VALUE_GENERAL CVG 
ON 
	CVG.CODE=NUIM.DATA_TYPE 
WHERE 		CVG.CODE_SET_NM = 'NBS_DATA_TYPE' AND CODE = 'CODED' AND QUESTION_GROUP_SEQ_NBR IS NOT NULL
ORDER BY 	NUIM.CODE_SET_GROUP_ID;
QUIT;
DATA CODED_METADATA;
SET CODED_METADATA;
RDB_COLUMN_NM = COMPRESS(RDB_COLUMN_NM);
RUN;

PROC SQL;
CREATE TABLE 
	CODED_TABLE AS
SELECT  DISTINCT NBS_CASE_ANSWER_UID, PA.ANSWER_GROUP_SEQ_NBR,ANSWER_TXT, ACT_UID LENGTH =8 AS PAGE_CASE_UID 'PAGE_CASE_UID',
	PA.RECORD_STATUS_CD, A.*	
FROM  
	CODED_METADATA A 
LEFT JOIN 
	NBS_CASE_ANSWER PA 
ON 
	A.NBS_QUESTION_UID =PA.NBS_QUESTION_UID 
	AND A.INVESTIGATION_FORM_CD=PA.INVESTIGATION_FORM_CD
/*LEFT join 
phc_uids 
on
	phc_uids.page_case_uid =PA.act_uid
AND phc_uids.investigation_form_cd=a.investigation_form_cd*/

AND ANSWER_GROUP_SEQ_NBR IS NOT NULL
ORDER BY 	ACT_UID;

QUIT;
/*PROC SORT DATA=CODED_TABLE NODUPKEY OUT=CODED_DATA; BY NBS_CASE_ANSWER_UID; RUN;*/
PROC SORT  DATA= CODED_TABLE; BY INVESTIGATION_FORM_CD PAGE_CASE_UID BLOCK_NM ANSWER_GROUP_SEQ_NBR; RUN;

DATA CODED_TABLE;
SET CODED_TABLE;
LENGTH RDB_COLUMN_NM3 $22;
LENGTH RDB_COLUMN_NM2 $30;
	
	X = INDEX(ANSWER_TXT, '^');
	LENGTH=LENGTHN(ANSWER_TXT);
	IF X> 0 THEN ANSWER_OTH=SUBSTR(ANSWER_TXT, (5), LENGTH);
	IF X> 0 THEN ANSWER_TXT=SUBSTR(ANSWER_TXT, 1, (X-1));
	IF OTHER_VALUE_IND_CD='T' THEN RDB_COLUMN_NM3= RDB_COLUMN_NM;
	IF OTHER_VALUE_IND_CD='T' THEN RDB_COLUMN_NM2= TRIM(RDB_COLUMN_NM3) || '_OTH';
	IF UPCASE (ANSWER_TXT)='OTH' THEN ANSWER_TXT='OTH';
	RDB_COLUMN_NM2 =RDB_COLUMN_NM3;
	DROP RDB_COLUMN_NM3;
RUN;
PROC SQL;
CREATE TABLE 
	CODED_TABLE AS 
SELECT DISTINCT 
	ANSWER_GROUP_SEQ_NBR, CODED.CODE_SET_GROUP_ID, PAGE_CASE_UID, NBS_QUESTION_UID, 
	NBS_CASE_ANSWER_UID, ANSWER_TXT, CVG.CODE_SET_NM, RDB_COLUMN_NM, ANSWER_OTH, RDB_COLUMN_NM2,
	CODE,CODE_SHORT_DESC_TXT AS ANSWER_TXT1 'ANSWER_TXT1', INVESTIGATION_FORM_CD, BLOCK_NM,OTHER_VALUE_IND_CD
FROM 
	CODED_TABLE CODED
	LEFT JOIN NBS_SRT.CODESET_GROUP_METADATA METADATA
ON  
	METADATA.CODE_SET_GROUP_ID=CODED.CODE_SET_GROUP_ID
	LEFT JOIN NBS_SRT.CODE_VALUE_GENERAL CVG
ON 	
	CVG.CODE_SET_NM=METADATA.CODE_SET_NM
AND	
	CVG.CODE=CODED.ANSWER_TXT;
QUIT;
PROC SORT DATA=CODED_TABLE; BY PAGE_CASE_UID ANSWER_GROUP_SEQ_NBR NBS_QUESTION_UID; RUN;

DATA CODED_TABLE_DESC;
SET CODED_TABLE;
	BY PAGE_CASE_UID ANSWER_GROUP_SEQ_NBR NBS_QUESTION_UID;
	FORMAT ANSWER_DESC1-ANSWER_DESC10 $40. ANSWER_DESC11 $4000.;
	ARRAY ANSWER_DESC(10) ANSWER_DESC1-ANSWER_DESC10;
	RETAIN ANSWER_DESC1-ANSWER_DESC11 ' ' I 0;
	IF  FIRST.NBS_QUESTION_UID THEN DO;
		DO J=1 TO 10; ANSWER_DESC(J) = ' ';	END;
		I = 0; ANSWER_DESC11 = ''; 
		END;
	I+1;
	IF I <= 10 THEN DO;
		ANSWER_DESC(I) = ANSWER_TXT1;
		ANSWER_DESC11 =LEFT(TRIM(ANSWER_TXT1))||' | '|| LEFT(TRIM(ANSWER_DESC11)) ;
	END;
	IF LAST.NBS_QUESTION_UID  THEN OUTPUT;
RUN;

DATA CODED_TABLE_DESC;
SET CODED_TABLE_DESC;
 	A=LENGTHN(ANSWER_TXT);
 	IF TRIM(ANSWER_DESC11)=' |' THEN ANSWER_DESC11='';
 	LENGTH=LENGTHN(ANSWER_DESC11);
 	IF LENGTH> 0 THEN ANSWER_DESC11=TRIM(SUBSTR(ANSWER_DESC11, 1, (LENGTH-1)));
RUN;

PROC SQL;
CREATE TABLE 
	CODED_COUNTY_TABLE AS 
SELECT 
	ANSWER_GROUP_SEQ_NBR, CODED.CODE_SET_GROUP_ID, PAGE_CASE_UID, NBS_QUESTION_UID, 
	NBS_CASE_ANSWER_UID, ANSWER_TXT, CVG.CODE_SET_NM, RDB_COLUMN_NM, ANSWER_OTH, RDB_COLUMN_NM2,
	CVG.CODE,CODE_SHORT_DESC_TXT AS ANSWER_TXT1 'ANSWER_TXT1', INVESTIGATION_FORM_CD, BLOCK_NM
FROM 
	CODED_TABLE CODED
	LEFT JOIN NBS_SRT.CODESET_GROUP_METADATA METADATA
ON  
	METADATA.CODE_SET_GROUP_ID=CODED.CODE_SET_GROUP_ID
	LEFT JOIN NBS_SRT.V_STATE_COUNTY_CODE_VALUE CVG
ON 	
	CVG.CODE_SET_NM=METADATA.CODE_SET_NM
AND	
	CVG.CODE=CODED.ANSWER_TXT
WHERE METADATA.CODE_SET_NM= 'COUNTY_CCD';
QUIT;
PROC SORT DATA=CODED_COUNTY_TABLE; BY PAGE_CASE_UID ANSWER_GROUP_SEQ_NBR NBS_QUESTION_UID; RUN;
DATA CODED_COUNTY_TABLE_DESC;
SET CODED_COUNTY_TABLE;
	BY PAGE_CASE_UID ANSWER_GROUP_SEQ_NBR NBS_QUESTION_UID;
	FORMAT ANSWER_DESC1-ANSWER_DESC10 $40. ANSWER_DESC11 $4000.;
	ARRAY ANSWER_DESC(10) ANSWER_DESC1-ANSWER_DESC10;
	RETAIN ANSWER_DESC1-ANSWER_DESC11 ' ' I 0;
	IF  FIRST.NBS_QUESTION_UID THEN DO;
		DO J=1 TO 10; ANSWER_DESC(J) = ' ';	END;
		I = 0; ANSWER_DESC11 = ''; 
		END;
	I+1;
	IF I <= 10 THEN DO;
		ANSWER_DESC(I) = ANSWER_TXT1;
		ANSWER_DESC11 =LEFT(TRIM(ANSWER_TXT1))||' | '|| LEFT(TRIM(ANSWER_DESC11)) ;
	END;
	IF LAST.NBS_QUESTION_UID  THEN OUTPUT;
RUN;

DATA CODED_COUNTY_TABLE_DESC;
SET CODED_COUNTY_TABLE_DESC;
 	A=LENGTHN(ANSWER_TXT);
 	IF TRIM(ANSWER_DESC11)=' |' THEN ANSWER_DESC11='';
 	LENGTH=LENGTHN(ANSWER_DESC11);
 	IF LENGTH> 0 THEN ANSWER_DESC11=TRIM(SUBSTR(ANSWER_DESC11, 1, (LENGTH-1)));
RUN;
PROC SQL;
CREATE TABLE CODED_TABLE_OTH AS SELECT * FROM CODED_TABLE WHERE OTHER_VALUE_IND_CD='T';
QUIT;
PROC SQL;
UPDATE CODED_TABLE_OTH SET ANSWER_TXT  = MISSING , PAGE_CASE_UID=MISSING, NBS_CASE_ANSWER_UID=MISSING WHERE ANSWER_TXT not eq 'OTH';
QUIT;

DATA CODED_TABLE_OTH;
SET CODED_TABLE_OTH;
	/*IF LENGTHN(TRIM(RDB_COLUMN_NM2))>0;
 	IF(LENGTHN(RDB_COLUMN_NM2)>0) 
   		THEN RDB_COLUMN_NM=RDB_COLUMN_NM2;
	IF OTHER_VALUE_IND_CD='T' THEN RDB_COLUMN_NM= TRIM(RDB_COLUMN_NM) || '_OTH';*/
	RDB_COLUMN_NM = TRIM(RDB_COLUMN_NM2) || '_OTH';
	IF UPCASE (ANSWER_TXT)='OTH' THEN ANSWER_TXT='OTH';
	IF(LENGTHN(TRIM(RDB_COLUMN_NM2))>0) THEN ANSWER_DESC11=ANSWER_OTH;
RUN;
proc sql;
create table rdb_ui_metadata as 
select distinct NUIM.NBS_QUESTION_UID, NUIM.CODE_SET_GROUP_ID,NUIM.investigation_form_cd, NRDBM.RDB_COLUMN_NM, NUIM.unit_value,
NUIM.INVESTIGATION_FORM_CD,NUIM.BLOCK_NM,
CODE_SET_GROUP_ID,QUESTION_GROUP_SEQ_NBR,DATA_TYPE, UNIT_VALUE, UNIT_TYPE_CD
FROM
NBS_ODS.NBS_RDB_METADATA NRDBM,
NBS_ODS.NBS_UI_METADATA NUIM
where NRDBM.NBS_UI_METADATA_UID=NUIM.NBS_UI_METADATA_UID
AND QUESTION_GROUP_SEQ_NBR IS NOT NULL
AND  (upcase(DATA_TYPE)='NUMERIC' and upcase(unit_type_cd)='CODED')
;
quit;

data rdb_ui_metadata;
set rdb_ui_metadata;
if CODE_SET_GROUP_ID=. then CODE_SET_GROUP_ID=unit_value;
RDB_COLUMN_NM= COMPRESS(RDB_COLUMN_NM);
run;

PROC SORT DATA=rdb_ui_metadata nodupkey; BY NBS_QUESTION_UID; RUN;
proc sql;
 CREATE TABLE CODED_TABLE_SNTEMP AS
 SELECT  NBS_CASE_ANSWER_UID, ANSWER_GROUP_SEQ_NBR,
rdb_ui_metadata.CODE_SET_GROUP_ID,  RDB_COLUMN_NM,
	ANSWER_TXT, ACT_UID LENGTH =8 AS PAGE_CASE_UID 'PAGE_CASE_UID',
	PA.RECORD_STATUS_CD, rdb_ui_metadata.NBS_QUESTION_UID, rdb_ui_metadata.INVESTIGATION_FORM_CD, 
	rdb_ui_metadata.BLOCK_NM, UNIT_TYPE_CD
 FROM  rdb_ui_metadata  left outer join 
NBS_ODS.NBS_CASE_ANSWER PA 
on
rdb_ui_metadata.nbs_question_uid=PA.nbs_question_uid

LEFT JOIN PHC_UIDS on
PHC_UIDS.PAGE_CASE_UID=PA.act_uid
INNER JOIN NBS_SRT.CODE_VALUE_GENERAL CVG 
 ON 	upcase(CVG.CODE)=upcase(rdb_ui_metadata.DATA_TYPE)
 WHERE CVG.CODE_SET_NM = 'NBS_DATA_TYPE' AND upcase(data_type) = 'NUMERIC'
AND QUESTION_GROUP_SEQ_NBR IS NOT NULL
/*AND phc_uids.investigation_form_cd=a.investigation_form_cd*/

ORDER BY 
	ACT_UID;
QUIT;

DATA CODED_TABLE_SNTEMP;
SET CODED_TABLE_SNTEMP;
	X = INDEX(ANSWER_TXT, '^');
	LENGTH=LENGTHN(ANSWER_TXT);
	IF X> 0 THEN ANSWER_TXT_CODE=SUBSTR(ANSWER_TXT, x+1, LENGTH);
	IF X> 0 THEN ANSWER_VALUE=INPUT(SUBSTR(ANSWER_TXT, 1, (X-1)),  comma20.);
	IF X= 0 THEN ANSWER_VALUE=ANSWER_TXT;
DROP ANSWER_TXT;
RUN;

PROC SQL;
CREATE TABLE 
	CODED_TABLE_SNTEMP_TRANS_A AS  SELECT CODED.CODE_SET_GROUP_ID, PAGE_CASE_UID, 
ANSWER_TXT_CODE , ANSWER_VALUE, NBS_CASE_ANSWER_UID,  CVG.CODE_SET_NM,  RDB_COLUMN_NM,
	 CVG.CODE,CODE_SHORT_DESC_TXT AS ANSWER_TXT2 'ANSWER_TXT2',INVESTIGATION_FORM_CD, BLOCK_NM, ANSWER_GROUP_SEQ_NBR,
	 UNIT_TYPE_CD
FROM CODED_TABLE_SNTEMP CODED 	LEFT JOIN NBS_SRT.CODESET_GROUP_METADATA METADATA
ON  METADATA.CODE_SET_GROUP_ID=CODED.CODE_SET_GROUP_ID
	LEFT JOIN NBS_SRT.CODE_VALUE_GENERAL CVG ON  CVG.CODE_SET_NM=METADATA.CODE_SET_NM
AND CVG.CODE=CODED.ANSWER_TXT_CODE
ORDER BY NBS_CASE_ANSWER_UID, RDB_COLUMN_NM;
QUIT;


DATA CODED_TABLE_SNTEMP_TRANS_A;
SET CODED_TABLE_SNTEMP_TRANS_A;
if length(UNIT_TYPE_CD)> 0 AND UPCASE(UNIT_TYPE_CD)= 'CODED' THEN ANSWER_DESC11=compress(ANSWER_VALUE);
/*if length(UNIT_TYPE_CODED)= 0 THEN ANSWER_DESC11=  compress(ANSWER_VALUE) ||' '||compress(ANSWER_TXT2);*/
DROP CODE_SET_GROUP_ID;
RUN;
DATA CODED_TABLE_SNTEMP_TRANS_CODE;
SET CODED_TABLE_SNTEMP_TRANS_A;
LENGTH RDB_COLUMN_NM3 $21;
LENGTH RDB_COLUMN_NM2 $30;
RDB_COLUMN_NM3 = RDB_COLUMN_NM;
if length(UNIT_TYPE_CD)> 0 AND UPCASE(UNIT_TYPE_CD)= 'CODED'  THEN RDB_COLUMN_NM2=compress(RDB_COLUMN_NM3|| '_UNIT');
if length(UNIT_TYPE_CD)> 0 AND UPCASE(UNIT_TYPE_CD)= 'CODED'  THEN ANSWER_DESC11=compress(ANSWER_TXT2);
if length(UNIT_TYPE_CD)> 0 AND UPCASE(UNIT_TYPE_CD)= 'CODED'  THEN RDB_COLUMN_NM = RDB_COLUMN_NM2;
DROP CODE_SET_GROUP_ID RDB_COLUMN_NM2 RDB_COLUMN_NM3;
RUN;

DATA CODED_TABLE_SNTEMP_TRANS;
  MERGE CODED_TABLE_SNTEMP_TRANS_A CODED_TABLE_SNTEMP_TRANS_CODE; 
  BY NBS_CASE_ANSWER_UID RDB_COLUMN_NM; 
RUN;
/*
DATA CODED_TABLE_SNTEMP_TRANS;
SET CODED_TABLE_SNTEMP_TRANS;
ANSWER_DESC11=  compress(ANSWER_VALUE) ||' '||compress(ANSWER_TXT2);
DROP CODE_SET_GROUP_ID;
RUN;*/
PROC SORT DATA=CODED_TABLE_SNTEMP_TRANS; BY NBS_CASE_ANSWER_UID RDB_COLUMN_NM; RUN;
PROC SORT DATA=CODED_COUNTY_TABLE_DESC; BY NBS_CASE_ANSWER_UID RDB_COLUMN_NM; RUN;
PROC SORT DATA=CODED_TABLE_DESC; BY NBS_CASE_ANSWER_UID RDB_COLUMN_NM; RUN;
PROC SORT DATA=CODED_TABLE_OTH NODUPKEY; BY NBS_CASE_ANSWER_UID RDB_COLUMN_NM; RUN;

DATA CODED_TABLE_MERGED ; 
  MERGE CODED_TABLE_DESC CODED_COUNTY_TABLE_DESC CODED_TABLE_OTH CODED_TABLE_SNTEMP_TRANS; 
  BY NBS_CASE_ANSWER_UID RDB_COLUMN_NM; 
RUN;
PROC SORT  DATA= CODED_TABLE_MERGED; BY INVESTIGATION_FORM_CD PAGE_CASE_UID BLOCK_NM ANSWER_GROUP_SEQ_NBR; RUN;
PROC TRANSPOSE 
	DATA=CODED_TABLE_MERGED OUT=CODED_DATA_PIVOT; BY INVESTIGATION_FORM_CD PAGE_CASE_UID BLOCK_NM ANSWER_GROUP_SEQ_NBR;
	ID 	RDB_COLUMN_NM; VAR ANSWER_DESC11;
	COPY NBS_CASE_ANSWER_UID;
RUN;
PROC SQL;
CREATE TABLE CODED_DATA_OUT 
	AS SELECT * FROM CODED_DATA_PIVOT 
	WHERE LENGTHN(_NAME_)>0 AND PAGE_CASE_UID>0;
QUIT;


PROC DATASETS LIBRARY = WORK NOLIST;
DELETE CODED_TABLE CODED_TABLE1 CODED_TABLE2 CODED_TABLE_DESC CODED_TABLE_OTH CODED_TABLE_MERGED TEXT_DATA_PIVOT
RUN;
QUIT; 

PROC SQL;
CREATE TABLE 
	DATE_METADATA AS
SELECT DISTINCT NUIM.QUESTION_GROUP_SEQ_NBR, NUIM.NBS_QUESTION_UID, NUIM.CODE_SET_GROUP_ID,  
	UPCASE(NRDBM.RDB_COLUMN_NM) AS RDB_COLUMN_NM, NUIM.INVESTIGATION_FORM_CD, NUIM.BLOCK_NM,
	NUIM.QUESTION_GROUP_SEQ_NBR
FROM  
	NBS_ODS.NBS_RDB_METADATA NRDBM 
 INNER JOIN 
	NBS_ODS.NBS_UI_METADATA NUIM
ON 
	NUIM.NBS_UI_METADATA_UID=NRDBM.NBS_UI_METADATA_UID
	INNER JOIN NBS_SRT.CODE_VALUE_GENERAL CVG 
ON 
	CVG.CODE=NUIM.DATA_TYPE 
WHERE 		CVG.CODE_SET_NM = 'NBS_DATA_TYPE' AND CODE IN( 'DATETIME','DATE') AND QUESTION_GROUP_SEQ_NBR IS NOT NULL
ORDER BY 	NBS_QUESTION_UID;
QUIT;
DATA DATE_METADATA;
SET DATE_METADATA;
RDB_COLUMN_NM = COMPRESS(RDB_COLUMN_NM);
RUN;
PROC SQL;
create index NBS_QUESTION_UID on DATE_METADATA(NBS_QUESTION_UID);
quit;
PROC SQL;
CREATE TABLE 
	DATE_DATA AS
SELECT DISTINCT  NBS_CASE_ANSWER_UID, PA.ANSWER_GROUP_SEQ_NBR,ANSWER_TXT, ACT_UID LENGTH =8 AS PAGE_CASE_UID 'PAGE_CASE_UID',
	PA.RECORD_STATUS_CD, A.*	
FROM  
	DATE_METADATA A 
LEFT OUTER JOIN 
	NBS_CASE_ANSWER PA 
ON 
	A.NBS_QUESTION_UID =PA.NBS_QUESTION_UID 
	and A.INVESTIGATION_FORM_CD = PA.INVESTIGATION_FORM_CD
WHERE QUESTION_GROUP_SEQ_NBR IS NOT NULL
ORDER BY 	ACT_UID;
QUIT;
PROC SORT DATA=DATE_DATA OUT=DATE_DATA; BY NBS_CASE_ANSWER_UID; RUN;


DATA DATE_DATA;
SET DATE_DATA;
	ANSWER_TXT1=input(ANSWER_TXT,anydtdtm20.);
	informat ANSWER_TXT1 LAST_CHG_TIME  dateTIME22.3 ;
	format ANSWER_TXT1 LAST_CHG_TIME dateTIME22.3;
RUN;

/*PROC SQL; 
DELETE FROM NBS_RDB.PAGE_DATE_TABLE;
QUIT;*/
DATA DATE_DATA; 
SET DATE_DATA;  
DROP _LABEL_; 
DROP _NAME_; 
RUN; 
PROC SORT DATA=DATE_DATA  OUT=DATE_DATA; BY PAGE_CASE_UID rdb_column_nm ANSWER_GROUP_SEQ_NBR; RUN;
PROC SQL;
CREATE TABLE DATE_DATA1 AS SELECT * FROM DATE_DATA;
QUIT;

%DBLOAD (PAGE_DATE_TABLE, DATE_DATA1); 
DATA PAGE_DATE_TABLE; SET NBS_RDB.PAGE_DATE_TABLE; RUN; 
PROC SORT  DATA=PAGE_DATE_TABLE; BY INVESTIGATION_FORM_CD PAGE_CASE_UID BLOCK_NM ANSWER_GROUP_SEQ_NBR; RUN;
PROC TRANSPOSE DATA=PAGE_DATE_TABLE OUT=DATE_DATA_PIVOT; 
	BY INVESTIGATION_FORM_CD PAGE_CASE_UID BLOCK_NM ANSWER_GROUP_SEQ_NBR; 
	ID 	RDB_COLUMN_NM; 
	VAR	ANSWER_TXT1;
	COPY NBS_CASE_ANSWER_UID;
RUN; 
DATA DATE_DATA_PIVOT;
SET DATE_DATA_PIVOT;
DROP RDB_COLUMN_NM;
RUN;
PROC SQL;
CREATE TABLE DATE_DATA_OUT 
	AS SELECT * FROM DATE_DATA_PIVOT 
	WHERE LENGTHN(_NAME_)>0 AND PAGE_CASE_UID>0;
QUIT;
PROC SQL;
DROP TABLE NBS_RDB.PAGE_DATE_TABLE;
QUIT;
PROC DATASETS LIBRARY = WORK NOLIST;
DELETE 
PAGE_DATE_TABLE
DATE_DATA
RUN;
QUIT;
PROC SQL;
CREATE TABLE 
	NUMERIC_METADATA AS
SELECT DISTINCT NUIM.QUESTION_GROUP_SEQ_NBR, NUIM.NBS_QUESTION_UID, NUIM.UNIT_VALUE as CODE_SET_GROUP_ID 'CODE_SET_GROUP_ID',  
	UPCASE(NRDBM.RDB_COLUMN_NM) AS RDB_COLUMN_NM, NUIM.INVESTIGATION_FORM_CD, NUIM.BLOCK_NM,
	NUIM.QUESTION_GROUP_SEQ_NBR
FROM  
	NBS_ODS.NBS_RDB_METADATA NRDBM 
 INNER JOIN 
	NBS_ODS.NBS_UI_METADATA NUIM
ON 
	NUIM.NBS_UI_METADATA_UID=NRDBM.NBS_UI_METADATA_UID
	INNER JOIN NBS_SRT.CODE_VALUE_GENERAL CVG 
ON 
	CVG.CODE=NUIM.DATA_TYPE 
WHERE 		CVG.CODE_SET_NM = 'NBS_DATA_TYPE' AND CODE = 'NUMERIC' AND (UNIT_TYPE_CD IS NULL OR UNIT_TYPE_CD='LITERAL')

/*OR  (upcase(DATA_TYPE)='NUMERIC' and  upcase(mask)='NUM' and UNIT_TYPE_CD='LITERAL'))*/

AND QUESTION_GROUP_SEQ_NBR IS NOT NULL
ORDER BY 	NUIM.CODE_SET_GROUP_ID;

QUIT;
DATA NUMERIC_METADATA;
SET NUMERIC_METADATA;
RDB_COLUMN_NM = COMPRESS(RDB_COLUMN_NM);
RUN;
PROC SQL;
create index NBS_QUESTION_UID on NUMERIC_METADATA(NBS_QUESTION_UID);
QUIT;
PROC SQL;
CREATE TABLE 
	NUMERIC_BASE_DATA AS
SELECT DISTINCT  NBS_CASE_ANSWER_UID, PA.ANSWER_GROUP_SEQ_NBR,ANSWER_TXT, ACT_UID LENGTH =8 AS PAGE_CASE_UID 'PAGE_CASE_UID',
	PA.RECORD_STATUS_CD, A.*	
FROM  
	NUMERIC_METADATA A LEFT OUTER JOIN 
	NBS_CASE_ANSWER PA 
ON 
	A.NBS_QUESTION_UID =PA.NBS_QUESTION_UID 
	AND A.INVESTIGATION_FORM_CD = PA.INVESTIGATION_FORM_CD
	AND ANSWER_GROUP_SEQ_NBR IS NOT NULL
	WHERE QUESTION_GROUP_SEQ_NBR IS NOT NULL
ORDER BY 	ACT_UID;
QUIT;
PROC SORT DATA=NUMERIC_BASE_DATA OUT=NUMERIC_BASE_DATA; BY NBS_CASE_ANSWER_UID; RUN;
DATA NUMERIC_DATA1;
SET NUMERIC_BASE_DATA;
	X = INDEX(ANSWER_TXT, '^');
	ANSWER_TXT1=ANSWER_TXT;
	LENGTH=LENGTHN(ANSWER_TXT1);
	IF X> 0 THEN ANSWER_UNIT=SUBSTR(ANSWER_TXT, 1, (X-1));
	IF X= 0 THEN ANSWER_UNIT=ANSWER_TXT;
	IF X> 0 THEN LENCODED=LENGTHN(ANSWER_UNIT);
	IF X> 0 THEN ANSWER_CODED=SUBSTR(ANSWER_TXT, (LENCODED+2), LENGTH);
	IF X> 0 THEN UNIT_VALUE1 = INPUT(CODE_SET_GROUP_ID, COMMA20.);
	Y=LENGTHN(ANSWER_CODED);
	IF(Y>0) THEN RDB_COLUMN_NM2= TRIM(RDB_COLUMN_NM) || ' UNIT';
RUN;
DATA NUMERIC_DATA2;
SET NUMERIC_DATA1;
LENGTH RDB_COLUMN_NM3 $22;
LENGTH RDB_COLUMN_NM2 $30;
	IF(LENGTHN(RDB_COLUMN_NM2)>0) THEN RDB_COLUMN_NM3=RDB_COLUMN_NM2;
	RDB_COLUMN_NM2 =RDB_COLUMN_NM3;
drop RDB_COLUMN_NM3;
RUN;
PROC SORT DATA=NUMERIC_DATA2; BY NBS_CASE_ANSWER_UID RDB_COLUMN_NM; RUN;
 PROC SORT DATA=NUMERIC_DATA1; BY NBS_CASE_ANSWER_UID RDB_COLUMN_NM; RUN;
DATA NUMERIC_DATA_MERGED ; 
  MERGE NUMERIC_DATA1 NUMERIC_DATA2; 
  BY NBS_CASE_ANSWER_UID RDB_COLUMN_NM; 
RUN; 
PROC SQL;
CREATE TABLE 
	NUMERIC_DATA_TRANS  AS 
SELECT 
	PAGE_CASE_UID, NBS_QUESTION_UID,  ANSWER_GROUP_SEQ_NBR,
	 NBS_CASE_ANSWER_UID, ANSWER_UNIT,ANSWER_CODED, CVG.CODE_SET_NM,RDB_COLUMN_NM,
	ANSWER_TXT,	CODE,CODE_SHORT_DESC_TXT AS UNIT 'UNIT', ANSWER_UNIT, INVESTIGATION_FORM_CD, BLOCK_NM
FROM 
	NUMERIC_DATA_MERGED CODED
	LEFT JOIN NBS_SRT.CODESET_GROUP_METADATA METADATA
ON 
	METADATA.CODE_SET_GROUP_ID=CODED.UNIT_VALUE1
	LEFT JOIN NBS_SRT.CODE_VALUE_GENERAL CVG
ON 
	CVG.CODE_SET_NM=METADATA.CODE_SET_NM
AND	 ANSWER_GROUP_SEQ_NBR IS NOT NULL
WHERE 
	CVG.CODE=CODED.ANSWER_CODED
	ORDER BY PAGE_CASE_UID;
QUIT;
DATA NUMERIC_DATA_TRANS;
SET NUMERIC_DATA_TRANS;
	X=INDEX(RDB_COLUMN_NM,' UNIT');
	IF TRIM(UNIT)=''  THEN ANSWER_TXT=ANSWER_TXT;
	ELSE IF X>0 THEN ANSWER_TXT=UNIT;
	ELSE ANSWER_TXT=ANSWER_UNIT;
RUN;
PROC SQL;
CREATE TABLE NUMERIC_DATA_TRANS1 AS 
SELECT DISTINCT 
	PAGE_CASE_UID,
	RDB_COLUMN_NM,
	ANSWER_UNIT,
	ANSWER_TXT,
	ANSWER_GROUP_SEQ_NBR,
	NBS_CASE_ANSWER_UID,
	INVESTIGATION_FORM_CD,
	BLOCK_NM,
	NBS_QUESTION_UID
FROM NUMERIC_DATA_TRANS;
QUIT;
PROC SORT  DATA= NUMERIC_DATA_TRANS1; BY INVESTIGATION_FORM_CD PAGE_CASE_UID BLOCK_NM ANSWER_GROUP_SEQ_NBR; RUN;
PROC TRANSPOSE 
	DATA=NUMERIC_DATA_TRANS1 OUT=NUMERIC_DATA_PIVOT;
	BY INVESTIGATION_FORM_CD PAGE_CASE_UID BLOCK_NM ANSWER_GROUP_SEQ_NBR;
	ID 	RDB_COLUMN_NM;
	VAR	ANSWER_TXT;
	COPY NBS_CASE_ANSWER_UID;
RUN;
PROC SQL;
CREATE TABLE NUMERIC_DATA_OUT 
	AS SELECT * FROM NUMERIC_DATA_PIVOT 
WHERE LENGTHN(_LABEL_)>0 AND PAGE_CASE_UID>0;
QUIT;
DATA NUMERIC_DATA_OUT;
SET NUMERIC_DATA_OUT;
DROP _LABEL_;
DROP _NAME_;
RUN;
proc sql;
create table Staging_key_metadata as 
select distinct NRDBM.RDB_COLUMN_NM,NUIM.NBS_QUESTION_UID, NUIM.CODE_SET_GROUP_ID,  
NUIM.INVESTIGATION_FORM_CD,data_type, NUIM.BLOCK_NM,
CODE_SET_GROUP_ID,QUESTION_GROUP_SEQ_NBR,DATA_TYPE
from
NBS_ODS.NBS_RDB_METADATA NRDBM,
NBS_ODS.NBS_UI_METADATA NUIM
where NRDBM.NBS_UI_METADATA_UID=NUIM.NBS_UI_METADATA_UID
AND QUESTION_GROUP_SEQ_NBR IS not NULL;

create table STAGING_KEY AS select
	ACT_UID LENGTH =8 AS PAGE_CASE_UID 'PAGE_CASE_UID',NBS_CASE_ANSWER_UID, PHC_UIDS.LAST_CHG_TIME
FROM  Staging_key_metadata NUIM
	INNER JOIN
	NBS_ODS.NBS_CASE_ANSWER PA 
ON	NUIM.NBS_QUESTION_UID =PA.NBS_QUESTION_UID
	INNER JOIN 
	PHC_UIDS 
ON	PHC_UIDS.PAGE_CASE_UID=PA.ACT_UID
WHERE 
ANSWER_GROUP_SEQ_NBR IS not NULL
ORDER BY 
	ACT_UID,NBS_CASE_ANSWER_UID, NUIM.CODE_SET_GROUP_ID;
quit;
PROC SORT DATA=STAGING_KEY NODUPKEY; BY PAGE_CASE_UID; RUN;
PROC SQL;
DROP TABLE NBS_RDB.S_INVESTIGATION_REPEAT;
QUIT;
PROC SORT DATA=NUMERIC_DATA_OUT; BY INVESTIGATION_FORM_CD PAGE_CASE_UID BLOCK_NM ANSWER_GROUP_SEQ_NBR; RUN;
PROC SORT DATA=DATE_DATA_OUT; BY INVESTIGATION_FORM_CD PAGE_CASE_UID BLOCK_NM ANSWER_GROUP_SEQ_NBR; RUN;
PROC SORT DATA=CODED_DATA_OUT; BY INVESTIGATION_FORM_CD PAGE_CASE_UID BLOCK_NM ANSWER_GROUP_SEQ_NBR; RUN;
PROC SORT DATA=TEXT_DATA_OUT; BY INVESTIGATION_FORM_CD PAGE_CASE_UID BLOCK_NM ANSWER_GROUP_SEQ_NBR; RUN;
DATA S_INVESTIGATION_REPEAT; 
MERGE 
	NUMERIC_DATA_OUT
	DATE_DATA_OUT
	CODED_DATA_OUT
	TEXT_DATA_OUT;
BY INVESTIGATION_FORM_CD PAGE_CASE_UID BLOCK_NM ANSWER_GROUP_SEQ_NBR;
RUN;
PROC SQL;
DROP TABLE NBS_RDB.S_INVESTIGATION_REPEAT;
QUIT;
DATA S_INVESTIGATION_REPEAT;
	SET S_INVESTIGATION_REPEAT(DROP=_NAME_ _LABEL_ );
RUN;
PROC SQL;
CREATE TABLE 
	NBS_RDB.S_INVESTIGATION_REPEAT AS 
SELECT * FROM S_INVESTIGATION_REPEAT;
QUIT;
PROC SQL;
DROP TABLE NBS_RDB.L_INVESTIGATION_REPEAT;
CREATE TABLE L_INVESTIGATION_REPEAT AS SELECT DISTINCT PAGE_CASE_UID FROM S_INVESTIGATION_REPEAT;
QUIT;
%ASSIGN_KEY (L_INVESTIGATION_REPEAT, D_INVESTIGATION_REPEAT_KEY);

%DBLOAD (L_INVESTIGATION_REPEAT, L_INVESTIGATION_REPEAT);


PROC SQL;
create index PAGE_CASE_UID on L_INVESTIGATION_REPEAT(PAGE_CASE_UID);
quit;

PROC SQL;
create index PAGE_CASE_UID on S_INVESTIGATION_REPEAT(PAGE_CASE_UID);
quit;

PROC SQL;
DROP TABLE NBS_RDB.D_INVESTIGATION_REPEAT;
QUIT;

PROC SQL;

CREATE TABLE NBS_RDB.D_INVESTIGATION_REPEAT(DROP=NBS_CASE_ANSWER_UID INVESTIGATION_FORM_CD) AS
SELECT A.*, B.D_INVESTIGATION_REPEAT_KEY FROM L_INVESTIGATION_REPEAT B LEFT OUTER JOIN S_INVESTIGATION_REPEAT A
ON A.PAGE_CASE_UID=B.PAGE_CASE_UID;
QUIT;

PROC DATASETS LIBRARY = WORK NOLIST;
DELETE 
	S_INVESTIGATION_REPEAT
	NUMERIC_BASE_METADATA
	DATE_DATA_PIVOT
	CODED_DATA_PIVOT
	CODED_DATA
	CODED_COUNTY_TABLE
	CODED_COUNTY_TABLE_DESC
	CODED_TABLE_SNTEMP
	CODED_TABLE_SNTEMP_TRANS
	D_INVESTIGATION_REPEAT
	NBS_CASE_ANSWER
	PHC_UIDS
	RDB_UI_METADATA
	TEXT_DATA TEXT_DATA_OUT
	CODED_DATA_OUT CODED_TABLE 
	DATE_DATA DATE_DATA_OUT 
	TEXT_METADATA NUMERIC_METADATA 
	CODED_METADATA DATE_METADATA
	NUMERIC_BASE_DATA NUMERIC_DATA1 
	NUMERIC_DATA2 NUMERIC_DATA_MERGED 
	NUMERIC_DATA_OUT NUMERIC_DATA_PIVOT 
	NUMERIC_DATA_TRANS NUMERIC_DATA_TRANS1
	STAGING_KEY
	INVESTIGATION_REPEAT_INIT
	STAGING_KEY_METADATA
RUN;

QUIT;
