PROC SQL;
DROP TABLE NBS_RDB.TB_PAM_LDF;
create table LDF_BASE as 
select DATAMART_COLUMN_NM, NBS_Case_Answer.ANSWER_TXT, NBS_Case_Answer.ACT_UID LENGTH =8 AS TB_PAM_UID  'TB_PAM_UID', 
NBS_Case_Answer.ADD_USER_ID, NBS_QUESTION.CODE_SET_GROUP_ID, 
NBS_Case_Answer.ADD_TIME, NBS_Case_Answer.LAST_CHG_USER_ID, NBS_Case_Answer.LAST_CHG_TIME 
FROM NBS_ODS.NBS_QUESTION   LEFT OUTER JOIN NBS_ODS.NBS_Case_Answer ON
nbs_question.nbs_question_uid=NBS_Case_Answer.nbs_question_uid
left outer join nbs_ods.nbs_UI_Metadata on 
nbs_question.nbs_question_uid=nbs_UI_Metadata.nbs_question_uid
where ldf_status_cd in ('LDF_UPDATE', 'LDF_CREATE', 'LDF_PROCESSED')
and nbs_UI_Metadata.investigation_form_cd ='INV_FORM_RVCT'
and nbs_UI_Metadata.record_status_cd in ('Active', 'Inactive');
/*AND NBS_Case_Answer.last_chg_time>(select start_date from ACTIVITY_LOG_MASTER_LAST);*/
QUIT;
PROC SQL;
CREATE TABLE LDF_BASE_CODED  AS 
	SELECT TB.*, a.CODE_SET_GROUP_ID, a.code_set_nm, class_cd 
	FROM LDF_BASE TB LEFT OUTER JOIN
	nbs_srt.codeset_group_metadata A ON
	A.CODE_SET_GROUP_ID=TB.CODE_SET_GROUP_ID
	 left outer join nbs_srt.codeset b on
	a.code_set_nm= b.code_set_nm;
QUIT;
PROC SQL;
CREATE TABLE LDF_BASE_CODED_TRANSLATED AS 
	SELECT 	DATAMART_COLUMN_NM, ANSWER_TXT,  TB_PAM_UID, 
			TB.ADD_USER_ID, TB.ADD_TIME, TB.LAST_CHG_USER_ID, TB.LAST_CHG_TIME, 
			CODE,CODE_SHORT_DESC_TXT AS CODE_SHORT_DESC_TXT, last_chg_time, TB.CODE_SET_NM, tb.CLASS_CD
	FROM	LDF_BASE_CODED TB
			LEFT JOIN NBS_SRT.CODE_VALUE_GENERAL CVG
			ON CVG.CODE_SET_NM=TB.CODE_SET_NM
			AND CVG.CODE=TB.ANSWER_TXT
			AND TB.CLASS_CD='code_value_general'
			/*WHERE tb.CODE_SET_NM NOT IN ('PSL_CNTRY','PHVS_STATE_CCD_ALPH','STATE_CCD')*/
	ORDER BY TB_PAM_UID, answer_txt;
QUIT;
data LDF_BASE_CODED_TRANSLATED;
set LDF_BASE_CODED_TRANSLATED;
if lengthn(CODE_SHORT_DESC_TXT)>0 then answer_txt= CODE_SHORT_DESC_TXT;
else answer_txt= answer_txt;
run;
PROC SQL;
CREATE TABLE LDF_BASE_CLINICAL_TRANSLATED AS 
	SELECT 	DATAMART_COLUMN_NM, ANSWER_TXT,  TB_PAM_UID, 
			ADD_USER_ID, ADD_TIME, LAST_CHG_USER_ID, LAST_CHG_TIME, 
			TB.CODE,CVG.CODE_SHORT_DESC_TXT AS CODE_SHORT_DESC_TXT, last_chg_time, TB.CODE_SET_NM, tb.CLASS_CD
	FROM	LDF_BASE_CODED_TRANSLATED TB
			LEFT JOIN NBS_SRT.CODE_VALUE_CLINICAL CVG
			ON CVG.CODE_SET_NM=TB.CODE_SET_NM
			AND CVG.CODE=TB.ANSWER_TXT
			AND TB.CLASS_CD='code_value_clinical'
	ORDER BY TB_PAM_UID, answer_txt;
QUIT;
data LDF_BASE_CLINICAL_TRANSLATED;
set LDF_BASE_CLINICAL_TRANSLATED;
if lengthn(CODE_SHORT_DESC_TXT)>0 then answer_txt= CODE_SHORT_DESC_TXT;
else answer_txt= answer_txt;
run;
PROC SQL;
CREATE TABLE LDF_BASE_STATE_TRANSLATED AS 
	SELECT 	DATAMART_COLUMN_NM, ANSWER_TXT,  TB_PAM_UID, 
			ADD_USER_ID, ADD_TIME, LAST_CHG_USER_ID, LAST_CHG_TIME, 
			TB.CODE,CVG.CODE_SHORT_DESC_TXT AS CODE_SHORT_DESC_TXT, last_chg_time, TB.CODE_SET_NM, tb.CLASS_CD
	FROM	LDF_BASE_CLINICAL_TRANSLATED TB
			LEFT OUTER JOIN NBS_SRT.V_STATE_CODE CVG
			ON CVG.CODE_SET_NM=TB.CODE_SET_NM
			AND CVG.STATE_CD=TB.ANSWER_TXT
			AND TB.CLASS_CD IN ('STATE_CCD', 'V_state_code')
			ORDER BY TB_PAM_UID, answer_txt;
QUIT;
data  LDF_BASE_STATE_TRANSLATED;
set  LDF_BASE_STATE_TRANSLATED;
if lengthn(CODE_SHORT_DESC_TXT)>0 then answer_txt= CODE_SHORT_DESC_TXT;
else answer_txt= answer_txt;
run;
PROC SQL;
CREATE TABLE LDF_BASE_COUNTRY_TRANSLATED AS 
	SELECT 	DATAMART_COLUMN_NM, ANSWER_TXT,  TB_PAM_UID, 
			ADD_USER_ID, ADD_TIME, LAST_CHG_USER_ID, LAST_CHG_TIME, 
			TB.CODE, CVG.CODE_SHORT_DESC_TXT AS CODE_SHORT_DESC_TXT, last_chg_time,TB.CODE_SET_NM, tb.CLASS_CD
	FROM	LDF_BASE_STATE_TRANSLATED TB
			LEFT JOIN NBS_SRT.COUNTRY_CODE CVG
			ON CVG.CODE_SET_NM=TB.CODE_SET_NM
			AND CVG.CODE=TB.ANSWER_TXT
			AND TB.CLASS_CD IN ('COUNTRY_CODE')
			ORDER BY TB_PAM_UID, answer_txt;
QUIT;
data LDF_BASE_COUNTRY_TRANSLATED;
set LDF_BASE_COUNTRY_TRANSLATED;
if lengthn(CODE_SHORT_DESC_TXT)>0 then answer_txt= CODE_SHORT_DESC_TXT;
else answer_txt= answer_txt;
run;
proc sort data= LDF_BASE_COUNTRY_TRANSLATED; by tb_pam_uid datamart_column_nm; 
run;
data  LDF_BASE_COUNTRY_TRANSLATED; 
length x $4000; 
set  LDF_BASE_COUNTRY_TRANSLATED; by tb_pam_uid datamart_column_nm; 
retain x; 
if  first.datamart_column_nm then x=' '; x=catx(' | ',x,answer_txt); 
if last.datamart_column_nm; 

if lengthn(x)>0 then answer_txt=x;
run; 
PROC TRANSPOSE DATA=  LDF_BASE_COUNTRY_TRANSLATED OUT=  LDF_TRANSLATED;
    BY TB_PAM_UID;
	COPY ADD_TIME;
	ID DATAMART_COLUMN_NM;
	VAR ANSWER_TXT;
RUN;
PROC SQL;
CREATE TABLE LDF_BASE2 AS 
SELECT D_TB_PAM.TB_PAM_UID,LDF_TRANSLATED.*
FROM NBS_RDB.D_TB_PAM left outer join  LDF_TRANSLATED on
D_TB_PAM.TB_PAM_UID=  LDF_TRANSLATED.TB_PAM_UID
WHERE LENGTHN(_LABEL_)>0;
QUIT;
DATA LDF_BASE2;
SET LDF_BASE2;
DROP _NAME_;
DROP _LABEL_;
RUN;
PROC SQL;
CREATE TABLE LDF_BASE3 AS 
SELECT INVESTIGATION.INVESTIGATION_KEY,LDF_BASE2.*
FROM LDF_BASE2 left outer join NBS_RDB.INVESTIGATION 
ON LDF_BASE2.TB_PAM_UID=INVESTIGATION.case_uid;
QUIT;
PROC SORT DATA=LDF_BASE3 nodupkey; BY INVESTIGATION_key; RUN;
PROC SQL;
CREATE TABLE NBS_RDB.TB_PAM_LDF AS SELECT * FROM LDF_BASE3;
QUIT;

