USE RDB
go 

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE Name = N'NOTIFICATION_LAST_CHANGE_TIME'
          AND Object_ID = Object_ID(N'dbo.NOTIFICATION'))
BEGIN

	ALTER TABLE dbo.NOTIFICATION add 
     	   NOTIFICATION_LAST_CHANGE_TIME DATETIME NULL;

END

go

IF OBJECT_ID('[dbo].[TMP_INV_SUMM_DATAMART]', 'U') IS NOT NULL 
				DROP TABLE rdb.[dbo].TMP_INV_SUMM_DATAMART
				;
  go


	IF OBJECT_ID('rdb.dbo.TMP_PATIENT_LOCATION_KEYS_INIT', 'U') IS NOT NULL
	BEGIN
	drop table rdb.dbo.TMP_PATIENT_LOCATION_KEYS_INIT;
	END
	GO



	


USE [RDB]
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


			 IF OBJECT_ID('rdb.dbo.sp_INV_SUMMARY_DATAMART', 'P') IS NOT NULL
				BEGIN
				DROP PROCEDURE dbo.sp_INV_SUMMARY_DATAMART;
				END;

GO



/*

exec rdb.[dbo].[sp_INV_SUMMARY_DATAMART]  9999

*/
	
CREATE PROCEDURE [dbo].[sp_INV_SUMMARY_DATAMART] 

            @batch_id BIGINT
	AS
BEGIN  
	 BEGIN TRY
	
	    --DECLARE  @batch_id BIGINT = 999;
		DECLARE @RowCount_no INT ;
		DECLARE @Proc_Step_no FLOAT = 0 ;
		DECLARE @Proc_Step_Name VARCHAR(200) = '' ;
		DECLARE @batch_start_time datetime = null ;
		DECLARE @batch_end_time datetime = null ;
		
		DECLARE @COUNTSTD AS int	;



				SET @Proc_Step_no = 1;
				SET @Proc_Step_Name = 'SP_Start';
			
	
		      BEGIN TRANSACTION;
			
					INSERT INTO rdb.[dbo].[job_flow_log] (
							batch_id         ---------------@batch_id
						   ,[Dataflow_Name]  --------------'INV_SUMM_DATAMART'
						   ,[package_Name]   --------------'RDB.INV_SUMM_DATAMART'
						   ,[Status_Type]    ---------------START
						   ,[step_number]    ---------------@Proc_Step_no
						   ,[step_name]   ------------------@Proc_Step_Name=sp_start
						   ,[row_count] --------------------0
						   )
						   VALUES
						   (
						   @batch_id
						   ,'INV_SUMM_DATAMART'
						   ,'RDB.INV_SUMM_DATAMART'
						   ,'START'
						   ,@Proc_Step_no
						   ,@Proc_Step_Name
						   ,0
						   );
		  
		    COMMIT TRANSACTION;
			
	       		
 	    	BEGIN TRANSACTION;

					SET @Proc_Step_no = @Proc_Step_no  + 1;
		
					SET @Proc_Step_name='Checking case_management COUNT';


			
				SET @COUNTSTD= (select  count(*) from NBS_ODSE.dbo.case_management with(nolock) );
				----Print @COUNTSTD
		
				SELECT @batch_start_time = batch_start_dttm,@batch_end_time = batch_end_dttm
				FROM rdb.[dbo].[job_batch_log]
				WHERE status_type = 'start' and type_code='MasterETL'
				;


	
				--SET  @batch_start_time  = '2022-12-31 15:54:08'
				--SET  @batch_end_time = '2023-01-18 17:22:00'


				select @batch_start_time,@batch_end_time;

		
				SELECT @ROWCOUNT_NO = @@ROWCOUNT;

				INSERT INTO RDB.[DBO].[JOB_FLOW_LOG] 
				(BATCH_ID,[DATAFLOW_NAME],[PACKAGE_NAME] ,[STATUS_TYPE],[STEP_NUMBER],[STEP_NAME],[ROW_COUNT])
				VALUES(@BATCH_ID,'INV_SUMM_DATAMART','RDB.INV_SUMM_DATAMART','START',@PROC_STEP_NO,@PROC_STEP_NAME,@ROWCOUNT_NO);  

			 COMMIT TRANSACTION;

			 BEGIN TRANSACTION;
				SET @Proc_Step_no = @Proc_Step_no + 1;
				SET @Proc_Step_Name = 'Generating TMP_UPDATED_INV_WITH_NOTIF';
						

				DECLARE  @INV_SUMMARY_DATAMART_COUNT AS BIGINT=0;
				SET  @INV_SUMMARY_DATAMART_COUNT= (SELECT COUNT(*) FROM rdb..INV_SUMM_DATAMART);
				
				--SET  @INV_SUMMARY_DATAMART_COUNT= 0;


				IF(@INV_SUMMARY_DATAMART_COUNT=0) 	SET @batch_start_time ='01-01-1990';
				IF(@INV_SUMMARY_DATAMART_COUNT=0)	SET @batch_end_time =getDate();


				IF OBJECT_ID('rdb.dbo.TMP_UPDATED_INV_WITH_NOTIF', 'U') IS NOT NULL   
 				drop table rdb.dbo.TMP_UPDATED_INV_WITH_NOTIF;
			

			
				select INVESTIGATION.INVESTIGATION_KEY , INVESTIGATION.CASE_UID
				INTO rdb.dbo.TMP_UPDATED_INV_WITH_NOTIF
				from rdb.dbo.NOTIFICATION_EVENT with(nolock) 
					inner join	rdb.dbo.NOTIFICATION  with(nolock)  on NOTIFICATION_EVENT.NOTIFICATION_KEY = NOTIFICATION.NOTIFICATION_KEY
					INNER JOIN  RDB.DBO.RDB_DATE  with(nolock) ON RDB_DATE.DATE_KEY = NOTIFICATION_EVENT.NOTIFICATION_UPD_DT_KEY
					INNER JOIN RDB.DBO.INVESTIGATION  with(nolock)  ON INVESTIGATION.INVESTIGATION_KEY = NOTIFICATION_EVENT.INVESTIGATION_KEY
				WHERE (
						  (
						    INVESTIGATION.CASE_TYPE= 'I'
						    AND INVESTIGATION.RECORD_STATUS_CD = 'ACTIVE'
						    AND INVESTIGATION.[LAST_CHG_TIME]  >= @batch_start_time 
						    AND INVESTIGATION.[LAST_CHG_TIME]  <  @batch_end_time
						  )
					   OR 
						   RDB_DATE.DATE_MM_DD_YYYY>INVESTIGATION.LAST_CHG_TIME
					   or
					     NOTIFICATION.NOTIFICATION_KEY in ( select NOTIFICATION_KEY
					                                        from rdb..NOTIFICATION with ( nolock)
															where NOTIFICATION_LAST_CHANGE_TIME  >= @batch_start_time
															and   NOTIFICATION_LAST_CHANGE_TIME   <   @batch_end_time
															)
						)
				 AND @INV_SUMMARY_DATAMART_COUNT>0  
				 AND INVESTIGATION.CASE_TYPE= 'I'
				 AND INVESTIGATION.RECORD_STATUS_CD = 'ACTIVE'
				 ;


		
				SELECT @ROWCOUNT_NO = @@ROWCOUNT;

				INSERT INTO RDB.[DBO].[JOB_FLOW_LOG] 
				(BATCH_ID,[DATAFLOW_NAME],[PACKAGE_NAME] ,[STATUS_TYPE],[STEP_NUMBER],[STEP_NAME],[ROW_COUNT])
				VALUES(@BATCH_ID,'INV_SUMM_DATAMART','RDB.INV_SUMM_DATAMART','START',@PROC_STEP_NO,@PROC_STEP_NAME,@ROWCOUNT_NO);  

			 COMMIT TRANSACTION;
	
			BEGIN TRANSACTION;
					
	--------------------------2a. Create Table rdb.dbo.TMP_PATIENT_LOCATION_KEYS_INIT---STD Cases
		if (@COUNTSTD >0) ------------------STD CASES

		BEGIN

			 	
				select @batch_start_time,@batch_end_time;

				SET @Proc_Step_no = @Proc_Step_no + 1;
				SET @Proc_Step_Name = 'Generating STD TMP_PATIENT_LOCATION_KEYS_INIT';



			 --CREATE TABLE PATIENT_LOCATION_KEYS_INIT 
	   
	            
				IF OBJECT_ID('rdb.dbo.TMP_PATIENT_LOCATION_KEYS_INIT', 'U') IS NOT NULL
				drop table rdb.dbo.TMP_PATIENT_LOCATION_KEYS_INIT;


			   	SELECT DISTINCT
			I.INVESTIGATION_KEY			 AS  'INVESTIGATION_KEY',---1
			I.INVESTIGATION_STATUS		 AS  'INVESTIGATION_STATUS',---2
			I.INV_LOCAL_ID                       AS  'INVESTIGATION_LOCAL_ID',---3
			I.EARLIEST_RPT_TO_CNTY_DT            AS  'EARLIEST_RPT_TO_CNTY_DT',---4
			I.EARLIEST_RPT_TO_STATE_DT           AS  'EARLIEST_RPT_TO_STATE_DT',---5
			I.DIAGNOSIS_DT                       AS  'DIAGNOSIS_DATE',---6
			I.ILLNESS_ONSET_DT                   AS  'ILLNESS_ONSET_DATE',   ---7       
			I.INV_CASE_STATUS                    AS  'CASE_STATUS',---8
			I.CASE_RPT_MMWR_WK                   AS  'MMWR_WEEK',      ---9             
			I.CASE_RPT_MMWR_YR                   AS  'MMWR_YEAR' ,     ---10             
			I.CASE_OID                           AS  'PROGRAM_JURISDICTION_OID',---11
			I.HSPTL_ADMISSION_DT                 AS  'HSPTL_ADMISSION_DT',--12
			I.INV_START_DT                       AS  'INV_START_DT',---13
			I.INV_RPT_DT                         AS  'INV_RPT_DT', ---14
			I.CURR_PROCESS_STATE                 AS  'CURR_PROCESS_STATE',----15
			I.JURISDICTION_NM,                                         ---16
			I.ADD_TIME			AS  'INVESTIGATION_CREATE_DATE',--17
			I.INVESTIGATION_ADDED_BY	 AS  'INVESTIGATION_CREATED_BY',---18
			I.LAST_CHG_TIME			     AS  'INVESTIGATION_LAST_UPDTD_DATE',---19
			I.INVESTIGATION_LAST_UPDATED_BY		 AS  'INVESTIGATION_LAST_UPDTD_BY',---20
			I.PROGRAM_AREA_DESCRIPTION	 AS  'PROGRAM_AREA', ---21
		   COALESCE(GC.PHYSICIAN_KEY,0)          AS  'GENERIC_PHYSICIAN_KEY'  ,---22
           COALESCE(GC.PATIENT_KEY,0)	         AS  'GEN_PATI_KEY',---23
           COALESCE(CC.PHYSICIAN_KEY,0)	 AS  'CRS_PHYSICIAN_KEY',---24
           COALESCE(CC.PATIENT_KEY,0)	 AS  'CRS_PAT_KEY',---25
           COALESCE(MC.PHYSICIAN_KEY,0)	 AS  'MEASLES_PHYSICIAN_KEY',---26
           COALESCE(MC.PATIENT_KEY,0)	 AS  'MEASLES_PAT_KEY',---27
           COALESCE(RC.PHYSICIAN_KEY,0)	 AS  'RUBELLA_PHYSICIAN_KEY',---28
           COALESCE(RC.PATIENT_KEY,0)	 AS  'RUBELLA_PAT_KEY',---29
           COALESCE(HC.PHYSICIAN_KEY,0)	 AS  'HEPATITIS_PHYSICIAN_KEY',---30
           COALESCE(HC.PATIENT_KEY,0)		     AS  'HEPATITIS_PAT_KEY',---31
           COALESCE(BC.PHYSICIAN_KEY,0)		     AS  'BMIRD_PHYSICIAN_KEY',---32
           COALESCE(BC.PATIENT_KEY,0)	 AS  'BMIRD_PAT_KEY',---33
			BC.FIRST_POSITIVE_CULTURE_DT		 AS  'FIRST_POSITIVE_CULTURE_DT',---34
			COALESCE(PC.PHYSICIAN_KEY,0)		 AS  'PERTUSSIS_PHYSICIAN_KEY',---35
			COALESCE(PC.PATIENT_KEY	,0)	 AS  'PERTUSSIS_PAT_KEY',---36
				    COALESCE(F_TB.PHYSICIAN_KEY	,0)		 AS  'F_TB_PAM_PHYSICIAN_KEY',---37
			COALESCE(F_TB.PERSON_KEY,0)	 AS  'F_TB_PAM_PAT_KEY',---38
			COALESCE(F_VAR.PHYSICIAN_KEY,0)		 AS  'F_VAR_PAM_PHYSICIAN_KEY',---39
				    COALESCE(F_VAR.PERSON_KEY,0)		 AS  'F_VAR_PAM_PAT_KEY',---40
			COALESCE(F_PAGE.PHYSICIAN_KEY,0)	 AS  'F_PAGE_CASE_PHYSICIAN_KEY', ---41
			COALESCE(F_PAGE.PATIENT_KEY	,0)		 AS  'F_PAGE_PATIENT_KEY', ---42
			COALESCE(F_STD.PHYSICIAN_KEY,0)      AS  'F_STD_PHYSICIAN_KEY',---43
			COALESCE(F_STD.PATIENT_KEY,0)		 AS  'F_STD_PATIENT_KEY', ---STD---44
			Cast (NULL as  bigint)		 AS  'PATIENT_KEY',---45
			Cast (NULL as  bigint)               AS  'PHYSICIAN_KEY'---46
			INTO rdb.[dbo].TMP_PATIENT_LOCATION_KEYS_INIT
			FROM rdb.[dbo].[INVESTIGATION] I             with (nolock)     
				FULL JOIN  rdb.[dbo].GENERIC_CASE    GC      with (nolock) ON GC.INVESTIGATION_KEY    = I.INVESTIGATION_KEY
				FULL JOIN  rdb.[dbo].CRS_CASE        CC      with (nolock) ON CC.INVESTIGATION_KEY    = I.INVESTIGATION_KEY
				FULL JOIN  rdb.[dbo].MEASLES_CASE    MC      with (nolock) ON MC.INVESTIGATION_KEY    = I.INVESTIGATION_KEY
				FULL JOIN  rdb.[dbo].RUBELLA_CASE    RC      with (nolock) ON RC.INVESTIGATION_KEY    = I.INVESTIGATION_KEY
				FULL JOIN  rdb.[dbo].HEPATITIS_CASE  HC      with (nolock) ON HC.INVESTIGATION_KEY    = I.INVESTIGATION_KEY
				FULL JOIN  rdb.[dbo].BMIRD_CASE      BC      with (nolock) ON BC.INVESTIGATION_KEY    = I.INVESTIGATION_KEY
				FULL JOIN  rdb.[dbo].PERTUSSIS_CASE  PC      with (nolock) ON PC.INVESTIGATION_KEY    = I.INVESTIGATION_KEY
				FULL JOIN  rdb.[dbo].F_TB_PAM        F_TB    with (nolock) ON F_TB.INVESTIGATION_KEY  = I.INVESTIGATION_KEY
				FULL JOIN  rdb.[dbo].F_VAR_PAM       F_VAR   with (nolock) ON F_VAR.INVESTIGATION_KEY = I.INVESTIGATION_KEY
				FULL JOIN  rdb.[dbo].F_PAGE_CASE     F_PAGE  with (nolock) ON F_PAGE.INVESTIGATION_KEY= I.INVESTIGATION_KEY
				FULL JOIN  rdb.[dbo].[F_STD_PAGE_CASE]F_STD  with (nolock) ON F_STD.INVESTIGATION_KEY = I.INVESTIGATION_KEY--STD
				FULL JOIN  rdb.[dbo].EVENT_METRIC    EM      with (nolock) ON EM.LOCAL_ID             = I.INV_LOCAL_ID
			WHERE (I.CASE_TYPE= 'I' AND I.RECORD_STATUS_CD = 'ACTIVE'
				  AND I.[LAST_CHG_TIME]  >= @batch_start_time AND I.[LAST_CHG_TIME]<  @batch_end_time)
				  OR I.INVESTIGATION_KEY IN (SELECT INVESTIGATION_KEY FROM rdb.dbo.TMP_UPDATED_INV_WITH_NOTIF WITH (NOLOCK))
					 ;
						 
					   UPDATE  rdb.dbo.TMP_PATIENT_LOCATION_KEYS_INIT
						   SET PATIENT_KEY  = 
						   (CASE 
						   WHEN   GEN_PATI_KEY       >1  then  GEN_PATI_KEY 
						   WHEN   CRS_PAT_KEY        >1  then  CRS_PAT_KEY
						   WHEN   MEASLES_PAT_KEY    >1  then  MEASLES_PAT_KEY
						   WHEN   RUBELLA_PAT_KEY    >1  then  RUBELLA_PAT_KEY
						   WHEN   HEPATITIS_PAT_KEY  >1  then  HEPATITIS_PAT_KEY
						   WHEN   BMIRD_PAT_KEY      >1  then  BMIRD_PAT_KEY
						   WHEN   PERTUSSIS_PAT_KEY  >1  then  PERTUSSIS_PAT_KEY
						   WHEN   F_TB_PAM_PAT_KEY   >1  then  F_TB_PAM_PAT_KEY
						   WHEN   F_PAGE_PATIENT_KEY >1  then  F_PAGE_PATIENT_KEY
						   WHEN   F_VAR_PAM_PAT_KEY  >1  then  F_VAR_PAM_PAT_KEY
						   WHEN   F_STD_PATIENT_KEY  >1  then  F_STD_PATIENT_KEY---STD
					ELSE NULL 
						  END
						  )
						  ;

					UPDATE  rdb.dbo.TMP_PATIENT_LOCATION_KEYS_INIT
						   SET PHYSICIAN_KEY   = 
						   (CASE 
						   WHEN   GENERIC_PHYSICIAN_KEY    >1  then GENERIC_PHYSICIAN_KEY
						   WHEN   CRS_PHYSICIAN_KEY        >1  then CRS_PHYSICIAN_KEY
						   WHEN   MEASLES_PHYSICIAN_KEY    >1  then MEASLES_PHYSICIAN_KEY
						   WHEN   RUBELLA_PHYSICIAN_KEY    >1  then RUBELLA_PHYSICIAN_KEY
						   WHEN   HEPATITIS_PHYSICIAN_KEY  >1  then HEPATITIS_PHYSICIAN_KEY
						   WHEN   BMIRD_PHYSICIAN_KEY      >1  then BMIRD_PHYSICIAN_KEY
						   WHEN   PERTUSSIS_PHYSICIAN_KEY  >1  then PERTUSSIS_PHYSICIAN_KEY
						   WHEN   F_TB_PAM_PHYSICIAN_KEY   >1  then F_TB_PAM_PHYSICIAN_KEY
						   WHEN   F_VAR_PAM_PHYSICIAN_KEY  >1  then F_VAR_PAM_PHYSICIAN_KEY
						   WHEN   F_PAGE_CASE_PHYSICIAN_KEY>1  then F_PAGE_CASE_PHYSICIAN_KEY
						   WHEN   F_STD_PHYSICIAN_KEY      >1  then F_STD_PHYSICIAN_KEY 
					ELSE NULL 
						  END
						  )
						  ;


					--	DROP GENERIC_PHYSICIAN_KEY;
					--	DROP CRS_PHYSICIAN_KEY;
					--	DROP MEASLES_PHYSICIAN_KEY;
					--	DROP RUBELLA_PHYSICIAN_KEY;
					--	DROP HEPATITIS_PHYSICIAN_KEY;
					--	DROP BMIRD_PHYSICIAN_KEY;
					--	DROP PERTUSSIS_PHYSICIAN_KEY;
					--	DROP F_TB_PAM_PHYSICIAN_KEY;
					--	DROP F_VAR_PAM_PHYSICIAN_KEY;
					--	DROP F_PAGE_CASE_PHYSICIAN_KEY;
					--	DROP GEN_PAT_KEY;
					--	DROP CRS_PAT_KEY;
					--	DROP MEASLES_PAT_KEY;
					--	DROP RUBELLA_PAT_KEY;
					--	DROP HEPATITIS_PAT_KEY;
					--	DROP BMIRD_PAT_KEY;
					--	DROP PERTUSSIS_PAT_KEY;
					--	DROP F_TB_PAM_PAT_KEY;
					--	DROP F_VAR_PAM_PAT_KEY;

		  
		
				SELECT @ROWCOUNT_NO = @@ROWCOUNT;

				INSERT INTO RDB.[DBO].[JOB_FLOW_LOG] 
				(BATCH_ID,[DATAFLOW_NAME],[PACKAGE_NAME] ,[STATUS_TYPE],[STEP_NUMBER],[STEP_NAME],[ROW_COUNT])
				VALUES(@BATCH_ID,'INV_SUMM_DATAMART','RDB.INV_SUMM_DATAMART','START',@PROC_STEP_NO,@PROC_STEP_NAME,@ROWCOUNT_NO);  

			
		  END;
	COMMIT TRANSACTION;
	
	BEGIN TRANSACTION;
			
  --------------------------2a. Create Table rdb.dbo.TMP_PATIENT_LOCATION_KEYS_INIT---NON-STD Cases
	if (@COUNTSTD =0) ------------------NO STD CASES
	  begin
			--CREATE TABLE PATIENT_LOCATION_KEYS_INIT 
 

			 	SET @Proc_Step_no = @Proc_Step_no + 1;
				SET @Proc_Step_Name = 'Generating NON STD TMP_PATIENT_LOCATION_KEYS_INIT';
	
				IF OBJECT_ID('rdb.dbo.TMP_PATIENT_LOCATION_KEYS_INIT', 'U') IS NOT NULL
				drop table rdb.dbo.TMP_PATIENT_LOCATION_KEYS_INIT;


			
			SELECT DISTINCT
			I.INVESTIGATION_KEY			 AS  'INVESTIGATION_KEY',---1
			I.INVESTIGATION_STATUS		 AS  'INVESTIGATION_STATUS',---2
			I.INV_LOCAL_ID                       AS  'INVESTIGATION_LOCAL_ID',---3
			I.EARLIEST_RPT_TO_CNTY_DT            AS  'EARLIEST_RPT_TO_CNTY_DT',---4
			I.EARLIEST_RPT_TO_STATE_DT           AS  'EARLIEST_RPT_TO_STATE_DT',---5
			I.DIAGNOSIS_DT                       AS  'DIAGNOSIS_DATE',---6
			I.ILLNESS_ONSET_DT                   AS  'ILLNESS_ONSET_DATE',   ---7       
			I.INV_CASE_STATUS                    AS  'CASE_STATUS',---8
			I.CASE_RPT_MMWR_WK                   AS  'MMWR_WEEK',      ---9             
			I.CASE_RPT_MMWR_YR                   AS  'MMWR_YEAR' ,     ---10             
			I.CASE_OID                           AS  'PROGRAM_JURISDICTION_OID',---11
			I.HSPTL_ADMISSION_DT                 AS  'HSPTL_ADMISSION_DT',--12
			I.INV_START_DT                       AS  'INV_START_DT',---13
			I.INV_RPT_DT                         AS  'INV_RPT_DT', ---14
			I.CURR_PROCESS_STATE                 AS  'CURR_PROCESS_STATE',----15
			I.JURISDICTION_NM,                                         ---16
			I.ADD_TIME			 AS  'INVESTIGATION_CREATE_DATE',--17
			I.INVESTIGATION_ADDED_BY	 AS  'INVESTIGATION_CREATED_BY',---18
			I.LAST_CHG_TIME			     AS  'INVESTIGATION_LAST_UPDTD_DATE',---19
			I.INVESTIGATION_LAST_UPDATED_BY		 AS  'INVESTIGATION_LAST_UPDTD_BY',---20
			I.PROGRAM_AREA_DESCRIPTION	 AS  'PROGRAM_AREA', ---21
			COALESCE(GC.PHYSICIAN_KEY,0)          AS  'GENERIC_PHYSICIAN_KEY'  ,---22
				   COALESCE(GC.PATIENT_KEY,0)	         AS  'GEN_PATI_KEY',---23
				   COALESCE(CC.PHYSICIAN_KEY,0)	 AS  'CRS_PHYSICIAN_KEY',---24
				   COALESCE(CC.PATIENT_KEY,0)	 AS  'CRS_PAT_KEY',---25
				   COALESCE(MC.PHYSICIAN_KEY,0)	 AS  'MEASLES_PHYSICIAN_KEY',---26
				   COALESCE(MC.PATIENT_KEY,0)	 AS  'MEASLES_PAT_KEY',---27
				   COALESCE(RC.PHYSICIAN_KEY,0)	 AS  'RUBELLA_PHYSICIAN_KEY',---28
				   COALESCE(RC.PATIENT_KEY,0)	 AS  'RUBELLA_PAT_KEY',---29
				   COALESCE(HC.PHYSICIAN_KEY,0)	 AS  'HEPATITIS_PHYSICIAN_KEY',---30
				   COALESCE(HC.PATIENT_KEY,0)		     AS  'HEPATITIS_PAT_KEY',---31
				   COALESCE(BC.PHYSICIAN_KEY,0)		     AS  'BMIRD_PHYSICIAN_KEY',---32
				   COALESCE(BC.PATIENT_KEY,0)	 AS  'BMIRD_PAT_KEY',---33
			BC.FIRST_POSITIVE_CULTURE_DT		 AS  'FIRST_POSITIVE_CULTURE_DT',---34
			COALESCE(PC.PHYSICIAN_KEY,0)		 AS  'PERTUSSIS_PHYSICIAN_KEY',---35
			COALESCE(PC.PATIENT_KEY	,0)	 AS  'PERTUSSIS_PAT_KEY',---36
				    COALESCE(F_TB.PHYSICIAN_KEY	,0)		 AS  'F_TB_PAM_PHYSICIAN_KEY',---37
			COALESCE(F_TB.PERSON_KEY,0)	 AS  'F_TB_PAM_PAT_KEY',---38
			COALESCE(F_VAR.PHYSICIAN_KEY,0)		 AS  'F_VAR_PAM_PHYSICIAN_KEY',---39
				    COALESCE(F_VAR.PERSON_KEY,0)		 AS  'F_VAR_PAM_PAT_KEY',---40
			COALESCE(F_PAGE.PHYSICIAN_KEY,0)	 AS  'F_PAGE_CASE_PHYSICIAN_KEY',---41
			COALESCE(F_PAGE.PATIENT_KEY	,0)		 AS  'F_PAGE_PATIENT_KEY',---42
			Cast (NULL as  bigint)		 AS  'F_STD_PHYSICIAN_KEY', ---STD	---43
				   Cast (NULL as  bigint)		 AS  'F_STD_PATIENT_KEY',---44
				   Cast (NULL as  bigint)		 AS  'PATIENT_KEY',---45
			Cast (NULL as  bigint)               AS  'PHYSICIAN_KEY'---46
        INTO rdb.dbo.TMP_PATIENT_LOCATION_KEYS_INIT		
		FROM rdb.[dbo].[INVESTIGATION] I             with (nolock)     
			FULL JOIN  rdb.[dbo].GENERIC_CASE    GC      with (nolock) ON GC.INVESTIGATION_KEY    = I.INVESTIGATION_KEY
			FULL JOIN  rdb.[dbo].CRS_CASE        CC      with (nolock) ON CC.INVESTIGATION_KEY    = I.INVESTIGATION_KEY
			FULL JOIN  rdb.[dbo].MEASLES_CASE    MC      with (nolock) ON MC.INVESTIGATION_KEY    = I.INVESTIGATION_KEY
			FULL JOIN  rdb.[dbo].RUBELLA_CASE    RC      with (nolock) ON RC.INVESTIGATION_KEY    = I.INVESTIGATION_KEY
			FULL JOIN  rdb.[dbo].HEPATITIS_CASE  HC      with (nolock) ON HC.INVESTIGATION_KEY    = I.INVESTIGATION_KEY
			FULL JOIN  rdb.[dbo].BMIRD_CASE      BC      with (nolock) ON BC.INVESTIGATION_KEY    = I.INVESTIGATION_KEY
			FULL JOIN  rdb.[dbo].PERTUSSIS_CASE  PC      with (nolock) ON PC.INVESTIGATION_KEY    = I.INVESTIGATION_KEY
			FULL JOIN  rdb.[dbo].F_TB_PAM        F_TB    with (nolock) ON F_TB.INVESTIGATION_KEY  = I.INVESTIGATION_KEY
			FULL JOIN  rdb.[dbo].F_VAR_PAM       F_VAR   with (nolock) ON F_VAR.INVESTIGATION_KEY = I.INVESTIGATION_KEY
			FULL JOIN  rdb.[dbo].F_PAGE_CASE     F_PAGE  with (nolock) ON F_PAGE.INVESTIGATION_KEY= I.INVESTIGATION_KEY
			---		FULL JOIN  rdb.[dbo].[F_STD_PAGE_CASE]F_STD  with (nolock) ON F_STD.INVESTIGATION_KEY = I.INVESTIGATION_KEY--STD
			FULL JOIN  rdb.[dbo].EVENT_METRIC    EM      with (nolock) ON EM.LOCAL_ID             = I.INV_LOCAL_ID
			WHERE I.CASE_TYPE= 'I' AND I.RECORD_STATUS_CD = 'ACTIVE'

			AND I.[LAST_CHG_TIME]  >= @batch_start_time AND I.[LAST_CHG_TIME]<  @batch_end_time  
			OR I.INVESTIGATION_KEY IN (SELECT INVESTIGATION_KEY FROM rdb.dbo.TMP_UPDATED_INV_WITH_NOTIF WITH (NOLOCK))
			;
			

			 UPDATE  rdb.dbo.TMP_PATIENT_LOCATION_KEYS_INIT
			   SET PATIENT_KEY  = 
			   (CASE 
			   WHEN   GEN_PATI_KEY       >1  then  GEN_PATI_KEY 
			   WHEN   CRS_PAT_KEY        >1  then  CRS_PAT_KEY
			   WHEN   MEASLES_PAT_KEY    >1  then  MEASLES_PAT_KEY
			   WHEN   RUBELLA_PAT_KEY    >1  then  RUBELLA_PAT_KEY
                               WHEN   HEPATITIS_PAT_KEY  >1  then  HEPATITIS_PAT_KEY
			   WHEN   BMIRD_PAT_KEY      >1  then  BMIRD_PAT_KEY
			   WHEN   PERTUSSIS_PAT_KEY  >1  then  PERTUSSIS_PAT_KEY
			   WHEN   F_TB_PAM_PAT_KEY   >1  then  F_TB_PAM_PAT_KEY
			   WHEN   F_PAGE_PATIENT_KEY >1  then  F_PAGE_PATIENT_KEY
			   WHEN   F_VAR_PAM_PAT_KEY  >1  then  F_VAR_PAM_PAT_KEY
			   ELSE NULL 
			  END
			  )
			  ;

			   UPDATE  rdb.dbo.TMP_PATIENT_LOCATION_KEYS_INIT
			   SET PHYSICIAN_KEY   = 
			   (CASE 
			   WHEN   GENERIC_PHYSICIAN_KEY    >1  then GENERIC_PHYSICIAN_KEY
			   WHEN   CRS_PHYSICIAN_KEY        >1  then CRS_PHYSICIAN_KEY
			   WHEN   MEASLES_PHYSICIAN_KEY    >1  then MEASLES_PHYSICIAN_KEY
			   WHEN   RUBELLA_PHYSICIAN_KEY    >1  then RUBELLA_PHYSICIAN_KEY
                               WHEN   HEPATITIS_PHYSICIAN_KEY  >1  then HEPATITIS_PHYSICIAN_KEY
			   WHEN   BMIRD_PHYSICIAN_KEY      >1  then BMIRD_PHYSICIAN_KEY
			   WHEN   PERTUSSIS_PHYSICIAN_KEY  >1  then PERTUSSIS_PHYSICIAN_KEY
			   WHEN   F_TB_PAM_PHYSICIAN_KEY   >1  then F_TB_PAM_PHYSICIAN_KEY
			   WHEN   F_VAR_PAM_PHYSICIAN_KEY  >1  then F_VAR_PAM_PHYSICIAN_KEY
			   WHEN   F_PAGE_CASE_PHYSICIAN_KEY>1  then F_PAGE_CASE_PHYSICIAN_KEY
		    ---WHEN   F_STD_PHYSICIAN_KEY      >1  then F_STD_PHYSICIAN_KEY 
			    ELSE NULL 
			  END
			  )
			  ;
		
                SELECT @ROWCOUNT_NO = @@ROWCOUNT;

				INSERT INTO RDB.[DBO].[JOB_FLOW_LOG] 
				(BATCH_ID,[DATAFLOW_NAME],[PACKAGE_NAME] ,[STATUS_TYPE],[STEP_NUMBER],[STEP_NAME],[ROW_COUNT])
				VALUES(@BATCH_ID,'INV_SUMM_DATAMART','RDB.INV_SUMM_DATAMART','START',@PROC_STEP_NO,@PROC_STEP_NAME,@ROWCOUNT_NO);  


           END;

/*

	DROP GENERIC_PHYSICIAN_KEY;
	DROP CRS_PHYSICIAN_KEY;
	DROP MEASLES_PHYSICIAN_KEY;
	DROP RUBELLA_PHYSICIAN_KEY;
	DROP HEPATITIS_PHYSICIAN_KEY;
	DROP BMIRD_PHYSICIAN_KEY;
	DROP PERTUSSIS_PHYSICIAN_KEY;
	DROP F_TB_PAM_PHYSICIAN_KEY;
	DROP F_VAR_PAM_PHYSICIAN_KEY;
	DROP F_PAGE_CASE_PHYSICIAN_KEY;
	DROP GEN_PAT_KEY;
	DROP CRS_PAT_KEY;
	DROP MEASLES_PAT_KEY;
	DROP RUBELLA_PAT_KEY;
	DROP HEPATITIS_PAT_KEY;
	DROP BMIRD_PAT_KEY;
	DROP PERTUSSIS_PAT_KEY;
	DROP F_TB_PAM_PAT_KEY;
	DROP F_VAR_PAM_PAT_KEY;
	DROP F_PAGE_PATIENT_KEY;
	DROP F_STD_PATIENT_KEY;
RUN;
*/




	
			COMMIT TRANSACTION;
		

			BEGIN TRANSACTION;
						SET @Proc_Step_no = @Proc_Step_no +1 ;
						SET @Proc_Step_Name = 'Generating tmp_CONFIRMATION_METHOD_BASE';
						


				IF OBJECT_ID('rdb.dbo.tmp_CONFIRMATION_METHOD_BASE', 'U') IS NOT NULL
				drop table rdb.dbo.tmp_CONFIRMATION_METHOD_BASE;


 
				--create table CONFIRMATION_METHOD_BASE as 
				select cm.*, cmg.investigation_key, cmg.confirmation_dt 
				into rdb.dbo.tmp_CONFIRMATION_METHOD_BASE
				from RDB..confirmation_method cm with (nolock),
			 RDB..confirmation_method_group cmg with (nolock), 
			 rdb.dbo.TMP_PATIENT_LOCATION_KEYS_INIT tpi with ( nolock)
				where 
			cmg.confirmation_method_key= cm.confirmation_method_key
				and cmg.investigation_key =tpi.investigation_key
				--order by cmg.investigation_key
				;


/*
PROC TRANSPOSE DATA=CONFIRMATION_METHOD_BASE OUT=CONFIRMATION_METHOD_PIVOT;
    BY investigation_key;
	COPY investigation_key confirmation_dt;
	VAR CONFIRMATION_METHOD_DESC;
RUN;
*/


/*



DELETE FROM CONFIRMATION_METHOD_PIVOT WHERE _NAME_ IS NULL;

data CONFIRMATION_METHOD_PIVOT;
set CONFIRMATION_METHOD_PIVOT;
LENGTH CONFIRMATION_METHOD $3000;
CONFIRMATION_METHOD = catx(" | ", of COL1, COL2, COL3, COL4, COL5, COL6, COL7, COL8, COL9,COL10,COL11,COL12,COL13);
x = index(CONFIRMATION_METHOD, ' | .');
if x > 0 then CONFIRMATION_METHOD = substr(CONFIRMATION_METHOD, 1, x);
if lengthn(CONFIRMATION_METHOD)>0 then x1 = lengthn(CONFIRMATION_METHOD);
else x1= -1;
if x= x1 then CONFIRMATION_METHOD = substr(CONFIRMATION_METHOD, 1, (x-1));
DROP COL1 COL2 COL3 COL4 COL5 COL6 COL7 COL8 COL9 COL10 COL11 COL12 COL13 X X1 _LABEL_ _NAME_;
RUN;
*/




	           SELECT @ROWCOUNT_NO = @@ROWCOUNT;

				INSERT INTO RDB.[DBO].[JOB_FLOW_LOG] 
				(BATCH_ID,[DATAFLOW_NAME],[PACKAGE_NAME] ,[STATUS_TYPE],[STEP_NUMBER],[STEP_NAME],[ROW_COUNT])
				VALUES(@BATCH_ID,'INV_SUMM_DATAMART','RDB.INV_SUMM_DATAMART','START',@PROC_STEP_NO,@PROC_STEP_NAME,@ROWCOUNT_NO);  

			COMMIT TRANSACTION;
		

			BEGIN TRANSACTION;
						SET @Proc_Step_no = @Proc_Step_no +1 ;
						SET @Proc_Step_Name = 'Generating TMP_CONFIRMATION_METHOD_BASE2';
						

--VS

		--------------------------------------5. Create Table TMP_S_CONFIRMATION_METHOD_PIVOT
		
		IF OBJECT_ID('rdb.dbo.TMP_CONFIRMATION_METHOD_BASE', 'U') IS NOT NULL   
		drop table rdb.dbo.TMP_CONFIRMATION_METHOD_BASE  ;


		SELECT CM.*, 
		       CMG.INVESTIGATION_KEY, 
			   CMG.[CONFIRMATION_DT] 
		INTO  rdb.dbo.TMP_CONFIRMATION_METHOD_BASE
		FROM 
				 rdb.dbo.[CONFIRMATION_METHOD] CM with (nolock),
				 rdb.dbo.[CONFIRMATION_METHOD_GROUP]CMG with (nolock), 
			     rdb.dbo.TMP_PATIENT_LOCATION_KEYS_INIT PL with (nolock)
			
		WHERE CMG.[CONFIRMATION_METHOD_KEY]= CM.[CONFIRMATION_METHOD_KEY]
		  and CMG.[INVESTIGATION_KEY]      = PL.INVESTIGATION_KEY
		;





	           SELECT @ROWCOUNT_NO = @@ROWCOUNT;

				INSERT INTO RDB.[DBO].[JOB_FLOW_LOG] 
				(BATCH_ID,[DATAFLOW_NAME],[PACKAGE_NAME] ,[STATUS_TYPE],[STEP_NUMBER],[STEP_NAME],[ROW_COUNT])
				VALUES(@BATCH_ID,'INV_SUMM_DATAMART','RDB.INV_SUMM_DATAMART','START',@PROC_STEP_NO,@PROC_STEP_NAME,@ROWCOUNT_NO);  

			COMMIT TRANSACTION;
		

			BEGIN TRANSACTION;

						SET @Proc_Step_no = @Proc_Step_no +1 ;
						SET @Proc_Step_Name = 'Generating TMP_CONFIRMATION_METHOD_PIVOT';
						
		
		IF OBJECT_ID('rdb.dbo.TMP_CONFIRMATION_METHOD_PIVOT', 'U') IS NOT NULL
		DROP TABLE rdb.dbo.TMP_CONFIRMATION_METHOD_PIVOT;
	


			Declare @CONFIRMATION_METHOD_DESC nvarchar(max)='',
			@sqlQuery nvarchar(max)=''

			;With CTE_Description 
			AS
			(SELECT DISTINCT COALESCE(CONFIRMATION_METHOD_DESC,'NULL') as CMD FROM rdb.[dbo].[CONFIRMATION_METHOD] )

			SELECT @CONFIRMATION_METHOD_DESC= @CONFIRMATION_METHOD_DESC+QUOTENAME(LTRIM(RTRIM([CMD]))) +',' from CTE_Description
			SET @CONFIRMATION_METHOD_DESC= LEFT( @CONFIRMATION_METHOD_DESC,len( @CONFIRMATION_METHOD_DESC)-1)

			----Print @CONFIRMATION_METHOD_DESC

			SET @sqlQuery = 
			'
			SELECT * Into rdb.dbo.TMP_CONFIRMATION_METHOD_PIVOT  FROM 
			(
			SELECT * from
				  (
			 SELECT CONFIRMATION_METHOD_DESC,investigation_key ,confirmation_dt
			 FROM   rdb.dbo.TMP_CONFIRMATION_METHOD_BASE 
			 GROUP BY  investigation_key,CONFIRMATION_METHOD_DESC,confirmation_dt
				  )MAIN
				 PIVOT
			   (
			MAX(CONFIRMATION_METHOD_DESC) For CONFIRMATION_METHOD_DESC in
		 
			('+
			 @CONFIRMATION_METHOD_DESC
				  +')
				)as P) as c

			'
			PRINT (@sqlQuery)
			EXEC sp_executesql  @sqlQuery

			SELECT @ROWCOUNT_NO = @@ROWCOUNT;

					INSERT INTO RDB.[DBO].[JOB_FLOW_LOG] 
					(BATCH_ID,[DATAFLOW_NAME],[PACKAGE_NAME] ,[STATUS_TYPE],[STEP_NUMBER],[STEP_NAME],[ROW_COUNT])
					VALUES(@BATCH_ID,'INV_SUMM_DATAMART','RDB.INV_SUMM_DATAMART','START',@PROC_STEP_NO,@PROC_STEP_NAME,@ROWCOUNT_NO);  


					COMMIT TRANSACTION;
		

			BEGIN TRANSACTION;

						SET @Proc_Step_no = @Proc_Step_no +1 ;
						SET @Proc_Step_Name = 'Update  TMP_CONFIRMATION_METHOD_PIVOT';
			
			----added
			BEGIN

				ALTER TABLE rdb.dbo.TMP_CONFIRMATION_METHOD_PIVOT 
				ADD CONFIRMATION_METHOD varchar(2000)

			END

			  ;WITH  CTE as 
		
		
			(
				select Investigation_key, 
				(    STUFF(
					(SELECT ' | ' + CAST(CMB.[CONFIRMATION_METHOD_DESC] AS varchar(2000))
					 FROM rdb..TMP_CONFIRMATION_METHOD_Base CMB
					 inner join rdb.dbo.TMP_CONFIRMATION_METHOD_PIVOT p on CMB.INVESTIGATION_KEY=p.INVESTIGATION_KEY
				     WHERE CMB.[INVESTIGATION_KEY] =CMP.[INVESTIGATION_KEY]
					 FOR XML PATH('')
					)
				   , 2 ,1, ''
				  )

				 ) AS CODE_DESC_TXT_List
				from  rdb.dbo.TMP_CONFIRMATION_METHOD_Pivot CMP  
			----	where [CONFIRMATION_dt] is not null ----Commended on 3/29/2021
				group by [INVESTIGATION_KEY]
			)

		UPDATE CMP
		set CMP.confirmation_Method = RTRIM(ltrim(cte1.CODE_DESC_TXT_List))
		from  rdb.dbo.TMP_CONFIRMATION_METHOD_PIVOT CMP, 
			 CTE CTE1
		where CMP.[INVESTIGATION_KEY] = CTE1.[INVESTIGATION_KEY] ;

--VS






	           SELECT @ROWCOUNT_NO = @@ROWCOUNT;

				INSERT INTO RDB.[DBO].[JOB_FLOW_LOG] 
				(BATCH_ID,[DATAFLOW_NAME],[PACKAGE_NAME] ,[STATUS_TYPE],[STEP_NUMBER],[STEP_NAME],[ROW_COUNT])
				VALUES(@BATCH_ID,'INV_SUMM_DATAMART','RDB.INV_SUMM_DATAMART','START',@PROC_STEP_NO,@PROC_STEP_NAME,@ROWCOUNT_NO);  

			COMMIT TRANSACTION;
		

			BEGIN TRANSACTION;
						SET @Proc_Step_no = @Proc_Step_no +1 ;
						SET @Proc_Step_Name = 'Generating tmp_PATIENT_LOCATION_KEYS';
						




--create table PATIENT_LOCATION_KEYS as 


		IF OBJECT_ID('rdb.dbo.tmp_PATIENT_LOCATION_KEYS', 'U') IS NOT NULL
		DROP TABLE rdb.dbo.tmp_PATIENT_LOCATION_KEYS;


		select A.*, 
		B.CONFIRMATION_METHOD, 
		B.CONFIRMATION_DT as confirmationdte
		into rdb.dbo.tmp_PATIENT_LOCATION_KEYS
		from rdb.dbo.tmp_CONFIRMATION_METHOD_PIVOT B 
		inner join rdb.dbo.tmp_PATIENT_LOCATION_KEYS_INIT A on a.investigation_key = b.investigation_key;






	           SELECT @ROWCOUNT_NO = @@ROWCOUNT;

				INSERT INTO RDB.[DBO].[JOB_FLOW_LOG] 
				(BATCH_ID,[DATAFLOW_NAME],[PACKAGE_NAME] ,[STATUS_TYPE],[STEP_NUMBER],[STEP_NAME],[ROW_COUNT])
				VALUES(@BATCH_ID,'INV_SUMM_DATAMART','RDB.INV_SUMM_DATAMART','START',@PROC_STEP_NO,@PROC_STEP_NAME,@ROWCOUNT_NO);  

			COMMIT TRANSACTION;
		

			BEGIN TRANSACTION;
						SET @Proc_Step_no = @Proc_Step_no +1 ;
						SET @Proc_Step_Name = 'Generating tmp_PATIENT_INFO';
						

		--CREATE TABLE 	PATIENT_INFO

		 IF OBJECT_ID('rdb.dbo.tmp_PATIENT_INFO', 'U') IS NOT NULL
			DROP TABLE rdb.dbo.tmp_PATIENT_INFO;

		 SELECT 
			KEYS.*,
			C.CONDITION_DESC AS DISEASE ,
			C.CONDITION_CD AS DISEASE_CD 
		into rdb..tmp_PATIENT_INFO
		FROM rdb..tmp_PATIENT_LOCATION_KEYS keys
		  INNER JOIN RDB..CASE_COUNT CC ON 		keys.investigation_key=CC.investigation_key
		  INNER JOIN  RDB..CONDITION C ON C.CONDITION_KEY=CC.CONDITION_KEY 
		;





	           SELECT @ROWCOUNT_NO = @@ROWCOUNT;

				INSERT INTO RDB.[DBO].[JOB_FLOW_LOG] 
				(BATCH_ID,[DATAFLOW_NAME],[PACKAGE_NAME] ,[STATUS_TYPE],[STEP_NUMBER],[STEP_NAME],[ROW_COUNT])
				VALUES(@BATCH_ID,'INV_SUMM_DATAMART','RDB.INV_SUMM_DATAMART','START',@PROC_STEP_NO,@PROC_STEP_NAME,@ROWCOUNT_NO);  

			COMMIT TRANSACTION;
		

			BEGIN TRANSACTION;
						SET @Proc_Step_no = @Proc_Step_no +1 ;
						SET @Proc_Step_Name = 'Generating tmp_PHYSICIAN_INFO';
						

		 IF OBJECT_ID('rdb.dbo.tmp_PHYSICIAN_INFO', 'U') IS NOT NULL
			DROP TABLE rdb.dbo.tmp_PHYSICIAN_INFO;


 
	
			--	CREATE TABLE PHYSICIAN_INFO AS 


			   SELECT KEYS.*,
 				   PROVIDER_LAST_NAME AS PHYSICIAN_LAST_NAME ,
				   PROVIDER_FIRST_NAME AS PHYSICIAN_FIRST_NAME  
				into rdb.dbo.tmp_PHYSICIAN_INFO
				FROM rdb..tmp_PATIENT_INFO KEYS 
				left outer join RDB..D_PROVIDER ON	KEYS.PHYSICIAN_KEY =D_PROVIDER.PROVIDER_KEY
				--ORDER BY PATIENT_KEY
				;






	           SELECT @ROWCOUNT_NO = @@ROWCOUNT;

				INSERT INTO RDB.[DBO].[JOB_FLOW_LOG] 
				(BATCH_ID,[DATAFLOW_NAME],[PACKAGE_NAME] ,[STATUS_TYPE],[STEP_NUMBER],[STEP_NAME],[ROW_COUNT])
				VALUES(@BATCH_ID,'INV_SUMM_DATAMART','RDB.INV_SUMM_DATAMART','START',@PROC_STEP_NO,@PROC_STEP_NAME,@ROWCOUNT_NO);  

			COMMIT TRANSACTION;
		

			BEGIN TRANSACTION;
						SET @Proc_Step_no = @Proc_Step_no +1 ;
						SET @Proc_Step_Name = 'Generating tmp_PATIENT_DETAILS';
						

		 IF OBJECT_ID('rdb.dbo.tmp_PATIENT_DETAILS', 'U') IS NOT NULL
			DROP TABLE rdb.dbo.tmp_PATIENT_DETAILS;


		--CREATE TABLE PATIENT_DETAILS AS

		  SELECT 
			A.*, 
			PATIENT.PATIENT_FIRST_NAME AS PATIENT_FIRST_NAME , 
			PATIENT.PATIENT_LAST_NAME AS PATIENT_LAST_NAME ,
			PATIENT.PATIENT_COUNTY AS PATIENT_COUNTY  ,
			PATIENT_COUNTY_CODE,
			PATIENT.PATIENT_STREET_ADDRESS_1 AS  PATIENT_STREET_ADDRESS_1 ,
			PATIENT.PATIENT_STREET_ADDRESS_2 AS   PATIENT_STREET_ADDRESS_2 ,
			PATIENT.PATIENT_CITY AS  PATIENT_CITY  ,
			PATIENT.PATIENT_STATE AS   PATIENT_STATE ,
			PATIENT.PATIENT_ZIP AS   PATIENT_ZIP ,

			PATIENT.PATIENT_ETHNICITY AS PATIENT_HISPANIC_IND ,
			PATIENT.PATIENT_LOCAL_ID AS PATIENT_LOCAL_ID ,
			PATIENT.PATIENT_DOB AS PATIENT_DOB ,
			PATIENT.PATIENT_CURRENT_SEX AS PATIENT_CURRENT_SEX ,
			PATIENT.PATIENT_AGE_REPORTED AS AGE_REPORTED ,
			PATIENT.PATIENT_AGE_REPORTED_UNIT AS AGE_REPORTED_UNIT ,
			PATIENT.PATIENT_ETHNICITY AS PATIENT_ETHNICITY ,
			PATIENT.PATIENT_RACE_CALCULATED AS RACE_CALCULATED ,
			PATIENT.PATIENT_RACE_CALC_DETAILS AS RACE_CALC_DETAILS 
		  into rdb.dbo.tmp_PATIENT_DETAILS
		  FROM 	rdb.dbo.tmp_PHYSICIAN_INFO A
			LEFT OUTER JOIN	RDB..D_PATIENT PATIENT ON 	PATIENT.PATIENT_KEY=A.PATIENT_KEY
			;



		  --CREATE TABLE INV_WITH_USER AS 
				/*
		--VS CHECK WHY COMMENTED IN SQL

		 IF OBJECT_ID('rdb.dbo.tmp_INV_WITH_USER', 'U') IS NOT NULL
			DROP TABLE rdb.dbo.tmp_INV_WITH_USER;


   
		   SELECT A.*,  
				  B.FIRST_NM AS CREATEUSER_FIRST_NM,B.LAST_NM AS CREATEUSER_LAST_NM,
				  C.FIRST_NM AS EDITUSER_FIRST_NM, C.LAST_NM AS EDITUSER_LAST_NM
			into rdb.dbo.tmp_INV_WITH_USER
			FROM rdb.dbo.tmp_PATIENT_DETAILS A 
    			LEFT JOIN 	RDB..USER_PROFILE B ON 	A.INVESTIGATION_CREATED_BY=B.NEDSS_ENTRY_ID
				LEFT JOIN	RDB..USER_PROFILE C	ON	A.INVESTIGATION_LAST_UPDTD_BY=C.NEDSS_ENTRY_ID
				;


		DATA INV_WITH_USER;
		SET INV_WITH_USER;
		DROP INVESTIGATION_CREATED_BY;
		DROP INVESTIGATION_LAST_UPDTD_BY;
		RUN;
		DATA INV_WITH_USER;
		SET INV_WITH_USER;
		IF LENGTHN(TRIM(CREATEUSER_FIRST_NM))> 0 AND LENGTHN(TRIM(CREATEUSER_LAST_NM))>0  THEN INVESTIGATION_CREATED_BY = TRIM(CREATEUSER_LAST_NM)|| ',' ||TRIM(CREATEUSER_FIRST_NM);
		ELSE IF LENGTHN(TRIM(CREATEUSER_LAST_NM))>0 THEN INVESTIGATION_CREATED_BY = TRIM(CREATEUSER_LAST_NM);
		ELSE IF LENGTHN(TRIM(CREATEUSER_LAST_NM))>0 THEN INVESTIGATION_CREATED_BY= TRIM(CREATEUSER_FIRST_NM);
		IF LENGTHN(TRIM(EDITUSER_LAST_NM))> 0 AND LENGTHN(TRIM(EDITUSER_FIRST_NM))>0  THEN INVESTIGATION_LAST_UPDTD_BY = TRIM(EDITUSER_LAST_NM)|| ',' ||TRIM(EDITUSER_FIRST_NM);
		ELSE IF LENGTHN(TRIM(EDITUSER_LAST_NM))>0 THEN INVESTIGATION_LAST_UPDTD_BY = TRIM(EDITUSER_FIRST_NM);
		ELSE IF LENGTHN(TRIM(EDITUSER_LAST_NM))>0 THEN INVESTIGATION_LAST_UPDTD_BY = TRIM(EDITUSER_FIRST_NM);
		RUN;
		*/




	           SELECT @ROWCOUNT_NO = @@ROWCOUNT;

				INSERT INTO RDB.[DBO].[JOB_FLOW_LOG] 
				(BATCH_ID,[DATAFLOW_NAME],[PACKAGE_NAME] ,[STATUS_TYPE],[STEP_NUMBER],[STEP_NAME],[ROW_COUNT])
				VALUES(@BATCH_ID,'INV_SUMM_DATAMART','RDB.INV_SUMM_DATAMART','START',@PROC_STEP_NO,@PROC_STEP_NAME,@ROWCOUNT_NO);  

			COMMIT TRANSACTION;
		

			BEGIN TRANSACTION;

			   SET @Proc_Step_no = @Proc_Step_no +1 ;
			   SET @Proc_Step_Name = 'GENERATING TMP_S_INV_SUMM_DATAMART_INIT'; 

					IF OBJECT_ID('rdb.dbo.TMP_S_INV_SUMM_DATAMART_INIT', 'U') IS NOT NULL   
					drop table rdb.dbo.TMP_S_INV_SUMM_DATAMART_INIT  ;
 
			         ; With CTE as ( 
			        SELECT A.*, 
					NOTI.NOTIFICATION_STATUS,
					NOTI.NOTIFICATION_LOCAL_ID, 
					NOTI.NOTIFICATION_SUBMITTED_BY ,
					NOTI.NOTIFICATION_LAST_CHANGE_TIME,
					RDB_DATE.DATE_MM_DD_YYYY  AS 'NOTIFICATION_CREATE_DATE', 					
					RDB_DATE_SENT.DATE_MM_DD_YYYY  AS  'NOTIFICATION_SENT_DATE',
					ROW_NUMBER() OVER (Partition by A.Investigation_Key Order by RDB_DATE.DATE_MM_DD_YYYY ASC )as rn
					--INTO rdb.dbo.TMP_S_INV_SUMM_DATAMART_INIT
				FROM rdb.dbo.tmp_PATIENT_DETAILS A

					LEFT OUTER JOIN rdb.[dbo].[NOTIFICATION_EVENT] NOT_EVENT with (nolock) ON A.INVESTIGATION_KEY=NOT_EVENT.INVESTIGATION_KEY
					LEFT OUTER JOIN rdb.[dbo].[NOTIFICATION]            NOTI with (nolock) ON NOTI.NOTIFICATION_KEY=NOT_EVENT.NOTIFICATION_KEY
					LEFT OUTER JOIN rdb.[dbo].[RDB_DATE]		    RDB_DATE with (nolock) ON NOT_EVENT.NOTIFICATION_SUBMIT_DT_KEY= RDB_DATE.DATE_KEY
					LEFT OUTER JOIN rdb.[dbo].[RDB_DATE]       RDB_DATE_SENT with (nolock) ON NOT_EVENT.NOTIFICATION_SENT_DT_KEY= RDB_DATE_SENT.DATE_KEY
				
				)
			Select *  
			INTO rdb.dbo.TMP_S_INV_SUMM_DATAMART_INIT from CTE where rn=1
			;
			
			SELECT @ROWCOUNT_NO = @@ROWCOUNT;

			update rdb.dbo.TMP_S_INV_SUMM_DATAMART_INIT set NOTIFICATION_CREATE_DATE=null where NOTIFICATION_STATUS is null;
			update rdb.dbo.TMP_S_INV_SUMM_DATAMART_INIT set  NOTIFICATION_SUBMITTED_BY=null where NOTIFICATION_STATUS is null;

			INSERT INTO RDB.[DBO].[JOB_FLOW_LOG] 
			(BATCH_ID,[DATAFLOW_NAME],[PACKAGE_NAME] ,[STATUS_TYPE],[STEP_NUMBER],[STEP_NAME],[ROW_COUNT])
			VALUES(@BATCH_ID,'INV_SUMM_DATAMART','RDB.INV_SUMM_DATAMART','START',@PROC_STEP_NO,@PROC_STEP_NAME,@ROWCOUNT_NO);  
        
       COMMIT TRANSACTION;

---------------------------------------------------------12. Create table TMP_InvLab
  BEGIN TRANSACTION;

			   SET @PROC_STEP_NO = @PROC_STEP_NO+1;
			   SET @Proc_Step_Name = 'GENERATING TMP_InvLab'; 


			IF OBJECT_ID('rdb.dbo.TMP_InvLab', 'U') IS NOT NULL   
			drop table rdb.dbo.TMP_InvLab ;
					
			    SELECT L.INVESTIGATION_KEY, L.LAB_TEST_KEY
				INTO  rdb.dbo.TMP_InvLab
				FROM  rdb.dbo.LAB_TEST_RESULT L   with (nolock)
				INNER JOIN rdb.dbo.INVESTIGATION I with (nolock)ON L.INVESTIGATION_KEY = I.INVESTIGATION_KEY
				 WHERE (L.LAB_TEST_KEY IN(SELECT  LAB_TEST_KEY FROM rdb.dbo.LAB_TEST  where LAB_RPT_LAST_UPDATE_DT >= @batch_start_time and  LAB_RPT_LAST_UPDATE_DT <   @batch_end_time)) 
				  AND (L.INVESTIGATION_KEY <> 1) 	AND (I.RECORD_STATUS_CD = 'ACTIVE')
				  --and L.LAB_RPT_LAST_UPDATE_DT >= @batch_start_time
			   -- 	and L.LAB_RPT_LAST_UPDATE_DT <   @batch_end_time
				 ORDER BY LAB_TEST_KEY;
				

			SELECT @ROWCOUNT_NO = @@ROWCOUNT;

			INSERT INTO RDB.[DBO].[JOB_FLOW_LOG] 
			(BATCH_ID,[DATAFLOW_NAME],[PACKAGE_NAME] ,[STATUS_TYPE],[STEP_NUMBER],[STEP_NAME],[ROW_COUNT])
			VALUES(@BATCH_ID,'INV_SUMM_DATAMART','RDB.INV_SUMM_DATAMART','START',@PROC_STEP_NO,@PROC_STEP_NAME,@ROWCOUNT_NO);  
        
		     		COMMIT TRANSACTION;
------------------------------------------------------------13 Create Table  TMP_Lab------------------------------------------------------
  BEGIN TRANSACTION;

			   SET @PROC_STEP_NO = @PROC_STEP_NO + 1;
			   SET @PROC_STEP_NAME = 'GENERATING TMP_Lab'; 


			IF OBJECT_ID('rdb.dbo.TMP_Lab', 'U') IS NOT NULL   
			drop table rdb.dbo.TMP_Lab ;

				SELECT 
					 lab_test_key,
					 lab_rpt_local_id 
				INTO rdb.dbo.TMP_Lab
				FROM  rdb.dbo.Lab_test with (nolock) order by lab_test_key;

				SELECT @ROWCOUNT_NO = @@ROWCOUNT;

			INSERT INTO RDB.[DBO].[JOB_FLOW_LOG] 
			(BATCH_ID,[DATAFLOW_NAME],[PACKAGE_NAME] ,[STATUS_TYPE],[STEP_NUMBER],[STEP_NAME],[ROW_COUNT])
			VALUES(@BATCH_ID,'INV_SUMM_DATAMART','RDB.INV_SUMM_DATAMART','START',@PROC_STEP_NO,@PROC_STEP_NAME,@ROWCOUNT_NO);  
                    
			COMMIT TRANSACTION;

--------------------------------------------------14. Create Table  Tmp_BothTable--------------------------------------

  BEGIN TRANSACTION;

			   SET @PROC_STEP_NO = @Proc_Step_no + 1 ;

			   SET @PROC_STEP_NAME = 'GENERATING  Tmp_BothTable'; 


			IF OBJECT_ID('rdb.dbo.TMP_BothTable', 'U') IS NOT NULL   
			drop table  rdb.dbo.TMP_BothTable ;



			          SELECT INV.INVESTIGATION_KEY,
			           INV.LAB_TEST_KEY as INVTestKey,
			   L.LAB_TEST_KEY   as LabTestKey,
			   L.LAB_RPT_LOCAL_ID
			  INTO  rdb.dbo.TMP_BothTable
			  FROM rdb.dbo.TMP_InvLab INV,
			       rdb.dbo.TMP_Lab  L
				   WHERE INV.LAB_TEST_KEY = L.LAB_TEST_KEY

                     SELECT @ROWCOUNT_NO = @@ROWCOUNT;

			INSERT INTO RDB.[DBO].[JOB_FLOW_LOG] 
			(BATCH_ID,[DATAFLOW_NAME],[PACKAGE_NAME] ,[STATUS_TYPE],[STEP_NUMBER],[STEP_NAME],[ROW_COUNT])
			VALUES(@BATCH_ID,'INV_SUMM_DATAMART','RDB.INV_SUMM_DATAMART','START',@PROC_STEP_NO,@PROC_STEP_NAME,@ROWCOUNT_NO);  
        
            		COMMIT TRANSACTION;


  BEGIN TRANSACTION;;
					 SET @PROC_STEP_NO = @PROC_STEP_NO + 1;
					 SET @Proc_Step_Name = 'GENERATING  TMP_Inv2Labs'; 


					IF OBJECT_ID('rdb.dbo.TMP_Inv2Labs', 'U') IS NOT NULL   
					         drop table rdb.dbo.TMP_Inv2Labs ;
						
					SELECT distinct 
						 b.investigation_key, 
						 b.LabTestKey as lab_test_key,
						 l.lab_rpt_LOCAL_ID, 
						 l.LAB_RPT_RECEIVED_BY_PH_DT, 
						 l.SPECIMEN_COLLECTION_DT,
						 l.RESULTED_LAB_TEST_CD_DESC, 
						 l.RESULTEDTEST_VAL_CD_DESC,
						 l.NUMERIC_RESULT_WITHUNITS,             
						 l.LAB_RESULT_TXT_VAL, 
						 l.LAB_RESULT_COMMENTS,
                         l.ELR_IND
					  INTO rdb.dbo.TMP_Inv2Labs
                      FROM rdb.dbo.TMP_BothTable b 
					   INNER JOIN  rdb.dbo.lab100   l with (nolock) on  l.LAB_RPT_LOCAL_ID = b.LAB_RPT_LOCAL_ID
						order by b.investigation_key;

                                     SELECT @ROWCOUNT_NO = @@ROWCOUNT;

			INSERT INTO RDB.[DBO].[JOB_FLOW_LOG] 
			(BATCH_ID,[DATAFLOW_NAME],[PACKAGE_NAME] ,[STATUS_TYPE],[STEP_NUMBER],[STEP_NAME],[ROW_COUNT])
			VALUES(@BATCH_ID,'INV_SUMM_DATAMART','RDB.INV_SUMM_DATAMART','START',@PROC_STEP_NO,@PROC_STEP_NAME,@ROWCOUNT_NO);  
  COMMIT TRANSACTION;
------------------------------------------------------------------16. Create Table TMP_SPECIMEN_COLLECTION---------------------------------------------------------
        BEGIN TRANSACTION
					 SET @PROC_STEP_NO = @PROC_STEP_NO + 1;
					 SET @Proc_Step_Name = 'GENERATING  TMP_SPECIMEN_COLLECT	ION'; 


					IF OBJECT_ID('rdb.dbo.TMP_SPECIMEN_COLLECTION', 'U') IS NOT NULL   
					         drop table rdb.dbo.TMP_SPECIMEN_COLLECTION ;
			   			
						  SELECT DISTINCT  INVESTIGATION_KEY ,
						  MIN(SPECIMEN_COLLECTION_DT) as  EARLIEST_SPECIMEN_COLLECTION_DT
						  INTO  rdb.dbo.TMP_SPECIMEN_COLLECTION
						  from  rdb.dbo.TMP_Inv2Labs with (nolock)where SPECIMEN_COLLECTION_DT is not null 
						  Group by INVESTIGATION_KEY 
					     union 
						   select INVESTIGATION_KEY,EARLIEST_SPECIMEN_COLLECTION_DT
                            from rdb.dbo.TMP_CLDM_CASE_LAB_DATAMART_FINAL
                             ;


					SELECT @ROWCOUNT_NO = @@ROWCOUNT;

					INSERT INTO RDB.[DBO].[JOB_FLOW_LOG] 
					(BATCH_ID,[DATAFLOW_NAME],[PACKAGE_NAME] ,[STATUS_TYPE],[STEP_NUMBER],[STEP_NAME],[ROW_COUNT])
					VALUES(@BATCH_ID,'INV_SUMM_DATAMART','RDB.INV_SUMM_DATAMART','START',@PROC_STEP_NO,@PROC_STEP_NAME,@ROWCOUNT_NO);  
   COMMIT TRANSACTION;
-----------------------------------------------------------------17. Create Table TMP_CASE_LAB_DATAMART_MODIFIED---------------------------------
  BEGIN TRANSACTION;
					 SET @PROC_STEP_NO = @PROC_STEP_NO + 1 ;
					 SET @PROC_STEP_NAME = 'GENERATING  TMP_CASE_LAB_DATAMART_MODIFIED'; 


					IF OBJECT_ID('rdb.dbo.TMP_CASE_LAB_DATAMART_MODIFIED', 'U') IS NOT NULL   
					         drop table  rdb.dbo.TMP_CASE_LAB_DATAMART_MODIFIED ;

			 				
						
						 SELECT DISTINCT C.INVESTIGATION_KEY ,
						    SC.EARLIEST_SPECIMEN_COLLECTION_DT 
						  INTO  rdb.dbo.TMP_CASE_LAB_DATAMART_MODIFIED 
						  from  rdb.dbo.[CASE_LAB_DATAMART] C with (nolock) 
						    JOIN rdb.dbo.TMP_SPECIMEN_COLLECTION SC with (nolock) ON SC.INVESTIGATION_KEY = C.INVESTIGATION_KEY 
						   order by C.INVESTIGATION_KEY asc
						  ;

					SELECT @ROWCOUNT_NO = @@ROWCOUNT;

					INSERT INTO RDB.[DBO].[JOB_FLOW_LOG] 
					(BATCH_ID,[DATAFLOW_NAME],[PACKAGE_NAME] ,[STATUS_TYPE],[STEP_NUMBER],[STEP_NAME],[ROW_COUNT])
					VALUES(@BATCH_ID,'INV_SUMM_DATAMART','RDB.INV_SUMM_DATAMART','START',@PROC_STEP_NO,@PROC_STEP_NAME,@ROWCOUNT_NO);  

      COMMIT TRANSACTION;
------------------------------------------------------18. Create Table  TMP_INV_SUMM_DATAMART

/*
--CREATE TABLE 	INV_SUMM_DATAMART_INIT AS 


SELECT A.*,  NOTI.NOTIFICATION_STATUS,
NOTI.NOTIFICATION_LOCAL_ID, NOTI.NOTIFICATION_SUBMITTED_BY ,
RDB_DATE.DATE_MM_DD_YYYY  AS NOTIFICATION_CREATE_DATE 'NOTIFICATION_CREATE_DATE', 
RDB_DATE_SENT.DATE_MM_DD_YYYY  AS NOTIFICATION_SENT_DATE 'NOTIFICATION_SENT_DATE',


RDB_DATE_UPD.DATE_MM_DD_YYYY  AS NOTIFICATION_LAST_UPDATED_DATE 'NOTIFICATION_LAST_UPDATED_DATE',
INVESTIGATION_LAST_UPDTD_BY AS NOTIFICATION_LAST_UPDATED_USER 'NOTIFICATION_LAST_UPDATED_USER',
trim(NOTIFUSER.LAST_NM) ||', '||trim(NOTIFUSER.FIRST_NM) AS NOTIFICATION_SUBMITTER 'NOTIFICATION_SUBMITTER'

FROM 
	INV_WITH_USER A
LEFT OUTER JOIN 
	RDB..NOTIFICATION_EVENT NOT_EVENT
ON 
	A.INVESTIGATION_KEY=NOT_EVENT.INVESTIGATION_KEY
LEFT OUTER JOIN 
	RDB..NOTIFICATION NOTI
ON
	NOTI.NOTIFICATION_KEY=NOT_EVENT.NOTIFICATION_KEY
LEFT OUTER JOIN RDB..RDB_DATE
ON
   NOT_EVENT.NOTIFICATION_SUBMIT_DT_KEY= RDB_DATE.DATE_KEY
   
   
LEFT OUTER JOIN RDB..RDB_DATE RDB_DATE_SENT
ON
   NOT_EVENT.NOTIFICATION_SENT_DT_KEY= RDB_DATE_SENT.DATE_KEY

LEFT OUTER JOIN RDB..RDB_DATE RDB_DATE_UPD
ON
   NOT_EVENT.NOTIFICATION_UPD_DT_KEY= RDB_DATE_UPD.DATE_KEY   
   
LEFT OUTER JOIN RDB..USER_PROFILE NOTIFUSER

ON
NOTI.NOTIFICATION_SUBMITTED_BY=NOTIFUSER.NEDSS_ENTRY_ID
;	
*/



		

			BEGIN TRANSACTION;

						SET @Proc_Step_no = @Proc_Step_no +1 ;
						SET @Proc_Step_Name = 'Generating TMP_INV_SUMM_DATAMART';
						

		              IF OBJECT_ID('rdb.dbo.TMP_INV_SUMM_DATAMART', 'U') IS NOT NULL   
		      drop table    rdb.dbo.TMP_INV_SUMM_DATAMART 
			  
			  select A.*
			   	,A.INVESTIGATION_CREATED_BY  as NOTIFICATION_SUBMITTER      ---42-------6/2/2021 ---
				--,A.INVESTIGATION_LAST_UPDTD_DATE AS NOTIFICATION_LAST_UPDATED_DATE	---43
				,coalesce(A.NOTIFICATION_LAST_CHANGE_TIME,A.INVESTIGATION_LAST_UPDTD_DATE) AS NOTIFICATION_LAST_UPDATED_DATE	---43
				
				,Substring(A.INVESTIGATION_LAST_UPDTD_BY,1,50) as NOTIFICATION_LAST_UPDATED_USER	------44-----------6/2/2021
				,A.CONFIRMATIONDTE as CONFIRMATION_DT   ----49 
				,A.DIAGNOSIS_DATE as DIAGNOSIS_DT   ----49
				,A.ILLNESS_ONSET_DATE as ILLNESS_ONSET_DT
				,Substring(B.LABORATORY_INFORMATION,1,4000) as LABORATORY_INFORMATION ----54----6/2/2021
				,S.EARLIEST_SPECIMEN_COLLECTION_DT  EARLIEST_SPECIMEN_COLLECT_DATE ----55 ----dont have this field in the table
				,S.EARLIEST_SPECIMEN_COLLECTION_DT   ----55 ----dont have this field in the table

				,CAST(NULL as datetime ) as EVENT_DATE----56
			    ,CAST(NULL as  varchar(200))as EVENT_DATE_TYPE----57
				
				 INTO rdb.dbo.TMP_INV_SUMM_DATAMART
				 FROM rdb.dbo.TMP_S_INV_SUMM_DATAMART_INIT A 
			    LEFT OUTER JOIN rdb.[dbo].[CASE_LAB_DATAMART]  B  with (nolock) ON 	A.INVESTIGATION_KEY=B.INVESTIGATION_KEY
				LEFT OUTER JOIN rdb.dbo.TMP_CASE_LAB_DATAMART_MODIFIED S with (nolock) ON A.INVESTIGATION_KEY=S.INVESTIGATION_KEY 
				;

				
				
			


	               		UPDATE TMP_INV_SUMM_DATAMART SET  NOTIFICATION_LAST_UPDATED_DATE=NULL WHERE NOTIFICATION_STATUS IS NULL;
						UPDATE TMP_INV_SUMM_DATAMART SET  NOTIFICATION_LAST_UPDATED_USER=NULL WHERE NOTIFICATION_STATUS IS NULL;
						UPDATE TMP_INV_SUMM_DATAMART SET  NOTIFICATION_SUBMITTER=NULL WHERE NOTIFICATION_STATUS IS NULL;
									


					            SELECT @ROWCOUNT_NO = @@ROWCOUNT;

					          INSERT INTO RDB.[DBO].[JOB_FLOW_LOG] 
									(BATCH_ID,[DATAFLOW_NAME],[PACKAGE_NAME] ,[STATUS_TYPE],[STEP_NUMBER],[STEP_NAME],[ROW_COUNT])
									VALUES(@BATCH_ID,'INV_SUMM_DATAMART','RDB.INV_SUMM_DATAMART','START',@PROC_STEP_NO,@PROC_STEP_NAME,@ROWCOUNT_NO);

			COMMIT TRANSACTION;
		
		---------------------
		
			BEGIN TRANSACTION;

			  SET @Proc_Step_no = @Proc_Step_no +1 ;
		
			  SET @PROC_STEP_NAME = 'Updating Additional values in rdb.dbo.INV_SUMM_DATAMART'; 


			  
		        IF OBJECT_ID('rdb.dbo.TMP_INV_SUMM_DATAMART_LAB_DT', 'U') IS NOT NULL   
		          drop table    rdb.dbo.TMP_INV_SUMM_DATAMART_LAB_DT ;
		


									------Added since lab info was not updating----on 6/8/2021 
									--	 UPDATE rdb.dbo.INV_SUMM_DATAMART
									--	    SET  [LABORATORY_INFORMATION]         = CLD.[LABORATORY_INFORMATION]
									--	 FROM    rdb.[dbo].[CASE_LAB_DATAMART] as CLD
									--	    INNER JOIN  rdb.dbo.INVESTIGATION  AS I
									--	       ON CLD.INVESTIGATION_KEY=I.INVESTIGATION_KEY and CLD.INVESTIGATION_LOCAL_ID=I.INV_LOCAL_ID 
									--	 WHERE CLD.INVESTIGATION_KEY     =INV_SUMM_DATAMART.INVESTIGATION_KEY
									--	       and   CLD.INVESTIGATION_LOCAL_ID =INV_SUMM_DATAMART.INVESTIGATION_LOCAL_ID
									--	       and   CLD.PHC_LAST_CHG_TIME = I.LAST_CHG_TIME
									--		   ;
									
									 ----Added since lab Specimen info was not updating----on 6/9/2021 
																			
			
			

										--;With CTE as (
										--		Select C.INVESTIGATION_KEY,C.INVESTIGATION_LOCAL_ID,LH.LAB_RPT_LAST_UPDATE_DT,I.Last_CHG_TIME,LH.SPECIMEN_COLLECTION_DT ,LH.Event_Date,
										--		ROW_NUMBER() OVER (PARTITION BY C.INVESTIGATION_KEY 
										--												ORDER BY LH.SPECIMEN_COLLECTION_DT ASC
         	--																	) AS [ROWNO]    
										--		from rdb.[dbo].[CASE_LAB_DATAMART] C 
										--		INNER JOIN rdb.dbo.INVESTIGATION   I ON I.INV_LOCAL_ID = C.INVESTIGATION_LOCAL_ID and C.INVESTIGATION_KEY= I.INVESTIGATION_KEY
										--		INNER JOIN rdb.[dbo].[LAB_TEST_RESULT] LTR ON I.INVESTIGATION_KEY =LTR.INVESTIGATION_KEY
										--		INNER JOIN rdb.dbo.Lab_test LT  ON LTR.LAB_TEST_UID=LT.LAB_RPT_UID and LTR.LAB_TEST_KEY=LT.LAB_TEST_KEY
										--		INNER JOIN  rdb.dbo.lab100 LH On LH.LAB_RPT_LOCAL_ID=LT.LAB_RPT_LOCAL_ID and C.PATIENT_LOCAL_ID= LH.PERSON_LOCAL_ID
										--		WHERE LH.LAB_RPT_LAST_UPDATE_DT >I.Last_CHG_TIME  and LH.SPECIMEN_COLLECTION_DT is not null
										--          )
										--	      Select *  INTO rdb.dbo.TMP_INV_SUMM_DATAMART_LAB_DT FROM CTE  where ROWNO=1
										--		  ;

										--	UPDATE   rdb.dbo.TMP_INV_SUMM_DATAMART
										--	SET  EARLIEST_SPECIMEN_COLLECT_DATE = t.SPECIMEN_COLLECTION_DT
										----	, [EVENT_DATE]       = t.EVENT_DATE
										--	FROM rdb.dbo.TMP_INV_SUMM_DATAMART_LAB_DT t
										--	WHERE
										--		   t.INVESTIGATION_KEY      =TMP_INV_SUMM_DATAMART.INVESTIGATION_KEY and 
										--		   t.INVESTIGATION_LOCAL_ID =TMP_INV_SUMM_DATAMART.INVESTIGATION_LOCAL_ID
										--	       and   EARLIEST_SPECIMEN_COLLECT_DATE > t.SPECIMEN_COLLECTION_DT
										--			;
					

             


	
						-- DECLARE	@return_value int = 0;
						-- DECLARE	@ERROR_MSG_BACK varchar(100)


						--	EXEC	@return_value = [dbo].SP_UPDATE_EVENT_DATE
						--			@batch_id = 999,
						--			@Dataflow_Name = N'INV_SUMM_DATAMART',
						--			@vTableName = N'rdb.dbo.TMP_INV_SUMM_DATAMART',
						--		    @ERROR_MSG = @ERROR_MSG_BACK;

      --                     select 'SP_UPDATE_EVENT_DATE',@return_value;


						--	if @return_value = -1
						--	  begin

					  			   
      --   				 IF @@TRANCOUNT > 0   ROLLBACK TRANSACTION;

						--INSERT INTO rdb.[dbo].[job_flow_log] (
						--		batch_id
						--	   ,[Dataflow_Name]
						--	   ,[package_Name]
						--		,[Status_Type] 
						--	   ,[step_number]
						--	   ,[step_name]
						--	   ,[Error_Description]
						--	   ,[row_count]
						--	   )
						--	   VALUES
						--	   (
						--	   @batch_id
						--	   ,'TMP_INV_SUMM_DATAMART'	
						--	   ,'RDB.TMP_INV_SUMM_DATAMART'
						--	   ,'ERROR'
						--	   ,@Proc_Step_no
						--	   ,'ERROR - '+  @ERROR_MSG_BACK
						--	   , 'Step -' + ' Table not found'
						--	   ,0
						--	   );

 					--		      return -1;

						--	  end 
						--	;
						


			
			        UPDATE rdB.dbo.TMP_INV_SUMM_DATAMART 
					set              DISEASE                = substring( DISEASE,1,50)-- DISEASE 
 									,INVESTIGATION_STATUS   = Substring( INVESTIGATION_STATUS,1,50) --INVESTIGATION_STATUS  
 									,CASE_STATUS            = Substring( CASE_STATUS,1,50)-- CASE_STATUS  
 									,INVESTIGATION_LAST_UPDTD_BY = substring( INVESTIGATION_LAST_UPDTD_BY,1,50)-- INVESTIGATION_LAST_UPDTD_BY    
 									,NOTIFICATION_LAST_UPDATED_USER = Substring( NOTIFICATION_LAST_UPDATED_USER,1,50)-- NOTIFICATION_LAST_UPDATED_USER	
 									,CURR_PROCESS_STATE     = Substring( CURR_PROCESS_STATE,1,50)-- CURR_PROCESS_STATE     
 									,JURISDICTION_NM        = Substring( JURISDICTION_NM,1,100)-- JURISDICTION_NM      	
 									,LABORATORY_INFORMATION = Substring(LABORATORY_INFORMATION,1,4000) 
					;


			       

	           SELECT @ROWCOUNT_NO = @@ROWCOUNT;

				INSERT INTO RDB.[DBO].[JOB_FLOW_LOG] 
				(BATCH_ID,[DATAFLOW_NAME],[PACKAGE_NAME] ,[STATUS_TYPE],[STEP_NUMBER],[STEP_NAME],[ROW_COUNT])
				VALUES(@BATCH_ID,'INV_SUMM_DATAMART','RDB.INV_SUMM_DATAMART','START',@PROC_STEP_NO,@PROC_STEP_NAME,@ROWCOUNT_NO);  

			COMMIT TRANSACTION;
		
		---------------------
	
			BEGIN TRANSACTION;

			  SET @Proc_Step_no = @Proc_Step_no +1 ;
		
			  SET @PROC_STEP_NAME = 'Updating rdb.dbo.INV_SUMM_DATAMART'; 


							UPDATE  rdb.dbo.INV_SUMM_DATAMART
  							 SET  [INVESTIGATION_KEY]             =  ISD.[INVESTIGATION_KEY],---1
							      [PATIENT_LOCAL_ID]              =  ISD.[PATIENT_LOCAL_ID] ,---2
							      [PATIENT_KEY]                   =  ISD.[PATIENT_KEY],----3
	                              [INVESTIGATION_LOCAL_ID]        =  ISD.[INVESTIGATION_LOCAL_ID],---4
								  [DISEASE]                       =  ISD.[DISEASE] ,---5
								  [DISEASE_CD]                    =  ISD.[DISEASE_CD] ,---6
	                              [PATIENT_FIRST_NAME]            =  ISD.[PATIENT_FIRST_NAME] ,---7
								  [PATIENT_LAST_NAME]             =  ISD.[PATIENT_LAST_NAME],---8
								  [PATIENT_DOB]                   =  ISD.[PATIENT_DOB]  ,---9
	                              [PATIENT_CURRENT_SEX]           =  ISD.[PATIENT_CURRENT_SEX] ,---10
								  [AGE_REPORTED]                  =  ISD.[AGE_REPORTED],----11
								  [AGE_REPORTED_UNIT]             =  ISD.[AGE_REPORTED_UNIT],----12
	                              [PATIENT_STREET_ADDRESS_1]      =  ISD.[PATIENT_STREET_ADDRESS_1] ,----13
								  [PATIENT_STREET_ADDRESS_2]      =  ISD.[PATIENT_STREET_ADDRESS_2] ,-----14
								  [PATIENT_CITY]                  =  ISD.[PATIENT_CITY],----15
	                              [PATIENT_STATE]                 =  ISD.[PATIENT_STATE] ,----16
								  [PATIENT_ZIP]                   =  ISD.[PATIENT_ZIP] ,----17
								  [PATIENT_COUNTY]                =  ISD.[PATIENT_COUNTY] ,---18
								  [PATIENT_ETHNICITY]             =  ISD.[PATIENT_ETHNICITY] ,----19
	                              [RACE_CALCULATED]               =  ISD.[RACE_CALCULATED],---table name changed---20
								  [RACE_CALC_DETAILS]             =  ISD.[RACE_CALC_DETAILS],---table name changed---21
								  [INVESTIGATION_STATUS]          =  ISD.[INVESTIGATION_STATUS],---22
	                              [EARLIEST_RPT_TO_CNTY_DT]       =  ISD.[EARLIEST_RPT_TO_CNTY_DT],---23
								  [EARLIEST_RPT_TO_STATE_DT]      =  ISD.[EARLIEST_RPT_TO_STATE_DT]  ,---24
								  [DIAGNOSIS_DATE]                =  ISD.[DIAGNOSIS_DATE] ,---25
	                              [ILLNESS_ONSET_DATE]            =  ISD.[ILLNESS_ONSET_DATE],---26
								  [CASE_STATUS]                   =  ISD.[CASE_STATUS],---27
								  [MMWR_WEEK]                     =  ISD.[MMWR_WEEK] ,---28
								  [MMWR_YEAR]                     =  ISD.[MMWR_YEAR] ,---29
								  [INVESTIGATION_CREATE_DATE]     =  ISD.[INVESTIGATION_CREATE_DATE] ,---30
	                              [INVESTIGATION_CREATED_BY]      =  ISD.[INVESTIGATION_CREATED_BY],---31
								  [INVESTIGATION_LAST_UPDTD_DATE] =  ISD.[INVESTIGATION_LAST_UPDTD_DATE],---32
								  [NOTIFICATION_STATUS]            = ISD.[NOTIFICATION_STATUS]  ,----33
								  [INVESTIGATION_LAST_UPDTD_BY]    = ISD.[INVESTIGATION_LAST_UPDTD_BY] ,----34
								  [PROGRAM_JURISDICTION_OID]       = ISD.[PROGRAM_JURISDICTION_OID] ,---35
								  [PROGRAM_AREA]                   = ISD.[PROGRAM_AREA],-----36
								  [PHYSICIAN_LAST_NAME]            = ISD.[PHYSICIAN_LAST_NAME] ,----37
								  [PHYSICIAN_FIRST_NAME]           = ISD.[PHYSICIAN_FIRST_NAME],----38
								  [NOTIFICATION_LOCAL_ID]          = ISD.[NOTIFICATION_LOCAL_ID],----39
								  [NOTIFICATION_CREATE_DATE]       = ISD.[NOTIFICATION_CREATE_DATE] ,----40
						    	  [NOTIFICATION_SENT_DATE]         = ISD.[NOTIFICATION_SENT_DATE],  ----41         ---Required since NBS 6.3
								  [NOTIFICATION_SUBMITTER]         = ISD.[NOTIFICATION_SUBMITTER]  ,---42
								  [NOTIFICATION_LAST_UPDATED_DATE] = ISD.[NOTIFICATION_LAST_UPDATED_DATE] ,---43
								  [NOTIFICATION_LAST_UPDATED_USER] = ISD.[NOTIFICATION_LAST_UPDATED_USER],---44
								  [FIRST_POSITIVE_CULTURE_DT]      = ISD.[FIRST_POSITIVE_CULTURE_DT] ,---45
								  [INV_START_DT]                   = ISD.[INV_START_DT]  ,---46
								  [HSPTL_ADMISSION_DT]             = ISD.[HSPTL_ADMISSION_DT],---47
								  [INV_RPT_DT]                     = ISD.[INV_RPT_DT],----48
								  [CONFIRMATION_DT]                = ISD.[CONFIRMATION_DT] ,----49
								  [CONFIRMATION_METHOD]            = ISD.[CONFIRMATION_METHOD],----50
								  [CURR_PROCESS_STATE]             = ISD.[CURR_PROCESS_STATE] ,----51
								  [JURISDICTION_NM]                = ISD.[JURISDICTION_NM],---52
								  [PATIENT_COUNTY_CODE]            = ISD.[PATIENT_COUNTY_CODE],---53
								  [LABORATORY_INFORMATION]         = ISD.[LABORATORY_INFORMATION]----54
								  --[EARLIEST_SPECIMEN_COLLECT_DATE] = ISD.[EARLIEST_SPECIMEN_COLLECT_DATE] ---table changed----55
								  --[EVENT_DATE]                     = ISD.[EVENT_DATE] ,---56
								  --[EVENT_DATE_TYPE]                 =ISD.[EVENT_DATE_TYPE]----57
								  FROM   rdb.dbo.TMP_INV_SUMM_DATAMART ISD
				                  Where ISD.[INVESTIGATION_KEY]  = [dbo].[INV_SUMM_DATAMART].INVESTIGATION_KEY
				                  ;


					            SELECT @ROWCOUNT_NO = @@ROWCOUNT;

					          INSERT INTO RDB.[DBO].[JOB_FLOW_LOG] 
									(BATCH_ID,[DATAFLOW_NAME],[PACKAGE_NAME] ,[STATUS_TYPE],[STEP_NUMBER],[STEP_NAME],[ROW_COUNT])
									VALUES(@BATCH_ID,'INV_SUMM_DATAMART','RDB.INV_SUMM_DATAMART','START',@PROC_STEP_NO,@PROC_STEP_NAME,@ROWCOUNT_NO);

			COMMIT TRANSACTION;
		
		---------------------
		
			BEGIN TRANSACTION;

			  SET @Proc_Step_no = @Proc_Step_no +1 ;
		
			  SET @PROC_STEP_NAME = 'Updating Additional values in rdb.dbo.INV_SUMM_DATAMART'; 


			  
											--------------------------- ----Added since lab Specimen info was not updating----on 6/9/2021 

											--UPDATE  rdb.dbo.INV_SUMM_DATAMART
											--SET  EVENT_DATE_TYPE	  ='Specimen Collection Date of Earliest Associated Lab'
											--Where EARLIEST_SPECIMEN_COLLECT_DATE is not null
											--and LABORATORY_INFORMATION is Not null
											--;

											--------added 6/15/2021
											--UPDATE  rdb.dbo.INV_SUMM_DATAMART
											--SET   EARLIEST_SPECIMEN_COLLECT_DATE=NULL
											--WHERE LABORATORY_INFORMATION IS NULL
											--;

					
					

					      --                   UPDATE   rdb.dbo.INV_SUMM_DATAMART
											--SET  EARLIEST_SPECIMEN_COLLECT_DATE = t.SPECIMEN_COLLECTION_DT
										 --                 , [EVENT_DATE]       = t.EVENT_DATE
											--			  , EVENT_DATE_TYPE	='Specimen Collection Date of Earliest Associated Lab'
											--FROM rdb.dbo.TMP_INV_SUMM_DATAMART_LAB_DT t
											--WHERE
											--	   t.INVESTIGATION_KEY      =INV_SUMM_DATAMART.INVESTIGATION_KEY and 
											--	   t.INVESTIGATION_LOCAL_ID =INV_SUMM_DATAMART.INVESTIGATION_LOCAL_ID
											--       and   INV_SUMM_DATAMART.[EVENT_DATE] > t.SPECIMEN_COLLECTION_DT
											--		;
					


										      Delete inv from  rdb.dbo.INV_SUMM_DATAMART INV
										      Inner Join rdb.[dbo].[INVESTIGATION] I ON   I.[INVESTIGATION_KEY]=INV.INVESTIGATION_KEY
											  WHERE I.CASE_TYPE= 'I' AND I.RECORD_STATUS_CD = 'INACTIVE'
			                                  ;

             



	           SELECT @ROWCOUNT_NO = @@ROWCOUNT;

				INSERT INTO RDB.[DBO].[JOB_FLOW_LOG] 
				(BATCH_ID,[DATAFLOW_NAME],[PACKAGE_NAME] ,[STATUS_TYPE],[STEP_NUMBER],[STEP_NAME],[ROW_COUNT])
				VALUES(@BATCH_ID,'INV_SUMM_DATAMART','RDB.INV_SUMM_DATAMART','START',@PROC_STEP_NO,@PROC_STEP_NAME,@ROWCOUNT_NO);  

			COMMIT TRANSACTION;
		
		
		-------------------
			BEGIN TRANSACTION;
						SET @Proc_Step_no = @Proc_Step_no +1 ;
						SET @Proc_Step_Name = 'Inserting new record sinto INV_SUMM_DATAMART';
						


		        IF OBJECT_ID('rdb.dbo.TMP_FINAL_INV_SUMM_DATAMART', 'U') IS NOT NULL   
		          drop table    rdb.dbo.TMP_FINAL_INV_SUMM_DATAMART ;
		


			  insert into rdb.dbo.INV_SUMM_DATAMART(
				   [INVESTIGATION_KEY]
				  ,[PATIENT_KEY]
				  ,[PATIENT_LOCAL_ID]
				  ,[INVESTIGATION_LOCAL_ID]
				  ,[DISEASE]
				  ,[DISEASE_CD]
				  ,[PATIENT_FIRST_NAME]
				  ,[PATIENT_LAST_NAME]
				  ,[PATIENT_DOB]
				  ,[PATIENT_CURRENT_SEX]
				  ,[AGE_REPORTED]
				  ,[AGE_REPORTED_UNIT]
				  ,[PATIENT_STREET_ADDRESS_1]
				  ,[PATIENT_STREET_ADDRESS_2]
				  ,[PATIENT_CITY]
				  ,[PATIENT_STATE]
				  ,[PATIENT_ZIP]
				  ,[PATIENT_COUNTY]
				  ,[PATIENT_ETHNICITY]
				  ,[RACE_CALCULATED]
				  ,[RACE_CALC_DETAILS]
				  ,[INVESTIGATION_STATUS]
				  ,[EARLIEST_RPT_TO_CNTY_DT]
				  ,[EARLIEST_RPT_TO_STATE_DT]
				  ,[DIAGNOSIS_DATE]
				  ,[ILLNESS_ONSET_DATE]
				  ,[CASE_STATUS]
				  ,[MMWR_WEEK]
				  ,[MMWR_YEAR]
				  ,[INVESTIGATION_CREATE_DATE]
				  ,[INVESTIGATION_CREATED_BY]
				  ,[INVESTIGATION_LAST_UPDTD_DATE]
				  ,[NOTIFICATION_STATUS]
				  ,[INVESTIGATION_LAST_UPDTD_BY]
				  ,[PROGRAM_JURISDICTION_OID]
				  --,[EVENT_DATE]
				  --,[EVENT_DATE_TYPE]
				  ,[LABORATORY_INFORMATION]
				  ,[FIRST_POSITIVE_CULTURE_DT]
				  --,[EARLIEST_SPECIMEN_COLLECT_DATE]
				  ,[PROGRAM_AREA]
				  ,[PHYSICIAN_LAST_NAME]
				  ,[PHYSICIAN_FIRST_NAME]
				  ,[NOTIFICATION_LOCAL_ID]
				  ,[NOTIFICATION_CREATE_DATE]
				  ,[NOTIFICATION_SENT_DATE]
				  ,[NOTIFICATION_SUBMITTER]
				  ,[NOTIFICATION_LAST_UPDATED_DATE]
				  ,[NOTIFICATION_LAST_UPDATED_USER]
				  ,[INV_RPT_DT]
				  ,[INV_START_DT]
				  ,[CONFIRMATION_DT]
				  ,[CONFIRMATION_METHOD]
				  ,[HSPTL_ADMISSION_DT]
				  ,[CURR_PROCESS_STATE]
				  ,[PATIENT_COUNTY_CODE]
				  ,[JURISDICTION_NM]
				  )
			  SELECT distinct [INVESTIGATION_KEY]
				  ,[PATIENT_KEY]
				  ,[PATIENT_LOCAL_ID]
				  ,[INVESTIGATION_LOCAL_ID]
				  ,substring([DISEASE],1,50)
				  ,[DISEASE_CD]
				  ,[PATIENT_FIRST_NAME]
				  ,[PATIENT_LAST_NAME]
				  ,[PATIENT_DOB]
				  ,[PATIENT_CURRENT_SEX]
				  ,[AGE_REPORTED]
				  ,[AGE_REPORTED_UNIT]
				  ,[PATIENT_STREET_ADDRESS_1]
				  ,[PATIENT_STREET_ADDRESS_2]
				  ,[PATIENT_CITY]
				  ,[PATIENT_STATE]
				  ,[PATIENT_ZIP]
				  ,[PATIENT_COUNTY]
				  ,[PATIENT_ETHNICITY]
				  ,[RACE_CALCULATED]
				  ,[RACE_CALC_DETAILS]
				  ,[INVESTIGATION_STATUS]
				  ,[EARLIEST_RPT_TO_CNTY_DT]
				  ,[EARLIEST_RPT_TO_STATE_DT]
				  ,[DIAGNOSIS_DATE]
				  ,[ILLNESS_ONSET_DATE]
				  ,[CASE_STATUS]
				  ,[MMWR_WEEK]
				  ,[MMWR_YEAR]
				  ,[INVESTIGATION_CREATE_DATE]
				  ,[INVESTIGATION_CREATED_BY]
				  ,[INVESTIGATION_LAST_UPDTD_DATE]
				  ,[NOTIFICATION_STATUS]
				  ,[INVESTIGATION_LAST_UPDTD_BY]
				  ,[PROGRAM_JURISDICTION_OID]
				  --,[EVENT_DATE]
				  --,[EVENT_DATE_TYPE]
				  ,[LABORATORY_INFORMATION]
				  ,[FIRST_POSITIVE_CULTURE_DT]
				  --,[EARLIEST_SPECIMEN_COLLECT_DATE]
				  ,[PROGRAM_AREA]
				  ,[PHYSICIAN_LAST_NAME]
				  ,[PHYSICIAN_FIRST_NAME]
				  ,[NOTIFICATION_LOCAL_ID]
				  ,[NOTIFICATION_CREATE_DATE]
				  ,[NOTIFICATION_SENT_DATE]
				  ,[NOTIFICATION_SUBMITTER]
				  ,[NOTIFICATION_LAST_UPDATED_DATE]
				  ,[NOTIFICATION_LAST_UPDATED_USER]
				  ,[INV_RPT_DT]
				  ,[INV_START_DT]
				  ,[CONFIRMATION_DT]
				  ,[CONFIRMATION_METHOD]
				  ,[HSPTL_ADMISSION_DT]
				  ,[CURR_PROCESS_STATE]
				  ,[PATIENT_COUNTY_CODE]
				  ,[JURISDICTION_NM]
			 FROM rdb.dbo.TMP_INV_SUMM_DATAMART T
			 WHERE NOT EXISTS
				(
				  SELECT * 
			       FROM rdb.dbo.INV_SUMM_DATAMART with (nolock)
				   WHERE INVESTIGATION_KEY = T.INVESTIGATION_KEY
				)
				;
			
			



	           SELECT @ROWCOUNT_NO = @@ROWCOUNT;

				INSERT INTO RDB.[DBO].[JOB_FLOW_LOG] 
				(BATCH_ID,[DATAFLOW_NAME],[PACKAGE_NAME] ,[STATUS_TYPE],[STEP_NUMBER],[STEP_NAME],[ROW_COUNT])
				VALUES(@BATCH_ID,'INV_SUMM_DATAMART','RDB.INV_SUMM_DATAMART','START',@PROC_STEP_NO,@PROC_STEP_NAME,@ROWCOUNT_NO);  

			COMMIT TRANSACTION;
		

		
			BEGIN TRANSACTION;

			  SET @Proc_Step_no = @Proc_Step_no +1 ;
		
			  SET @PROC_STEP_NAME = 'Updating EVENT DATE AND TYPE in rdb.dbo.INV_SUMM_DATAMART'; 


			   	  		IF OBJECT_ID('rdb.dbo.TMP_CASE_LAB_DATAMART_MODIFIED', 'U')  is  NULL   
					   SELECT DISTINCT C.INVESTIGATION_KEY ,
						    C.EARLIEST_SPECIMEN_COLLECT_DATE as EARLIEST_SPECIMEN_COLLECTION_DT 
						  INTO  rdb.dbo.TMP_CASE_LAB_DATAMART_MODIFIED
						  from  rdb.dbo.[CASE_LAB_DATAMART] C with (nolock) 
						  ;
			   
		
					update ISD
					set ISD.EVENT_DATE = CLD.EVENT_DATE, 
						ISD.EVENT_DATE_TYPE = CLD.EVENT_DATE_TYPE,
						ISD.Earliest_specimen_collect_date = cld.Earliest_specimen_collect_date,
						ISD.LABORATORY_INFORMATION  = cld.LABORATORY_INFORMATION
					FROM rdb.dbo.INV_SUMM_DATAMART ISD 
									LEFT OUTER JOIN rdb.[dbo].[CASE_LAB_DATAMART]  CLD  with (nolock) ON 	ISD.INVESTIGATION_KEY=CLD.INVESTIGATION_KEY
									 JOIN rdb.dbo.TMP_CASE_LAB_DATAMART_MODIFIED TCLDM with (nolock) ON ISD.INVESTIGATION_KEY=TCLDM.INVESTIGATION_KEY 
									;



	           SELECT @ROWCOUNT_NO = @@ROWCOUNT;

				INSERT INTO RDB.[DBO].[JOB_FLOW_LOG] 
				(BATCH_ID,[DATAFLOW_NAME],[PACKAGE_NAME] ,[STATUS_TYPE],[STEP_NUMBER],[STEP_NAME],[ROW_COUNT])
				VALUES(@BATCH_ID,'INV_SUMM_DATAMART','RDB.INV_SUMM_DATAMART','START',@PROC_STEP_NO,@PROC_STEP_NAME,@ROWCOUNT_NO);  

			COMMIT TRANSACTION;
		
		
		-------------------
		
		 --VS
		/*
			BEGIN TRANSACTION;

			  SET @Proc_Step_no =  @Proc_Step_no +1  ;
		
			  SET @PROC_STEP_NAME = 'Creating TEMP_CASECNT'; 

		

   
				   IF OBJECT_ID('RDB.DBO.TEMP_CASECNT') IS NOT NULL
							DROP TABLE RDB.DBO.TEMP_CASECNT;

						SELECT top 1000  AR1.last_chg_time,
						AR2.TARGET_ACT_UID AS PUBLIC_HEALTH_CASE_UID
							,AR2.SOURCE_ACT_UID AS SUM_REPORT_FORM_UID
							,AR1.TARGET_ACT_UID AS AR1_SUM_REPORT_FORM_UID
							,
							/*--SUMMARY_REPORT_FORM OBS_UID*/
							AR1.SOURCE_ACT_UID AS AR1_SUM107_UID
							,
							/*--SUM107 OBS_UID*/
							OB1.OBSERVATION_UID AS OB1_SUM107_UID
							,OB1.CD AS OB1_CD
							,OB2.OBSERVATION_UID AS OB2_SUM_REPORT_FORM_UID
							,OB2.CD AS OB2_CD
							,OVN.NUMERIC_VALUE_1 AS GROUP_CASE_CNT
							,AR1.TYPE_CD AS AR1_TYPE_CD
							,AR1.SOURCE_CLASS_CD AS AR1_SOURCE_CLASS_CD
							,AR1.TARGET_CLASS_CD AS AR1_TARGET_CLASS_CD
							,AR2.TYPE_CD AS AR2_TYPE_CD
							,AR2.SOURCE_CLASS_CD AS AR2_SOURCE_CLASS_CD
							,AR2.TARGET_CLASS_CD AS AR2_TARGET_CLASS_CD
						INTO RDB.DBO.TEMP_CASECNT
						FROM NBS_ODSE.DBO.ACT_RELATIONSHIP AS AR1 WITH (NOLOCK)
							,NBS_ODSE.DBO.OBSERVATION AS OB1 WITH (NOLOCK)
							,NBS_ODSE.DBO.OBSERVATION AS OB2 WITH (NOLOCK)
							,NBS_ODSE.DBO.OBS_VALUE_NUMERIC AS OVN WITH (NOLOCK)
							,NBS_ODSE.DBO.ACT_RELATIONSHIP AS AR2 WITH (NOLOCK)
						WHERE AR1.SOURCE_ACT_UID = OB1.OBSERVATION_UID
							AND AR1.TARGET_ACT_UID = OB2.OBSERVATION_UID
							AND AR1.TYPE_CD = 'SUMMARYFRMQ'
							AND OB1.CD = 'SUM107'
							AND OB2.CD = 'SUMMARY_REPORT_FORM'
							AND OB1.OBSERVATION_UID = OVN.OBSERVATION_UID
							AND OB2.OBSERVATION_UID = AR2.SOURCE_ACT_UID
							AND AR2.TYPE_CD = 'SUMMARYFORM'
							AND (
							(AR1.[last_chg_time] >= @batch_start_time 
							AND AR1.[last_chg_time] <  @batch_end_time )
							 OR 
							AR1.TARGET_ACT_UID IN (SELECT   CASE_UID FROM rdb..TMP_CASE_LAB_DATAMART_MODIFIED tcl with ( nolock) , rdb..investigation inv  with ( nolock) 
													where tcl.investigation_key = inv.INVESTIGATION_KEY and case_uid is not null  group by case_uid)
						)	

					;
   
   

	           SELECT @ROWCOUNT_NO = @@ROWCOUNT;

				INSERT INTO RDB.[DBO].[JOB_FLOW_LOG] 
				(BATCH_ID,[DATAFLOW_NAME],[PACKAGE_NAME] ,[STATUS_TYPE],[STEP_NUMBER],[STEP_NAME],[ROW_COUNT])
				VALUES(@BATCH_ID,'INV_SUMM_DATAMART','RDB.INV_SUMM_DATAMART','START',@PROC_STEP_NO,@PROC_STEP_NAME,@ROWCOUNT_NO);  

			COMMIT TRANSACTION;
		*/
		
		
			BEGIN TRANSACTION;

			  SET @Proc_Step_no =  @Proc_Step_no +1  ;
		
			  SET @PROC_STEP_NAME = 'Creating TEMP_INV_SUMM_NOTIFICATION'; 

		
		               select @batch_start_time,@batch_end_time;

	   
					   IF OBJECT_ID('RDB.DBO.TEMP_INV_SUMM_NOTIFICATION') IS NOT NULL
							DROP TABLE RDB.DBO.TEMP_INV_SUMM_NOTIFICATION;

							--new stag testing changes 02012024
							IF OBJECT_ID('RDB.DBO.TMP_CASE_LAB_DATAMART_MODIFIED_output') IS NOT NULL
							DROP TABLE RDB.DBO.TMP_CASE_LAB_DATAMART_MODIFIED_output;

							SELECT distinct CASE_UID 
							INTO	RDB.DBO.TMP_CASE_LAB_DATAMART_MODIFIED_OUTPUT
							FROM RDB.DBO.TMP_CASE_LAB_DATAMART_MODIFIED TCL WITH ( NOLOCK) , 
							     RDB.dbo.INVESTIGATION INV  WITH ( NOLOCK) 
							WHERE TCL.INVESTIGATION_KEY = INV.INVESTIGATION_KEY 
							 GROUP BY CASE_UID
							;

							--INDEX on temp
							CREATE  NONCLUSTERED INDEX  idx_tlcd_caseuid  ON dbo.TMP_CASE_LAB_DATAMART_MODIFIED_OUTPUT (CASE_UID); 
 

 /*                	INTO RDB.DBO.TEMP_INV_SUMM_NOTIFICATION
							FROM NBS_ODSE.DBO.ACT_RELATIONSHIP AR WITH (NOLOCK)
									INNER JOIN NBS_ODSE.DBO.NOTIFICATION_HIST NF WITH (NOLOCK) ON AR.SOURCE_ACT_UID = NF.NOTIFICATION_UID
									left join rdb.dbo.TMP_CASE_LAB_DATAMART_MODIFIED_output tcld on AR.TARGET_ACT_UID  = tlcd.case_uid
							WHERE	 
									SOURCE_CLASS_CD = 'NOTF'
								AND TARGET_CLASS_CD = 'CASE'
								AND NF.CD='NOTF'
								AND (
									NF.RECORD_STATUS_CD = 'COMPLETED'
									OR NF.RECORD_STATUS_CD = 'MSG_FAIL'
									OR NF.RECORD_STATUS_CD = 'REJECTED'
									OR NF.RECORD_STATUS_CD = 'PEND_APPR'
									OR NF.RECORD_STATUS_CD = 'APPROVED'
									)
								AND (
								(NF.[last_chg_time]    >= @batch_start_time	AND NF.[last_chg_time] <  @batch_end_time ) 
								OR 
								( tlcd.case_uid is not null))
							)
			*/

							SELECT  DISTINCT 
									TARGET_ACT_UID AS PUBLIC_HEALTH_CASE_UID
								,TARGET_CLASS_CD
								,SOURCE_ACT_UID
								,SOURCE_CLASS_CD
								,NF.VERSION_CTRL_NBR
								,NF.ADD_TIME
								,NF.ADD_USER_ID
								,NF.RPT_SENT_TIME
								,NF.RECORD_STATUS_CD
								,NF.RECORD_STATUS_TIME
								,NF.LAST_CHG_TIME
								,NF.LAST_CHG_USER_ID
								,'Y' AS HIST_IND
								, NF.txt 
								,CAST(NULL AS INT) AS NOTIFSENTCOUNT
								,CAST(NULL AS INT) AS NOTIFREJECTEDCOUNT
								,CAST(NULL AS INT) AS NOTIFCREATEDCOUNT
								,CAST(NULL AS INT) AS X1
								,CAST(NULL AS INT) AS X2
								,CAST(NULL AS DATETIME) AS FIRSTNOTIFICATIONSENDDATE
								,CAST(NULL AS DATETIME) AS NOTIFICATIONDATE
								--,getdate() as test_data_created_date
							INTO RDB.DBO.TEMP_INV_SUMM_NOTIFICATION
							FROM NBS_ODSE.DBO.ACT_RELATIONSHIP AR WITH (NOLOCK)
									INNER JOIN NBS_ODSE.DBO.NOTIFICATION_HIST NF WITH (NOLOCK) ON AR.SOURCE_ACT_UID = NF.NOTIFICATION_UID
							WHERE	 
									SOURCE_CLASS_CD = 'NOTF'
								AND TARGET_CLASS_CD = 'CASE'
								AND NF.CD='NOTF'
								AND (
									NF.RECORD_STATUS_CD = 'COMPLETED'
									OR NF.RECORD_STATUS_CD = 'MSG_FAIL'
									OR NF.RECORD_STATUS_CD = 'REJECTED'
									OR NF.RECORD_STATUS_CD = 'PEND_APPR'
									OR NF.RECORD_STATUS_CD = 'APPROVED'
									)
								AND (
								(NF.[last_chg_time]    >= @batch_start_time	AND NF.[last_chg_time] <  @batch_end_time ) 
								OR 
								(AR.TARGET_ACT_UID IN (SELECT CASE_UID FROM rdb.dbo.TMP_CASE_LAB_DATAMART_MODIFIED_output))
							)
		
							UNION
		
							SELECT  TARGET_ACT_UID
								,TARGET_CLASS_CD
								,SOURCE_ACT_UID
								,SOURCE_CLASS_CD
								,NF.VERSION_CTRL_NBR
								,NF.ADD_TIME
								,NF.ADD_USER_ID
								,NF.RPT_SENT_TIME
								,NF.RECORD_STATUS_CD
								,NF.RECORD_STATUS_TIME
								,NF.LAST_CHG_TIME
								,NF.LAST_CHG_USER_ID
								,'N' AS HIST_IND
								, NULL AS TXT
								,CAST(NULL AS INT) AS NOTIFSENTCOUNT
								,CAST(NULL AS INT) AS NOTIFREJECTEDCOUNT
								,CAST(NULL AS INT) AS NOTIFCREATEDCOUNT
								,CAST(NULL AS INT) AS X1
								,CAST(NULL AS INT) AS X2
								,CAST(NULL AS DATETIME) AS FIRSTNOTIFICATIONSENDDATE
								,CAST(NULL AS DATETIME) AS NOTIFICATIONDATE
							--	,getdate() as test_data_created_date
							FROM NBS_ODSE.DBO.ACT_RELATIONSHIP AR WITH (NOLOCK)
								,NBS_ODSE.DBO.NOTIFICATION NF WITH (NOLOCK)
							WHERE AR.SOURCE_ACT_UID = NF.NOTIFICATION_UID
								AND SOURCE_CLASS_CD = 'NOTF'
								AND TARGET_CLASS_CD = 'CASE'
								AND NF.CD='NOTF'
								AND (
									NF.RECORD_STATUS_CD = 'COMPLETED'
									OR NF.RECORD_STATUS_CD = 'MSG_FAIL'
									OR NF.RECORD_STATUS_CD = 'REJECTED'
									OR NF.RECORD_STATUS_CD = 'PEND_APPR'
									OR NF.RECORD_STATUS_CD = 'APPROVED'
									)
								AND (
								(NF.[last_chg_time] >=  @batch_start_time	  AND NF.[last_chg_time] <  @batch_end_time )
								OR
								AR.TARGET_ACT_UID IN (SELECT CASE_UID FROM rdb.dbo.TMP_CASE_LAB_DATAMART_MODIFIED_output)
			
								)
								;

							--new stag testing changes 02012024


	           SELECT @ROWCOUNT_NO = @@ROWCOUNT;

				INSERT INTO RDB.[DBO].[JOB_FLOW_LOG] 
				(BATCH_ID,[DATAFLOW_NAME],[PACKAGE_NAME] ,[STATUS_TYPE],[STEP_NUMBER],[STEP_NAME],[ROW_COUNT])
				VALUES(@BATCH_ID,'INV_SUMM_DATAMART','RDB.INV_SUMM_DATAMART','START',@PROC_STEP_NO,@PROC_STEP_NAME,@ROWCOUNT_NO);  

			COMMIT TRANSACTION;
		
		
		
			BEGIN TRANSACTION;

			  SET @Proc_Step_no =  @Proc_Step_no +1  ;
		
			  SET @PROC_STEP_NAME = 'CREATING RDB.DBO.TEMP_PHCFACT'; 

		

				
								IF OBJECT_ID('RDB.DBO.TEMP_PHCFACT') IS NOT NULL
							DROP TABLE RDB.DBO.TEMP_PHCFACT;

						SELECT 
							TARGET_CLASS_CD
							,TEMP_INV_SUMM_NOTIFICATION.SOURCE_ACT_UID
							,TEMP_INV_SUMM_NOTIFICATION.SOURCE_CLASS_CD
							,VERSION_CTRL_NBR
							,ADD_TIME
							,ADD_USER_ID
							,RPT_SENT_TIME
							,RECORD_STATUS_CD
							,RECORD_STATUS_TIME
							,TEMP_INV_SUMM_NOTIFICATION.LAST_CHG_TIME as LAST_CHG_TIME1
							,LAST_CHG_USER_ID
							,HIST_IND
							,NOTIFSENTCOUNT
							,NOTIFCREATEDCOUNT
							,FIRSTNOTIFICATIONSENDDATE
							,NOTIFICATIONDATE
						INTO RDB.DBO.TEMP_PHCFACT
						FROM  RDB.DBO.TEMP_INV_SUMM_NOTIFICATION WITH (NOLOCK) 
						 ;



	           SELECT @ROWCOUNT_NO = @@ROWCOUNT;

				INSERT INTO RDB.[DBO].[JOB_FLOW_LOG] 
				(BATCH_ID,[DATAFLOW_NAME],[PACKAGE_NAME] ,[STATUS_TYPE],[STEP_NUMBER],[STEP_NAME],[ROW_COUNT])
				VALUES(@BATCH_ID,'INV_SUMM_DATAMART','RDB.INV_SUMM_DATAMART','START',@PROC_STEP_NO,@PROC_STEP_NAME,@ROWCOUNT_NO);  

			COMMIT TRANSACTION;
		
		
		
			BEGIN TRANSACTION;

			  SET @Proc_Step_no =  @Proc_Step_no +1  ;
		
			  SET @PROC_STEP_NAME = 'Creating RDB.DBO.TEMP_MIN_MAX_NOTIFICATION'; 

		


					   IF OBJECT_ID('RDB.DBO.TEMP_MIN_MAX_NOTIFICATION') IS NOT NULL
							DROP TABLE RDB.DBO.TEMP_MIN_MAX_NOTIFICATION;

						SELECT DISTINCT MIN(CASE 
									WHEN VERSION_CTRL_NBR = 1
										THEN RECORD_STATUS_CD
									END) AS FIRSTNOTIFICATIONSTATUS
							,
			
							SUM(CASE 
									WHEN RECORD_STATUS_CD = 'REJECTED'
										THEN 1
									ELSE 0
									END) NOTIFREJECTEDCOUNT
							,SUM(CASE 
									WHEN RECORD_STATUS_CD = 'APPROVED'
										OR RECORD_STATUS_CD = 'PEND_APPR'
										THEN 1
									WHEN RECORD_STATUS_CD = 'REJECTED'
										THEN -1
									ELSE 0
									END) NOTIFCREATEDCOUNT
							,SUM(CASE 
									WHEN RECORD_STATUS_CD = 'COMPLETED'
										THEN 1
									ELSE 0
									END) NOTIFSENTCOUNT
							,MIN(CASE 
									WHEN RECORD_STATUS_CD = 'COMPLETED'
										THEN RPT_SENT_TIME
									END) AS FIRSTNOTIFICATIONSENDDATE
							,
							SUM(CASE 
									WHEN RECORD_STATUS_CD = 'PEND_APPR'
										THEN 1
									ELSE 0
									END) NOTIFCREATEDPENDINGSCOUNT
							,MAX(CASE 
									WHEN RECORD_STATUS_CD = 'APPROVED'
										OR RECORD_STATUS_CD = 'PEND_APPR'
										THEN LAST_CHG_TIME
									END) AS LASTNOTIFICATIONDATE
							,
							--DONE?
							MAX(CASE 
									WHEN RECORD_STATUS_CD = 'COMPLETED'
										THEN RPT_SENT_TIME
									END) AS LASTNOTIFICATIONSENDDATE
							,
							--DONE?
							MIN(ADD_TIME) AS FIRSTNOTIFICATIONDATE
							,
							--DONE
							MIN(ADD_USER_ID) AS FIRSTNOTIFICATIONSUBMITTEDBY
							,
							--DONE
							MIN(ADD_USER_ID) AS LASTNOTIFICATIONSUBMITTEDBY
							--DONE
							--MIN(CASE WHEN RECORD_STATUS_CD='COMPLETED' THEN  LAST_CHG_USER_ID END) AS FIRSTNOTIFICATIONSUBMITTEDBY,
							,MIN(CASE 
									WHEN RECORD_STATUS_CD = 'COMPLETED'
										AND RPT_SENT_TIME IS NOT NULL
										THEN RPT_SENT_TIME
									END) AS NOTIFICATIONDATE
							,PUBLIC_HEALTH_CASE_UID
						INTO RDB.DBO.TEMP_MIN_MAX_NOTIFICATION
						FROM RDB.DBO.TEMP_INV_SUMM_NOTIFICATION WITH (NOLOCK)
						GROUP BY PUBLIC_HEALTH_CASE_UID;



	           SELECT @ROWCOUNT_NO = @@ROWCOUNT;

				INSERT INTO RDB.[DBO].[JOB_FLOW_LOG] 
				(BATCH_ID,[DATAFLOW_NAME],[PACKAGE_NAME] ,[STATUS_TYPE],[STEP_NUMBER],[STEP_NAME],[ROW_COUNT])
				VALUES(@BATCH_ID,'INV_SUMM_DATAMART','RDB.INV_SUMM_DATAMART','START',@PROC_STEP_NO,@PROC_STEP_NAME,@ROWCOUNT_NO);  

			COMMIT TRANSACTION;
		
		
		
			BEGIN TRANSACTION;

			  SET @Proc_Step_no =  @Proc_Step_no +1  ;
		
			  SET @PROC_STEP_NAME = 'Creating tmp_inv_sum_nnd_info';  -- DO NOT DROP NEEDED FOR HEP_DATAMART

		
	
						IF OBJECT_ID('RDB.DBO.tmp_inv_sum_nnd_info') IS NOT NULL
							DROP TABLE RDB.DBO.tmp_inv_sum_nnd_info;

						select PUBLIC_HEALTH_CASE_UID,FIRSTNOTIFICATIONSENDDATE,INVESTIGATION_KEY
							into rdb..tmp_inv_sum_nnd_info
						FROM rdb..TEMP_MIN_MAX_NOTIFICATION tcl with ( nolock) , rdb..investigation inv  with ( nolock) 
						   where tcl.PUBLIC_HEALTH_CASE_UID = inv.CASE_UID
						   and FIRSTNOTIFICATIONSENDDATE is not null 
						   ;


	

	           SELECT @ROWCOUNT_NO = @@ROWCOUNT;

				INSERT INTO RDB.[DBO].[JOB_FLOW_LOG] 
				(BATCH_ID,[DATAFLOW_NAME],[PACKAGE_NAME] ,[STATUS_TYPE],[STEP_NUMBER],[STEP_NAME],[ROW_COUNT])
				VALUES(@BATCH_ID,'INV_SUMM_DATAMART','RDB.INV_SUMM_DATAMART','START',@PROC_STEP_NO,@PROC_STEP_NAME,@ROWCOUNT_NO);  

			COMMIT TRANSACTION;
		
		
		
			BEGIN TRANSACTION;

			  SET @Proc_Step_no =  @Proc_Step_no +1  ;
		
			  SET @PROC_STEP_NAME = 'Updating INIT_NND_NOTF_DT in INV_SUMM_DATAMART'; 

		
	
				update ISD
					set ISD.INIT_NND_NOT_DT = NND.FIRSTNOTIFICATIONSENDDATE
					FROM rdb.dbo.INV_SUMM_DATAMART ISD 
						 JOIN rdb.dbo.tmp_inv_sum_nnd_info NND with (nolock) ON ISD.INVESTIGATION_KEY=NND.INVESTIGATION_KEY 
				where INIT_NND_NOT_DT is null
        		;

	           SELECT @ROWCOUNT_NO = @@ROWCOUNT;

				INSERT INTO RDB.[DBO].[JOB_FLOW_LOG] 
				(BATCH_ID,[DATAFLOW_NAME],[PACKAGE_NAME] ,[STATUS_TYPE],[STEP_NUMBER],[STEP_NAME],[ROW_COUNT])
				VALUES(@BATCH_ID,'INV_SUMM_DATAMART','RDB.INV_SUMM_DATAMART','START',@PROC_STEP_NO,@PROC_STEP_NAME,@ROWCOUNT_NO);  

			COMMIT TRANSACTION;
			




			BEGIN TRANSACTION;
						SET @Proc_Step_no = @Proc_Step_no +1 ;
						SET @Proc_Step_Name = 'Deleting TMP Tables ';
						

			
				IF OBJECT_ID('[dbo].[TMP_UPDATED_INV_WITH_NOTIF]', 'U') IS NOT NULL 
				DROP TABLE rdb.[dbo].[TMP_UPDATED_INV_WITH_NOTIF]
				;

				IF OBJECT_ID('[dbo].[TMP_PATIENT_LOCATION_KEYS_INIT]', 'U') IS NOT NULL 
				DROP TABLE rdb.[dbo].[TMP_PATIENT_LOCATION_KEYS_INIT]
				;

				IF OBJECT_ID('[dbo].[TMP_CONFIRMATION_METHOD_BASE]', 'U') IS NOT NULL 
				DROP TABLE rdb.[dbo].[TMP_CONFIRMATION_METHOD_BASE]
				;

				IF OBJECT_ID('[dbo].[TMP_CONFIRMATION_METHOD_PIVOT]', 'U') IS NOT NULL 
				DROP TABLE rdb.[dbo].[TMP_CONFIRMATION_METHOD_PIVOT]
				;

				IF OBJECT_ID('[dbo].[tmp_PATIENT_LOCATION_KEYS]', 'U') IS NOT NULL 
				DROP TABLE rdb.[dbo].[tmp_PATIENT_LOCATION_KEYS]
				;

				IF OBJECT_ID('[dbo].[tmp_PATIENT_INFO]', 'U') IS NOT NULL 
				DROP TABLE rdb.[dbo].[tmp_PATIENT_INFO]
				;

				IF OBJECT_ID('[dbo].[tmp_PHYSICIAN_INFO]', 'U') IS NOT NULL 
				DROP TABLE rdb.[dbo].[tmp_PHYSICIAN_INFO]
				;

				IF OBJECT_ID('[dbo].[tmp_PATIENT_DETAILS]', 'U') IS NOT NULL 
				DROP TABLE rdb.[dbo].[tmp_PATIENT_DETAILS]
				;

				IF OBJECT_ID('[dbo].[TMP_S_INV_SUMM_DATAMART_INIT]', 'U') IS NOT NULL 
				DROP TABLE rdb.[dbo].[TMP_S_INV_SUMM_DATAMART_INIT]
				;

				IF OBJECT_ID('[dbo].[TMP_InvLab]', 'U') IS NOT NULL 
				DROP TABLE rdb.[dbo].[TMP_InvLab]
				;

				IF OBJECT_ID('[dbo].[TMP_Lab]', 'U') IS NOT NULL 
				DROP TABLE rdb.[dbo].[TMP_Lab]
				;

				IF OBJECT_ID('[dbo].[TMP_BothTable]', 'U') IS NOT NULL 
				DROP TABLE rdb.[dbo].[TMP_BothTable]
				;

				IF OBJECT_ID('[dbo].[TMP_Inv2Labs]', 'U') IS NOT NULL 
				DROP TABLE rdb.[dbo].[TMP_Inv2Labs]
				;

				IF OBJECT_ID('[dbo].[TMP_SPECIMEN_COLLECTION]', 'U') IS NOT NULL 
				DROP TABLE rdb.[dbo].[TMP_SPECIMEN_COLLECTION]
				;



				IF OBJECT_ID('[dbo].[TMP_INV_SUMM_DATAMART]', 'U') IS NOT NULL 
				DROP TABLE rdb.[dbo].[TMP_INV_SUMM_DATAMART]
				;

									  
		        IF OBJECT_ID('rdb.dbo.TMP_INV_SUMM_DATAMART_LAB_DT', 'U') IS NOT NULL   
		          drop table    rdb.dbo.TMP_INV_SUMM_DATAMART_LAB_DT ;
		
					  
		        IF OBJECT_ID('rdb.dbo.TEMP_INV_SUMM_NOTIFICATION', 'U') IS NOT NULL   
		          drop table    rdb.dbo.TEMP_INV_SUMM_NOTIFICATION ;
		
					  
		        IF OBJECT_ID('rdb.dbo.TEMP_MIN_MAX_NOTIFICATION', 'U') IS NOT NULL   
		          drop table rdb.[dbo].TEMP_MIN_MAX_NOTIFICATION
						  
		        IF OBJECT_ID('rdb.dbo.TEMP_PHCFACT', 'U') IS NOT NULL   
		          drop table    rdb.dbo.TEMP_PHCFACT ;

				IF OBJECT_ID('rdb.dbo.TMP_CLDM_CASE_LAB_DATAMART_FINAL', 'U') IS NOT NULL  
								 drop table  rdb.dbo.TMP_CLDM_CASE_LAB_DATAMART_FINAL ;
				
				IF OBJECT_ID('RDB.DBO.TMP_CASE_LAB_DATAMART_MODIFIED_output') IS NOT NULL
				DROP TABLE RDB.DBO.TMP_CASE_LAB_DATAMART_MODIFIED_output;

		COMMIT TRANSACTION;
		
----------------------------------------------------------------------------
        BEGIN TRANSACTION ;
	
				SET @Proc_Step_no =  @Proc_Step_no + 1 ;
				SET @Proc_Step_Name = 'SP_COMPLETE'; 
				SELECT @ROWCOUNT_NO = 0;


				INSERT INTO rdb.[dbo].[job_flow_log] (
						batch_id
						,[Dataflow_Name]
					   ,[package_Name]
						,[Status_Type] 
					   ,[step_number]
					   ,[step_name]
					   ,[row_count]
					   )
					   VALUES
					   (
					   @batch_id,
					   'INV_SUMM_DATAMART'
					   ,'RDB.INV_SUMM_DATAMART'
					   ,'COMPLETE'
					   ,@Proc_Step_no
					   ,@Proc_Step_name
					   ,@RowCount_no
					   );
			  
	
	    COMMIT TRANSACTION;

    END TRY
            BEGIN CATCH
						IF @@TRANCOUNT > 0
						BEGIN
							ROLLBACK TRANSACTION;
						END;
						DECLARE @ErrorNumber int= ERROR_NUMBER();
						DECLARE @ErrorLine int= ERROR_LINE();
						DECLARE @ErrorMessage nvarchar(4000)= ERROR_MESSAGE();
						DECLARE @ErrorSeverity int= ERROR_SEVERITY();
						DECLARE @ErrorState int= ERROR_STATE();
						INSERT INTO rdb.[dbo].[job_flow_log]( batch_id, [Dataflow_Name], [package_Name], [Status_Type], [step_number], [step_name], [Error_Description], [row_count] )
						VALUES( @Batch_id, 'INV_SUMM_DATAMART', 'RDB.INV_SUMM_DATAMART', 'ERROR', @Proc_Step_no, 'ERROR - '+@Proc_Step_name, 'Step -'+CAST(@Proc_Step_no AS varchar(3))+' -'+CAST(@ErrorMessage AS varchar(500)), 0 );
						RETURN -1;
	        END CATCH;
END;
GO

