USE [RDB]
GO

/****** Object:  StoredProcedure [dbo].[SP_FIX_MORBIDITY_CONDITION]    Script Date: 11/20/2023 1:44:22 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER OFF
GO



CREATE OR ALTER PROCEDURE [dbo].[SP_FIX_MORBIDITY_CONDITION]
	  
AS
BEGIN
	BEGIN TRY
	print 'inside [SP_FIX_MORBIDITY_CONDITION]'
		BEGIN TRANSACTION
		BEGIN
			UPDATE
				RDB.DBO.MORBIDITY_REPORT_EVENT
			SET MORBIDITY_REPORT_EVENT.CONDITION_KEY = CONDITION.CONDITION_KEY
			FROM RDB.DBO.MORBIDITY_REPORT_EVENT
			INNER JOIN RDB.DBO.MORBIDITY_REPORT 
			ON MORBIDITY_REPORT_EVENT.MORB_RPT_KEY = MORBIDITY_REPORT.MORB_RPT_KEY
			INNER JOIN NBS_ODSE.DBO.OBSERVATION
			ON OBSERVATION.LOCAL_ID = MORBIDITY_REPORT.MORB_RPT_LOCAL_ID
			INNER JOIN RDB.DBO.CONDITION 
			ON CONDITION.CONDITION_CD =OBSERVATION.CD;

		END	
		COMMIT TRANSACTION
		print 'inside [SP_FIX_MORBIDITY_CONDITION] completed'
	END TRY

	BEGIN CATCH		
		DECLARE @ERRORNUMBER INT = ERROR_NUMBER();
		DECLARE @ERRORLINE INT = ERROR_LINE();
		DECLARE @ERRORMESSAGE NVARCHAR(4000) = ERROR_MESSAGE();
		DECLARE @ERRORSEVERITY INT = ERROR_SEVERITY();
		DECLARE @ERRORSTATE INT = ERROR_STATE();
		PRINT(CAST(@ERRORMESSAGE AS VARCHAR(500)));
	END CATCH
END;

GO


