package gov.cdc.nbs.entity.enums;

public enum IdentificationType {
    ACCOUNT_NUMBER,
    ALTERNATE_PERSON_NUMBER,
    CHIP_IDENTIFICATION_NUMBER,
    DRIVERS_LICENSE_NUMBER,
    IMMUNIZATION_REGISTRY_ID,
    MEDICAID_NUMBER,
    MEDICAL_RECORD_NUMBER,
    MEDICARE_NUMBER,
    MOTHERS_IDENTIFIER,
    NATIONAL_UNIQUE_INDIVIDUAL_IDENTIFIER,
    OTHER,
    PARTNER_SERVICES_PATIENT_NUMBER,
    PATIENT_EXTERNAL_IDENTIFIER,
    PATIENT_INTERNAL_IDENTIFIER,
    PERSON_NUMBER,
    PRISON_IDENTIFICATION_NUMBER,
    QUICK_ENTRY_CODE,
    RYAN_WHITE_IDENTIFIER,
    SOCIAL_SECURITY,
    VISA_PASSPORT,
    WIC_IDENTIFIER
}
