logging.level.org.hibernate.SQL: debug
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE

spring.graphql.graphiql.enabled: true
spring.graphql.graphiql.path: /graphiql

spring.jpa.properties.hibernate.default_schema: dbo
spring.jpa.properties.hibernate.hbm2ddl.jdbc_metadata_extraction_strategy: individually
spring.jpa.hibernate.ddl-auto: validate
spring.datasource.url: jdbc:sqlserver://localhost:1433;database=nbs_odse;encrypt=true;trustServerCertificate=true;
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.properties.hibernate.jdbc.time_zone: UTC
spring.datasource.username: sa
spring.datasource.password: fake.fake.fake.1234
spring.jpa.properties.hibernate.format_sql: true
spring.mvc.pathmatch.matching-strategy: ant_path_matcher
logging.file.path: ./log/
