package gov.cdc.nbs.support.util;

import java.util.HashMap;

public class CountryCodeUtil {
    public static HashMap<String, String> countryCodeMap = new HashMap<>();

    static {
        countryCodeMap.put("Bulgaria", "100");
        countryCodeMap.put("Myanmar", "104");
        countryCodeMap.put("Burundi", "108");
        countryCodeMap.put("Belarus", "112");
        countryCodeMap.put("Cambodia", "116");
        countryCodeMap.put("Algeria", "12");
        countryCodeMap.put("Cameroon", "120");
        countryCodeMap.put("Canada", "124");
        countryCodeMap.put("Cape Verde", "132");
        countryCodeMap.put("Cayman Islands", "136");
        countryCodeMap.put("Central African Republic", "140");
        countryCodeMap.put("Sri Lanka", "144");
        countryCodeMap.put("Chad", "148");
        countryCodeMap.put("Chile", "152");
        countryCodeMap.put("China", "156");
        countryCodeMap.put("Taiwan Province of China", "158");
        countryCodeMap.put("American Samoa", "16");
        countryCodeMap.put("Colombia", "170");
        countryCodeMap.put("Comoros", "174");
        countryCodeMap.put("Congo", "178");
        countryCodeMap.put("Democratic Republic of the Congo", "180");
        countryCodeMap.put("Cook Islands", "184");
        countryCodeMap.put("Costa Rica", "188");
        countryCodeMap.put("Croatia", "191");
        countryCodeMap.put("Cuba", "192");
        countryCodeMap.put("Cyprus", "196");
        countryCodeMap.put("Andorra", "20");
        countryCodeMap.put("Czech Republic", "203");
        countryCodeMap.put("Benin", "204");
        countryCodeMap.put("Denmark", "208");
        countryCodeMap.put("Dominica", "212");
        countryCodeMap.put("Dominican Republic", "214");
        countryCodeMap.put("Ecuador", "218");
        countryCodeMap.put("El Salvador", "222");
        countryCodeMap.put("Equatorial Guinea", "226");
        countryCodeMap.put("Ethiopia", "231");
        countryCodeMap.put("Eritrea", "232");
        countryCodeMap.put("Estonia", "233");
        countryCodeMap.put("Faeroe Islands", "234");
        countryCodeMap.put("Falkland Islands (Malvinas)", "238");
        countryCodeMap.put("Angola", "24");
        countryCodeMap.put("Fiji", "242");
        countryCodeMap.put("Finland", "246");
        countryCodeMap.put("France", "250");
        countryCodeMap.put("French Guiana", "254");
        countryCodeMap.put("French Polynesia", "258");
        countryCodeMap.put("Djibouti", "262");
        countryCodeMap.put("Gabon", "266");
        countryCodeMap.put("Georgia", "268");
        countryCodeMap.put("Gambia", "270");
        countryCodeMap.put("Occupied Palestinian Territory", "275");
        countryCodeMap.put("Germany", "276");
        countryCodeMap.put("Antigua and Barbuda", "28");
        countryCodeMap.put("Ghana", "288");
        countryCodeMap.put("Gibraltar", "292");
        countryCodeMap.put("Kiribati", "296");
        countryCodeMap.put("Greece", "300");
        countryCodeMap.put("Greenland", "304");
        countryCodeMap.put("Grenada", "308");
        countryCodeMap.put("Azerbaijan", "31");
        countryCodeMap.put("Guadeloupe", "312");
        countryCodeMap.put("Guam", "316");
        countryCodeMap.put("Argentina", "32");
        countryCodeMap.put("Guatemala", "320");
        countryCodeMap.put("Guinea", "324");
        countryCodeMap.put("Guyana", "328");
        countryCodeMap.put("Haiti", "332");
        countryCodeMap.put("Holy See", "336");
        countryCodeMap.put("Honduras", "340");
        countryCodeMap.put("Hong Kong Special Administrative Region of China", "344");
        countryCodeMap.put("Hungary", "348");
        countryCodeMap.put("Iceland", "352");
        countryCodeMap.put("India", "356");
        countryCodeMap.put("Australia", "36");
        countryCodeMap.put("Indonesia", "360");
        countryCodeMap.put("Iran (Islamic Republic of)", "364");
        countryCodeMap.put("Iraq", "368");
        countryCodeMap.put("Ireland", "372");
        countryCodeMap.put("Israel", "376");
        countryCodeMap.put("Italy", "380");
        countryCodeMap.put("\"Cote d'Ivoire\"", "384");
        countryCodeMap.put("Jamaica", "388");
        countryCodeMap.put("Japan", "392");
        countryCodeMap.put("Kazakhstan", "398");
        countryCodeMap.put("Afghanistan", "4");
        countryCodeMap.put("Austria", "40");
        countryCodeMap.put("Jordan", "400");
        countryCodeMap.put("Kenya", "404");
        countryCodeMap.put("\"Democratic People's Republic of Korea\"", "408");
        countryCodeMap.put("Republic of Korea", "410");
        countryCodeMap.put("Kuwait", "414");
        countryCodeMap.put("Kyrgyzstan", "417");
        countryCodeMap.put("\"Lao People's Democratic Republic\"", "418");
        countryCodeMap.put("Lebanon", "422");
        countryCodeMap.put("Lesotho", "426");
        countryCodeMap.put("Latvia", "428");
        countryCodeMap.put("Liberia", "430");
        countryCodeMap.put("Libyan Arab Jamahiriya", "434");
        countryCodeMap.put("Liechtenstein", "438");
        countryCodeMap.put("Bahamas", "44");
        countryCodeMap.put("Lithuania", "440");
        countryCodeMap.put("Luxembourg", "442");
        countryCodeMap.put("Macao Special Administrative Region of China", "446");
        countryCodeMap.put("Madagascar", "450");
        countryCodeMap.put("Malawi", "454");
        countryCodeMap.put("Malaysia", "458");
        countryCodeMap.put("Maldives", "462");
        countryCodeMap.put("Mali", "466");
        countryCodeMap.put("Malta", "470");
        countryCodeMap.put("Martinique", "474");
        countryCodeMap.put("Mauritania", "478");
        countryCodeMap.put("Bahrain", "48");
        countryCodeMap.put("Mauritius", "480");
        countryCodeMap.put("Mexico", "484");
        countryCodeMap.put("Monaco", "492");
        countryCodeMap.put("Mongolia", "496");
        countryCodeMap.put("Republic of Moldova", "498");
        countryCodeMap.put("Bangladesh", "50");
        countryCodeMap.put("Montserrat", "500");
        countryCodeMap.put("Morocco", "504");
        countryCodeMap.put("Mozambique", "508");
        countryCodeMap.put("Armenia", "51");
        countryCodeMap.put("Oman", "512");
        countryCodeMap.put("Namibia", "516");
        countryCodeMap.put("Barbados", "52");
        countryCodeMap.put("Nauru", "520");
        countryCodeMap.put("Nepal", "524");
        countryCodeMap.put("Netherlands", "528");
        countryCodeMap.put("Netherlands Antilles", "530");
        countryCodeMap.put("Aruba", "533");
        countryCodeMap.put("New Caledonia", "540");
        countryCodeMap.put("Vanuatu", "548");
        countryCodeMap.put("New Zealand", "554");
        countryCodeMap.put("Nicaragua", "558");
        countryCodeMap.put("Belgium", "56");
        countryCodeMap.put("Niger", "562");
        countryCodeMap.put("Nigeria", "566");
        countryCodeMap.put("Niue", "570");
        countryCodeMap.put("Norfolk Island", "574");
        countryCodeMap.put("Norway", "578");
        countryCodeMap.put("Northern Mariana Islands", "580");
        countryCodeMap.put("Micronesia, Federated States of", "583");
        countryCodeMap.put("Marshall Islands", "584");
        countryCodeMap.put("Palau", "585");
        countryCodeMap.put("Pakistan", "586");
        countryCodeMap.put("Panama", "591");
        countryCodeMap.put("Papua New Guinea", "598");
        countryCodeMap.put("Bermuda", "60");
        countryCodeMap.put("Paraguay", "600");
        countryCodeMap.put("Peru", "604");
        countryCodeMap.put("Philippines", "608");
        countryCodeMap.put("Pitcairn", "612");
        countryCodeMap.put("Poland", "616");
        countryCodeMap.put("Portugal", "620");
        countryCodeMap.put("Guinea-Bissau", "624");
        countryCodeMap.put("East Timor", "626");
        countryCodeMap.put("Puerto Rico", "630");
        countryCodeMap.put("Qatar", "634");
        countryCodeMap.put("Réunion", "638");
        countryCodeMap.put("Bhutan", "64");
        countryCodeMap.put("Romania", "642");
        countryCodeMap.put("Russian Federation", "643");
        countryCodeMap.put("Rwanda", "646");
        countryCodeMap.put("Saint Helena", "654");
        countryCodeMap.put("Saint Kitts and Nevis", "659");
        countryCodeMap.put("Anguilla", "660");
        countryCodeMap.put("Saint Lucia", "662");
        countryCodeMap.put("Saint Pierre and Miquelon", "666");
        countryCodeMap.put("Saint Vincent and the Grenadines", "670");
        countryCodeMap.put("San Marino", "674");
        countryCodeMap.put("Sao Tome and Principe", "678");
        countryCodeMap.put("Bolivia", "68");
        countryCodeMap.put("Saudi Arabia", "682");
        countryCodeMap.put("Senegal", "686");
        countryCodeMap.put("Seychelles", "690");
        countryCodeMap.put("Sierra Leone", "694");
        countryCodeMap.put("Bosnia and Herzegovina", "70");
        countryCodeMap.put("Singapore", "702");
        countryCodeMap.put("Slovakia", "703");
        countryCodeMap.put("Viet Nam", "704");
        countryCodeMap.put("Slovenia", "705");
        countryCodeMap.put("Somalia", "706");
        countryCodeMap.put("South Africa", "710");
        countryCodeMap.put("Zimbabwe", "716");
        countryCodeMap.put("Botswana", "72");
        countryCodeMap.put("Spain", "724");
        countryCodeMap.put("Western Sahara", "732");
        countryCodeMap.put("Sudan", "736");
        countryCodeMap.put("Suriname", "740");
        countryCodeMap.put("Svalbard and Jan Mayen Islands", "744");
        countryCodeMap.put("Swaziland", "748");
        countryCodeMap.put("Sweden", "752");
        countryCodeMap.put("Switzerland", "756");
        countryCodeMap.put("Brazil", "76");
        countryCodeMap.put("Syrian Arab Republic", "760");
        countryCodeMap.put("Tajikistan", "762");
        countryCodeMap.put("Thailand", "764");
        countryCodeMap.put("Togo", "768");
        countryCodeMap.put("Tokelau", "772");
        countryCodeMap.put("Tonga", "776");
        countryCodeMap.put("Trinidad and Tobago", "780");
        countryCodeMap.put("United Arab Emirates", "784");
        countryCodeMap.put("Tunisia", "788");
        countryCodeMap.put("Turkey", "792");
        countryCodeMap.put("Turkmenistan", "795");
        countryCodeMap.put("Turks and Caicos Islands", "796");
        countryCodeMap.put("Tuvalu", "798");
        countryCodeMap.put("Albania", "8");
        countryCodeMap.put("Uganda", "800");
        countryCodeMap.put("Ukraine", "804");
        countryCodeMap.put("The former Yugoslav Republic of Macedonia", "807");
        countryCodeMap.put("Egypt", "818");
        countryCodeMap.put("United Kingdom", "826");
        countryCodeMap.put("Channel Islands", "830");
        countryCodeMap.put("Isle of Man", "833");
        countryCodeMap.put("United Republic of Tanzania", "834");
        countryCodeMap.put("Belize", "84");
        countryCodeMap.put("United States", "840");
        countryCodeMap.put("United States Virgin Islands", "850");
        countryCodeMap.put("Burkina Faso", "854");
        countryCodeMap.put("Uruguay", "858");
        countryCodeMap.put("Uzbekistan", "860");
        countryCodeMap.put("Venezuela", "862");
        countryCodeMap.put("Wallis and Futuna Islands", "876");
        countryCodeMap.put("Samoa", "882");
        countryCodeMap.put("Yemen", "887");
        countryCodeMap.put("Yugoslavia", "891");
        countryCodeMap.put("Zambia", "894");
        countryCodeMap.put("Solomon Islands", "90");
        countryCodeMap.put("British Virgin Islands", "92");
        countryCodeMap.put("Brunei Darussalam", "96");
    }
}
