server:
  port: 8095
  servlet:
    context-path: /nbs/page-builder
nbs:
  datasource:
    server: localhost
  security:
    tokenSecret: ${TOKEN_SECRET}
    tokenIssuer: gov.cdc.nbs
    tokenExpirationMillis: 1800000 # 30 minutes
  wildfly:
    host: wildfly
    server: ${nbs.wildfly.host}:${nbs.wildfly.port}
    port: 7001
    url: http://${nbs.wildfly.server}
  authentication:
    paths:
      ignored:
        - /v3/api-docs/**
        - /swagger-ui/**
        - /swagger-resources/**

spring:
  profiles:
    include: oidc
  servlet.multipart.max-file-size: 10MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # swagger
  jackson:
    mapper:
      accept-case-insensitive-enums: true
  data:
    web:
      pageable:
        max-page-size: 100 # max pageable size
  jpa:
    properties:
      hibernate:
        default_schema: dbo
        format_sql: true
        jdbc:
          time_zone: UTC
        timezone:
          default_storage: NORMALIZE
  datasource:
    url: jdbc:sqlserver://${nbs.datasource.server}:1433;database=nbs_odse;encrypt=true;trustServerCertificate=true;
    username: sa
    password: ${DATABASE_PASSWORD}

springdoc:
  packages-to-scan: "gov.cdc.nbs.questionbank"

logging:
  file.name.path: ./log/
