server:
  port: 8095
  servlet:
    context-path: /nbs/page-builder
nbs:
  datasource:
    server: localhost
    port: 1433
    username: ${DATABASE_USER:sa}
    password: ${DATABASE_PASSWORD}
  security:
    tokenSecret: ${TOKEN_SECRET}
    tokenIssuer: gov.cdc.nbs
    tokenExpirationMillis: 1800000 # 30 minutes
  wildfly:
    host: wildfly
    server: ${nbs.wildfly.host}:${nbs.wildfly.port}
    port: 7001
    url: http://${nbs.wildfly.server}
  authentication:
    paths:
      ignored:
        - /v3/api-docs/**
        - /swagger-ui/**
        - /swagger-resources/**
        - /~/health
        - /~/info

spring:
  profiles:
    include: oidc
  servlet.multipart.max-file-size: 10MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # swagger
  jackson:
    mapper:
      accept-case-insensitive-enums: true
  data:
    web:
      pageable:
        max-page-size: 100 # max pageable size
  jpa:
    properties:
      hibernate:
        default_schema: dbo
        format_sql: true
        jdbc:
          time_zone: UTC
        timezone:
          default_storage: NORMALIZE
  datasource:
    url: jdbc:sqlserver://${nbs.datasource.server}:${nbs.datasource.port};database=nbs_odse;encrypt=true;trustServerCertificate=true;
    username: ${nbs.datasource.username}
    password: ${nbs.datasource.password}

springdoc:
  packages-to-scan: "gov.cdc.nbs.questionbank"

logging:
  file:
    path: ./log/

management:
  health:
    db:
      enabled: true
  endpoints:
    web:
      discovery:
        enabled: false
      exposure:
        include: health,info
      base-path: /~
    access:
      default: read_only
  endpoint:
    health:
      access: read_only
    info:
      access: read_only
