server:
  port: 8095
nbs:
  datasource:
    server: localhost
  security:
    enabled: true
    tokenSecret: qJ5+oDurrJnxfaAz6h4Eg1saP7NSeHuQQ/Yq4vh+mbi4B4QYThc/M+33VtPJ5O2A
    tokenIssuer: gov.cdc.nbs
    tokenExpirationMillis: 1800000 # 30 minutes
  max-page-size: 50

spring:
  mvc.pathmatch.matching-strategy: ant_path_matcher # swagger
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        hbm2ddl.jdbc_metadata_extraction_strategy: individually
        jdbc.time_zone: UTC
        format_sql: true
        default_schema: dbo
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:sqlserver://${nbs.datasource.server}:1433;database=nbs_odse;encrypt=true;trustServerCertificate=true;
    username: sa
    password: fake.fake.fake.1234
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      ackMode: record
    consumer:
      group-id: question-group
      enable-auto-commit: false
      auto-offset-reset: earliest

kafka:
    enabled: false

kafkadef:
  groups:
    patient: question-group
  topics:
    questionbank:
      question-created: question-created
      question-deleted: question-deleted
