nbs:
  datasource:
    server: localhost
  security:
    tokenSecret: qJ5+oDurrJnxfaAz6h4Eg1saP7NSeHuQQ/Yq4vh+mbi4B4QYThc/M+33VtPJ5O2A
    tokenIssuer: gov.cdc.nbs
    tokenExpirationMillis: 1800000 # 30 minutes
    max-page-size: 50

spring:
  graphql:
    path: /graphql
    graphiql:
      enabled: true
      path: /graphiql
  flyway:
    enabled: true
    schemas: dbo
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        hbm2ddl.jdbc_metadata_extraction_strategy: individually
        jdbc.time_zone: UTC
        format_sql: true
        default_schema: dbo
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:sqlserver://${nbs.datasource.server}:1433;database=question_bank;encrypt=true;trustServerCertificate=true;
    username: qb_admin
    password: qb_admin

