// export const ADD_INVESTIGATION_PERMISSION = 'ADD-INVESTIGATION';
// export const ADD_LAB_REPORT_PERMISSION = 'ADD-OBSERVATIONLABREPORT';
// export const ADD_MORBIDITY_REPORT_PERMISSION = 'ADD-OBSERVATIONMORBIDITYREPORT';
// export const ADD_PATIENT_PERMISSION = 'ADD-PATIENT';
// export const DELETE_INVESTIGATION_PERMISSION = 'DELETE-INVESTIGATION';
// export const DELETE_LAB_REPORT_PERMISSION = 'DELETE-OBSERVATIONLABREPORT';
// export const DELETE_MORBIDITY_REPORT_PERMISSION = 'DELETE-OBSERVATIONMORBIDITYREPORT';
// export const DELETE_PATIENT_PERMISSION = 'DELETE-PATIENT';
// export const EDIT_INVESTIGATION_PERMISSION = 'EDIT-INVESTIGATION';
// export const EDIT_LAB_REPORT_PERMISSION = 'EDIT-OBSERVATIONLABREPORT';
// // export const EDIT_MORBIDITY_REPORT_PERMISSION = 'EDIT-OBSERVATIONMORBIDITYREPORT';
// export const EDIT_PATIENT_PERMISSION = 'EDIT-PATIENT';
// export const FIND_INACTIVE_PATIENT_PERMISSION = 'FINDINACTIVE-PATIENT';
// export const FIND_PATIENT_PERMISSION = 'FIND-PATIENT';
// export const HIV_QUESTIONS_GLOBAL_PERMISSION = 'HIVQUESTIONS-GLOBAL';
// export const MERGE_INVESTIGATION_PERMISSION = 'MERGEINVESTIGATION-INVESTIGATION';
// export const VIEW_INVESTIGATION_PERMISSION = 'VIEW-INVESTIGATION';
// export const VIEW_LAB_REPORT_PERMISSION = 'VIEW-OBSERVATIONLABREPORT';
// export const VIEW_MORBIDITY_REPORT_PERMISSION = 'VIEW-OBSERVATIONMORBIDITYREPORT';
// export const VIEW_PATIENT_PERMISSION = 'VIEW-PATIENT';

export const permissions = {
    global: {
        hivQuestion: 'HIVQUESTIONS-GLOBAL'
    },
    investigation: {
        add: 'ADD-INVESTIGATION',
        delete: 'DELETE-INVESTIGATION',
        edit: 'EDIT-INVESTIGATION',
        merge: 'MERGEINVESTIGATION-INVESTIGATION',
        view: 'VIEW-INVESTIGATION'
    },
    labReport: {
        add: 'ADD-OBSERVATIONLABREPORT',
        delete: 'DELETE-OBSERVATIONLABREPORT',
        edit: 'EDIT-OBSERVATIONLABREPORT',
        view: 'VIEW-OBSERVATIONLABREPORT'
    },
    morbidityReport: {
        add: 'ADD-OBSERVATIONMORBIDITYREPORT',
        delete: 'DELETE-OBSERVATIONMORBIDITYREPORT',
        edit: 'EDIT-OBSERVATIONMORBIDITYREPORT',
        view: 'VIEW-OBSERVATIONMORBIDITYREPORT'
    },
    patient: {
        add: 'ADD-PATIENT',
        delete: 'DELETE-PATIENT',
        search: 'FIND-PATIENT',
        searchInactive: 'FINDINACTIVE-PATIENT',
        update: 'EDIT-PATIENT',
        view: 'VIEW-PATIENT'
    }
};
