const ADD_PATIENT_PERMISSION = 'ADD-PATIENT';
const ADD_LAB_REPORT_PERMISSION = 'ADD-OBSERVATIONLABREPORT';
const ADD_INVESTIGATION_PERMISSION = 'ADD-INVESTIGATION';

export { ADD_PATIENT_PERMISSION, ADD_LAB_REPORT_PERMISSION, ADD_INVESTIGATION_PERMISSION };
