%global PAR_TYPE_CD_SUBJECT;
%global PAR_TYPE_CD_REPORTER;
%global PAR_TYPE_CD_PROVIDER;
%global PAR_TYPE_CD_INVESTIGATOR;
%global PAR_TYPE_CD_SOURCE;

%let RECORD_STATUS_CD_ACTIVE='ACTIVE';
%let RECORD_STATUS_CD_INACTIVE='INACTIVE';

%let PAR_TYPE_CD_SUBJECT='SubjOfPHC';
%let PAR_TYPE_CD_REPORTER='PerAsReporterOfPHC';
%let PAR_TYPE_CD_PROVIDER='PhysicianOfPHC';
%let PAR_TYPE_CD_INVESTIGATOR='InvestgrOfPHC';
%let PAR_TYPE_CD_SOURCE='OrgAsReporterOfPHC';

%let ELP_CD_PHONE='PH';
%let ELP_USE_CD_HOME='H';
%let ELP_CLASS_CD_POSTAL='PST';
%let ELP_USE_CD_WORKPLACE='WP';
%let ELP_CLASS_CD_TELE='TELE';

%let CSN_P_ETHN_GRP='P_ETHN_GRP';
%let CSN_PHC_RPT_SRC_T='PHC_RPT_SRC_T';
%let CSN_PHC_DET_MT='PHC_DET_MT';
%let CSN_PHC_IMPRT='PHC_IMPRT';
%let CSN_P_MARITAL='P_MARITAL';
%let CSN_P_LANG='P_LANG';
%let CSN_P_EDUC_LVL='P_EDUC_LVL';

%let PHC_CASE_TYPE_CD_SUMMARY='S';
%let PNM_PERSON_NAME_SEQ=1;
%let PNM_NM_USE_CD_LEGAL='L';

%let OBS_CD_SUMMARY_ROOT='SUM107';
%let OBS_CD_SUMMARY_REPORT_FORM='Summary_Report_Form';
%let AR_TYPE_CD_SUMMARY_FORM='SummaryForm';
%let AR_TYPE_CD_SUMMARY_FORMQ='SummaryFrmQ';

%put &PAR_TYPE_CD_SUBJECT;