export enum PatientIdentificationType {
    ACCOUNT_NUMBER = 'Account Number',
    ALTERNATE_PERSON_NUMBER = 'Alternate person number',
    CHIP_IDENTIFICATION_NUMBER = 'CHIP Identification number',
    DRIVERS_LICENSE_NUMBER = "Driver's license number",
    IMMUNIZATION_REGISTRY_ID = 'Immunization Registry ID',
    MEDICAID_NUMBER = 'Medicaid number',
    MEDICAL_RECORD_NUMBER = 'Medical record number',
    MEDICARE_NUMBER = 'Medicare number',
    MOTHERS_IDENTIFIER = "Mother's identifier",
    NATIONAL_UNIQUE_INDIVIDUAL_IDENTIFIER = 'National unique individual identifier',
    OTHER = 'Other',
    PARTNER_SERVICES_PATIENT_NUMBER = 'Partner Services Patient Number',
    PATIENT_EXTERNAL_IDENTIFIER = 'Patient External Identifier',
    PATIENT_INTERNAL_IDENTIFIER = 'Patient Internal Identifier',
    PERSON_NUMBER = 'Person number',
    PRISON_IDENTIFICATION_NUMBER = 'Prison identification number',
    RYAN_WHITE_IDENTIFIER = 'Ryan White identifier',
    SOCIAL_SECURITY = 'Social Security',
    VISA_PASSPORT = 'VISA/Passport',
    WIC_IDENTIFIER = 'WIC identifier'
}
