nbs:
  ui:
    features:
      pageBuilder:
        enabled: false
        page:
          library:
            enabled: false
          management:
            create:
              enabled: false
            edit:
              enabled: false
      deduplication:
        enabled: true
    settings:
      analytics:
        host: https://us.posthog.com
