nbs:
  ui:
    features:
      address:
        autocomplete: false
        verification: false
      pageBuilder:
        enabled: false
        page:
          library:
            enabled: false
          management:
            create:
              enabled: false
            edit:
              enabled: false
      search:
        view:
          enabled: false
          table:
            enabled: false
      patient:
        add:
          extended:
            enabled: false


    settings:
      analytics:
        host: https://us.posthog.com
