export const SYSTEM_MANAGEMENT_ACCESS: string[] = [
    'EPILINKADMIN-SYSTEM',
    'VIEWELRACTIVITY-OBSERVATIONLABREPORT',
    'SRTADMIN-SYSTEM',
    'VIEWPHCRACTIVITY-CASEREPORTING',
    'IMPORTEXPORTADMIN-SYSTEM',
    'REPORTADMIN-SYSTEM',
    'ALERTADMIN-SYSTEM'
];
