entrypoints:
    traefik:
        address: ':8081'
    port:
        address: ':8080'
    web:
        address: ':80'
    websecure:
        address: ':443'
api:
    insecure: true
providers:
    file:
        filename: /etc/traefik/providers.yml

log:
    format: json
    level: DEBUG
