export const ConceptNames = {
    maritalStatuses: 'P_MARITAL',
    educationLevels: 'P_EDUC_LVL',
    raceCategories: 'RACE_CALCULATED',
    ethnicGroups: 'PHVS_ETHNICITYGROUP_CDC_UNK',
    detailedEthnicities: 'P_ETHN',
    ethnicityUnknownReasons: 'P_ETHN_UNK_REASON',
    genderUnknownReasons: 'SEX_UNK_REASON',
    preferredGenders: 'NBS_STD_GENDER_PARPT',
    nameTypes: 'P_NM_USE',
    namePrefixes: 'P_NM_PFX',
    nameSuffixes: 'P_NM_SFX',
    nameDegrees: 'P_NM_DEG',
    addressTypes: 'EL_TYPE_PST_PAT',
    addressUses: 'EL_USE_PST_PAT',
    phoneTypes: 'EL_TYPE_TELE_PAT',
    phoneUses: 'EL_USE_TELE_PAT',
    identificationTypes: 'EI_TYPE_PAT',
    assigningAuthorities: 'EI_AUTH_PAT'
};
