FROM amazoncorretto:8-al2-jdk

ARG ant_version=1.10.12
ARG maven_version=3.8.8

RUN yum update -y
RUN yum install -y tar gzip hostname
WORKDIR /home
ADD https://dlcdn.apache.org/ant/binaries/apache-ant-$ant_version-bin.tar.gz .
RUN tar -zxvf apache-ant-$ant_version-bin.tar.gz
RUN rm apache-ant-$ant_version*.gz
ENV ANT_HOME=/home/apache-ant-$ant_version
ADD https://dlcdn.apache.org/maven/maven-3/$maven_version/binaries/apache-maven-$maven_version-bin.tar.gz .
RUN tar -zxvf apache-maven-$maven_version-bin.tar.gz
RUN rm apache-maven-$maven_version-bin.tar.gz
ENV MAVEN_HOME=/home/apache-maven-$maven_version
ENV JBOSS_HOME=build
ENV JAVA_TOOL_OPTIONS=-Dfile.encoding=ISO-8859-1
ADD docker-entrypoint-ant.sh .
WORKDIR /mnt/src
VOLUME /root/.m2
CMD /home/docker-entrypoint-ant.sh
