FROM maven:3.9-amazoncorretto-8

ARG ant_version=1.10.12

# update
RUN yum update -y
RUN yum install -y tar gzip hostname

# install ant
WORKDIR /home
ADD https://dlcdn.apache.org/ant/binaries/apache-ant-$ant_version-bin.tar.gz .
RUN tar -zxvf apache-ant-$ant_version-bin.tar.gz
RUN rm apache-ant-$ant_version*.gz
ENV ANT_HOME=/home/apache-ant-$ant_version

# run build
ENV JBOSS_HOME=build
ENV JAVA_TOOL_OPTIONS=-Dfile.encoding=ISO-8859-1
ADD docker-entrypoint-ant.sh .
WORKDIR /mnt/src
VOLUME /root/.m2
CMD /home/docker-entrypoint-ant.sh
