nbs:
  security:
    oidc:
      protocol: http
      host: localhost:8100
      base: /realms/nbs-users
      uri: ${nbs.security.oidc.protocol}://${nbs.security.oidc.host}${nbs.security.oidc.base}
spring:
  security:
    oauth2:
      client:
        registration:
          nbs-users:
            provider: nbs-authentication
            client-id: ${nbs.security.oidc.client.id}
            client-secret: ${nbs.security.oidc.client.secret}
            scope:
              - openid
        provider:
          nbs-authentication:
            user-name-attribute: preferred_username
            issuer-uri: ${nbs.security.oidc.uri}
            jwk-set-uri: ${nbs.security.oidc.uri}/protocol/openid-connect/certs
