package gov.cdc.nedss.systemservice.scheduler.util;

public  final class SchedulerConstants{
	/*Generic constants for all scheduler files*/
	public static final String DAILY="DAILY";
	public static final String HOURLY="HOURLY";
	public static final String MINUTE="MINUTE";
	public static String DEDUPPROCESS = null;
	public static String TIMECOMPARE = null;
	public static String SAMEPROCESSEXCEP = null;
	public static String SIMILARPROCESSEXCEP = null;
	public static String SAMEBATCHSTARTTIME = null;
	public static String SIMILARBATCHSTARTTIME = null;
	public static String FROMSAMEBATCH = null;
	/*constants for BlowfishKeyManager.java*/

	/* constants for CdfSubformImportManager*/
	public static final String CDF_SUBFORM_SCHEDULE_TIMEGAP_IN_MINUTES="CDF_SUBFORM_SCHEDULE_TIMEGAP_IN_MINUTES";
	public static final String CDF_SUBFORM_SCHEDULE_TO_RUN="CDF_SUBFORM_SCHEDULE_TO_RUN";

	public static final String CDF_SUBFORM_IMPORT_NBS_RELEASE="CDF_SUBFORM_IMPORT_NBS_RELEASE";
	public static final String CDF_SUBFORM_IMPORT_USER_NAME="CDF_SUBFORM_IMPORT_USER_NAME";
	public static final String CDF_SUBFORM_IMPORT_SCHEDULE_HOURLY_OR_DAILY_OR_MINUTE="CDF_SUBFORM_IMPORT_SCHEDULE_HOURLY_OR_DAILY_OR_MINUTE";
	public static final String CDF_SUBFORM_IMPORT_SCHEDULE_TIME_IN_HOUR="CDF_SUBFORM_IMPORT_SCHEDULE_TIME_IN_HOUR";
	public static final String CDF_SUBFORM_IMPORT_SCHEDULE_TIME_IN_MINUTE="CDF_SUBFORM_IMPORT_SCHEDULE_TIME_IN_MINUTE";

	/*UndoCDFImport constants */
	public static final String UNDO_CDF_IMPORT_SCHEDULE_TIMEGAP_IN_MINUTES="UNDO_CDF_IMPORT_SCHEDULE_TIMEGAP_IN_MINUTES";
	public static final String UNDO_CDF_IMPORT_SCHEDULE_TO_RUN="UNDO_CDF_IMPORT_SCHEDULE_TO_RUN";
	public static final String UNDOCDF_SUBFORM_IMPORT_NBS_RELEASE="UNDO_CDF_SUBFORM_IMPORT_NBS_RELEASE";
	public static final String UNDOCDF_SUBFORM_IMPORT_USER_NAME="UNDO_CDF_SUBFORM_IMPORT_USER_NAME";
	public static final String UNDOCDF_SUBFORM_IMPORT_SCHEDULE_TO_RUN_HOURLY_OR_DAILY_OR_MINUTE="UNDOCDF_SUBFORM_IMPORT_SCHEDULE_TO_RUN_HOURLY_OR_DAILY_OR_MINUTE";
	public static final String UNDOCDF_SUBFORM_IMPORT_SCHEDULE_TO_RUN_TIME_IN_HOUR="UNDOCDF_SUBFORM_IMPORT_SCHEDULE_TO_RUN_TIME_IN_HOUR";
	public static final String UNDOCDF_SUBFORM_IMPORT_SCHEDULE_TO_RUN_TIME_IN_MINUTE="UNDOCDF_SUBFORM_IMPORT_SCHEDULE_TO_RUN_TIME_IN_MINUTE";

	/*user profile specific constants */
	public static final String USER_PROFILE_SCHEDULE_TO_RUN="USER_PROFILE_SCHEDULE_TO_RUN";
	public static final String USER_PROFILE_SCHEDULE_TIMEGAP_IN_MINUTES="USER_PROFILE_SCHEDULE_TIMEGAP_IN_MINUTES";
	public static final String POPULATE_FLAG="POPULATE_FLAG";
	public static final String USER_PROFILE_USER_NAME="USER_PROFILE_USER_NAME";
	public static final String USER_PROFILE_SCHEDULE_HOURLY_OR_DAILY_OR_MINUTE="USER_PROFILE_SCHEDULE_HOURLY_OR_DAILY_OR_MINUTE";
	public static final String USER_PROFILE_SCHEDULE_TIME_IN_HOUR="USER_PROFILE_SCHEDULE_TIME_IN_HOUR";
	public static final String USER_PROFILE_SCHEDULE_TIME_IN_MINUTE="USER_PROFILE_SCHEDULE_TIME_IN_MINUTE";


	/*PHCMART specific constants */
	public static final String PHCMART_SCHEDULE_TO_RUN="PHCMART_SCHEDULE_TO_RUN";
	public static final String PHCMART_SCHEDULE_TIMEGAP_IN_MINUTES="PHCMART_SCHEDULE_TIMEGAP_IN_MINUTES";
	public static final String PHCMART_SCHEDULE_TO_RUN_SCHEDULE_HOURLY_OR_DAILY_OR_MINUTE="PHCMART_SCHEDULE_TO_RUN_SCHEDULE_HOURLY_OR_DAILY_OR_MINUTE";
	public static final String PHCMART_SCHEDULE_TO_RUN_SCHEDULE_TIME_IN_HOUR="PHCMART_SCHEDULE_TO_RUN_SCHEDULE_TIME_IN_HOUR";
	public static final String PHCMART_SCHEDULE_TO_RUN_SCHEDULE_TIME_IN_MINUTE="PHCMART_SCHEDULE_TO_RUN_SCHEDULE_TIME_IN_MINUTE";
	public static final String PHCMART_WINDOWS_FILE="PhcMartEtl.bat";

	/*ELR specific constants*/
	public static final String ELR_IMPORTER_SCHEDULE_TO_RUN="ELR_IMPORTER_SCHEDULE_TO_RUN";
	public static final String ELR_IMPORTER_SCHEDULE_TIMEGAP_IN_MINUTES="ELR_IMPORTER_SCHEDULE_TIMEGAP_IN_MINUTES";
	public static final String ELR_IMPORTER_SCHEDULE_HOURlY_OR_DAILY_OR_MINUTE="ELR_IMPORTER_SCHEDULE_HOURlY_OR_DAILY_OR_MINUTE";
	public static final String ELR_IMPORTER_SCHEDULE_TIME_IN_HOUR_OR_MINUTE="ELR_IMPORTER_SCHEDULE_TIME_IN_HOUR_OR_MINUTE";
	public static final String ELR_IMPORTER_SCHEDULE_TIME_IN_HOUR="ELR_IMPORTER_SCHEDULE_TIME_IN_HOUR";
	public static final String ELR_IMPORTER_SCHEDULE_TIME_IN_MINUTE="ELR_IMPORTER_SCHEDULE_TIME_IN_MINUTE";

	/*MSGOUT PROCESSOR constants */
	public static final String MSGOUT_SCHEDULE_TO_RUN="MSGOUT_SCHEDULE_TO_RUN";
	public static final String MSGOUT_SCHEDULE_TIMEGAP_IN_MINUTES="MSGOUT_SCHEDULE_TIMEGAP_IN_MINUTES";
	public static final String MSGOUT_SCHEDULE_HOURLY_OR_DAILY_OR_MINUTE="MSGOUT_SCHEDULE_HOURLY_OR_DAILY_OR_MINUTE";
	public static final String MSGOUT_SCHEDULE_TIME_IN_HOUR="MSGOUT_SCHEDULE_TIME_IN_HOUR";
	public static final String MSGOUT_SCHEDULE_TIME_IN_MINUTE="MSGOUT_SCHEDULE_TIME_IN_MINUTE";

	/*DEDUPLICATION Processor constants */
	/*public static final String DEDUPLICATION_SCHEDULE_TIMEGAP_IN_MINUTES="DEDUPLICATION_SCHEDULE_TIMEGAP_IN_MINUTES";
	public static final String DEDUPLICATION_SCHEDULE_TO_RUN="DEDUPLICATION_SCHEDULE_TO_RUN";
	public static final String DEDUPLICATION_SCHEDULE_HOURLY_OR_DAILY_OR_MINUTE="DEDUPLICATION_SCHEDULE_HOURLY_OR_DAILY_OR_MINUTE";
	public static final String DEDUPLICATION_SCHEDULE_TIME_IN_HOUR="DEDUPLICATION_SCHEDULE_TIME_IN_HOUR";
	public static final String DEDUPLICATION_SCHEDULE_TIME_IN_MINUTE="DEDUPLICATION_SCHEDULE_TIME_IN_MINUTE";
	public static final String DEDUPLICATION_PROCESS_TYPE="DEDUPLICATION_PROCESS_TYPE";*/
	
	/*DEDUPLICATION Processor constants for same patients merge*/
	public static final String DEDUPLICATION_SAME_SCHEDULE_TIMEGAP_IN_MINUTES="DEDUPLICATION_SAME_SCHEDULE_TIMEGAP_IN_MINUTES";
	public static final String DEDUPLICATION_SAME_SCHEDULE_TO_RUN="DEDUPLICATION_SAME_SCHEDULE_TO_RUN";
	public static final String DEDUPLICATION_SAME_SCHEDULE_HOURLY_OR_DAILY_OR_MINUTE="DEDUPLICATION_SAME_SCHEDULE_HOURLY_OR_DAILY_OR_MINUTE";
	public static final String DEDUPLICATION_SAME_SCHEDULE_TIME_IN_HOUR="DEDUPLICATION_SAME_SCHEDULE_TIME_IN_HOUR";
	public static final String DEDUPLICATION_SAME_SCHEDULE_TIME_IN_MINUTE="DEDUPLICATION_SAME_SCHEDULE_TIME_IN_MINUTE";
	public static final String DEDUPLICATION_SAME_PROCESS_TYPE="DEDUPLICATION_SAME_PROCESS_TYPE";
	
	/*DEDUPLICATION Processor constants for Similar patients merge*/
	public static final String DEDUPLICATION_SIMILAR_SCHEDULE_TIMEGAP_IN_MINUTES="DEDUPLICATION_SIMILAR_SCHEDULE_TIMEGAP_IN_MINUTES";
	public static final String DEDUPLICATION_SIMILAR_SCHEDULE_TO_RUN="DEDUPLICATION_SIMILAR_SCHEDULE_TO_RUN";
	public static final String DEDUPLICATION_SIMILAR_SCHEDULE_HOURLY_OR_DAILY_OR_MINUTE="DEDUPLICATION_SIMILAR_SCHEDULE_HOURLY_OR_DAILY_OR_MINUTE";
	public static final String DEDUPLICATION_SIMILAR_SCHEDULE_TIME_IN_HOUR="DEDUPLICATION_SIMILAR_SCHEDULE_TIME_IN_HOUR";
	public static final String DEDUPLICATION_SIMILAR_SCHEDULE_TIME_IN_MINUTE="DEDUPLICATION_SIMILAR_SCHEDULE_TIME_IN_MINUTE";
	public static final String DEDUPLICATION_SIMILAR_PROCESS_TYPE="DEDUPLICATION_SIMILAR_PROCESS_TYPE";
	

	/*GEOCODING Processor constants */
	public static final String GEOCODING_SCHEDULE_TIMEGAP_IN_MINUTES="GEOCODING_SCHEDULE_TIMEGAP_IN_MINUTES";
	public static final String GEOCODING_SCHEDULE_TO_RUN="GEOCODING_SCHEDULE_TO_RUN";
	public static final String GEOCODING_SCHEDULE_HOURLY_OR_DAILY_OR_MINUTE="GEOCODING_SCHEDULE_HOURLY_OR_DAILY_OR_MINUTE";
	public static final String GEOCODING_SCHEDULE_TIME_IN_HOUR="GEOCODING_SCHEDULE_TIME_IN_HOUR";
	public static final String GEOCODING_SCHEDULE_TIME_IN_MINUTE="GEOCODING_SCHEDULE_TIME_IN_MINUTE";
	public static final String GEOCODING_PROCESS_TYPE="GEOCODING_PROCESS_TYPE";

	/*LDF SRT REPORT Processor constants */
	public static final String LDF_SRT_REPORT_SCHEDULE_TIMEGAP_IN_MINUTES="LDF_SRT_REPORT_SCHEDULE_TIMEGAP_IN_MINUTES";
	public static final String LDF_SRT_REPORT_SCHEDULE_TO_RUN="LDF_SRT_REPORT_SCHEDULE_TO_RUN";
	public static final String LDF_SRT_REPORT_SCHEDULE_HOURLY_OR_DAILY_OR_MINUTE="LDF_SRT_REPORT_SCHEDULE_HOURLY_OR_DAILY_OR_MINUTE";
	public static final String LDF_SRT_REPORT_SCHEDULE_TIME_IN_HOUR="LDF_SRT_REPORT_SCHEDULE_TIME_IN_HOUR";
	public static final String LDF_SRT_REPORT_SCHEDULE_TIME_IN_MINUTE="LDF_SRT_REPORT_SCHEDULE_TIME_IN_MINUTE";
	public static final String LDFREPORT_USERNAME="LDF_SRT_REPORT_USERNAME";
	public static final String LDFREPORT_FILENAME="LDF_SRT_REPORT_FILENAME";
	public static final String LDFREPORT_REPORT_TYPE="LDF_SRT_REPORT_REPORT_TYPE";


	/*MasterETL processor constants */
	public static final String MASTER_ETL_SCHEDULE_TIMEGAP_IN_MINUTES="MASTER_ETL_SCHEDULE_TIMEGAP_IN_MINUTES";
	public static final String MASTER_ETL_SCHEDULE_TO_RUN="MASTER_ETL_SCHEDULE_TO_RUN";
	public static final String MASTERETL_SCHEDULE_HOURLY_OR_DAILY_OR_MINUTE="MASTERETL_SCHEDULE_HOURLY_OR_DAILY_OR_MINUTE";
	public static final String MASTERETL_SCHEDULE_TIME_IN_HOUR="MASTERETL_SCHEDULE_TIME_IN_HOUR";
	public static final String MASTERETL_SCHEDULE_TIME_IN_MINUTE="MASTERETL_SCHEDULE_TIME_IN_MINUTE";
	public static final String MASTERETL_WINDOWS_FILE="MasterEtl.bat";
	public static final String INCRE_MASTERETL_WINDOWS_FILE="MasterEtlIncremental.bat";
	public static final String MASTERETL_ETL_PROCESS="MASTERETL_ETL_PROCESS";
	public static final String MASTERETL_ETL_INCR="INCR";
	public static final String MASTERETL_ETL_FULL="FULL";

	/* The following lines are commented out b's  for the Defect no :15457*/
	//public static final String MASTERETL_WINDOWS_FILE2="EtlProcessWithScheduler.bat";
	//public static final int TIME_GAP_TO_IN_MIN_RUN_MASTERRTLSAS_PROGRAM_AFTER_NEW_RDB_TABLES=5*60000;

	/*NND LDF EXTRACTION CONSTANTS */
	public static final String NND_LDF_EXTRACTION_SCHEDULE_TO_RUN="NND_LDF_EXTRACTION_SCHEDULE_TO_RUN";
	public static final String NND_LDF_EXTRACTION_SCHEDULE_TIMEGAP_IN_MINUTES="NND_LDF_EXTRACTION_SCHEDULE_TIMEGAP_IN_MINUTES";
	public static final String NND_LDF_EXT_SCHEDULE_TO_RUN_SCHEDULE_HOURLY_OR_DAILY_OR_MINUTE="NND_LDF_EXT_SCHEDULE_TO_RUN_SCHEDULE_HOURLY_OR_DAILY_OR_MINUTE";
	public static final String NND_LDF_EXT_SCHEDULE_TO_RUN_SCHEDULE_TIME_IN_HOUR="NND_LDF_EXT_SCHEDULE_TO_RUN_SCHEDULE_TIME_IN_HOUR";
	public static final String NND_LDF_EXT_SCHEDULE_TO_RUN_SCHEDULE_TIME_IN_MINUTE="NND_LDF_EXT_SCHEDULE_TO_RUN_SCHEDULE_TIME_IN_MINUTE";
	
	/*ALERT_EMAIL specific constants*/
	public static final String ALERT_EMAIL_SCHEDULE_TO_RUN="ALERT_EMAIL_SCHEDULE_TO_RUN";
	public static final String ALERT_EMAIL_SCHEDULE_TIMEGAP_IN_MINUTES="ALERT_EMAIL_SCHEDULE_TIMEGAP_IN_MINUTES";
	public static final String ALERT_EMAIL_SCHEDULE_HOURlY_OR_DAILY_OR_MINUTE="ALERT_EMAIL_SCHEDULE_HOURLY_OR_DAILY_OR_MINUTE";
	public static final String ALERT_EMAIL_SCHEDULE_TIME_IN_HOUR="ALERT_EMAIL_SCHEDULE_TIME_IN_HOUR";
	public static final String ALERT_EMAIL_SCHEDULE_TIME_IN_MINUTE="ALERT_EMAIL_SCHEDULE_TIME_IN_MINUTE";
	public static final String ALERT_EMAIL_USER_NAME="ALERT_EMAIL_USER_NAME";
	
	/*import process specific constants */
	public static final String PHCR_IMPORTER_SCHEDULE_TO_RUN="PHCR_IMPORTER_SCHEDULE_TO_RUN";
	public static final String PHCR_IMPORTER_SCHEDULE_TIMEGAP_IN_MINUTES="PHCR_IMPORTER_SCHEDULE_TIMEGAP_IN_MINUTES";
	public static final String PHCR_IMPORTER_USER_NAME="PHCR_IMPORTER_USER_NAME";
	public static final String PHCR_IMPORTER_SCHEDULE_HOURLY_OR_DAILY_OR_MINUTE="PHCR_IMPORTER_SCHEDULE_HOURLY_OR_DAILY_OR_MINUTE";
	public static final String PHCR_IMPORTER_SCHEDULE_TIME_IN_HOUR="PHCR_IMPORTER_SCHEDULE_TIME_IN_HOUR";
	public static final String PHCR_IMPORTER_SCHEDULE_TIME_IN_MINUTE="PHCR_IMPORTER_SCHEDULE_TIME_IN_MINUTE";


	public static String getDEDUPPROCESS() {
		return DEDUPPROCESS;
	}
	public static void setDEDUPPROCESS(String dedupprocess) {
		DEDUPPROCESS = dedupprocess;
	}
	public static String getTIMECOMPARE() {
		return TIMECOMPARE;
	}
	public static void setTIMECOMPARE(String timecompare) {
		TIMECOMPARE = timecompare;
	}
	public static String getSAMEPROCESSEXCEP() {
		return SAMEPROCESSEXCEP;
	}
	public static void setSAMEPROCESSEXCEP(String sameprocessexcep) {
		SAMEPROCESSEXCEP = sameprocessexcep;
	}
	public static String getSIMILARPROCESSEXCEP() {
		return SIMILARPROCESSEXCEP;
	}
	public static void setSIMILARPROCESSEXCEP(String similarprocessexcep) {
		SIMILARPROCESSEXCEP = similarprocessexcep;
	}
	public static String getSAMEBATCHSTARTTIME() {
		return SAMEBATCHSTARTTIME;
	}
	public static void setSAMEBATCHSTARTTIME(String samebatchstarttime) {
		SAMEBATCHSTARTTIME = samebatchstarttime;
	}
	public static String getSIMILARBATCHSTARTTIME() {
		return SIMILARBATCHSTARTTIME;
	}
	public static void setSIMILARBATCHSTARTTIME(String similarbatchstarttime) {
		SIMILARBATCHSTARTTIME = similarbatchstarttime;
	}
	public static String getFROMSAMEBATCH() {
		return FROMSAMEBATCH;
	}
	public static void setFROMSAMEBATCH(String fromsamebatch) {
		FROMSAMEBATCH = fromsamebatch;
	}
	
	
}
