package gov.cdc.nedss.webapp.nbs.action.util;

public interface ActionConstants {

	public static String UPDATED_FIELD_SPERVISOR_NOTES_CURR_SUPERV="UPDATED_FILED_SPERVISOR_NOTES";
	public static String UPDATED_CASE_SPERVISOR_NOTES_CURR_SUPERV="UPDATED_CASE_SPERVISOR_NOTES";
	
	public static String UPDATED_FIELD_SPERVISOR_NOTES_CURRENT_SUPRV="UPDATED_FILED_SPERVISOR_NOTES_CURRENT_SUPRV";
	public static String UPDATED_CASE_SPERVISOR_NOTES_CURRENT_SUPRV="UPDATED_CASE_SPERVISOR_NOTES_CURRENT_SUPRV";
	public static String CURRENT_INVESTGATOR="CURRENT_INVESTGATOR";
	public static String PATIENT_NAME="PATIENT_NAME";
	public static String MESSAGE_TEXT="MESSAGE_TEXT";
	public static String SUBMITTED_BY="SUBMITTED_BY";
	public static String DATE_ADDED="DATE_ADDED";
	public static String NEW_IND="NEW_IND";
	public static String RECORD_STATUS_CD="RECORD_STATUS_CD";
	public static String CURRENT_INVESTIGATOR="RECORD_STATUS_CD";
	public static String CURRENT_SUPERVISOR="CURRENT_SUPERVISOR";
		
}
