spring.application.name=save-dedupe-configuration
# Database connection properties
spring.datasource.url=jdbc:postgresql://localhost:5432/config_db
spring.datasource.username=user
spring.datasource.password=mypassword
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate properties (optional)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Logging
logging.file.name=app.log
logging.file.path=/Users/SnehaaHari/Desktop/API-DIBBS/configservice/NEDSS-Modernization/apps
server.error.include-message=always

# CORS
spring.web.cors.allow-credentials=true
spring.web.cors.allowed-origins=http://localhost:3000
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
