spring.application.name=save-dedupe-configuration
# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/config_db
spring.datasource.username=user
spring.datasource.password=mypassword
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update  # Auto-creates the database schema
spring.jpa.show-sql=true  # Shows SQL queries in logs
