package gov.cdc.nbs.questionbank.page.component.tree;

record FlattenedComponent(
    long identifier,
    int type,
    String name,
    boolean visible,
    int order,
    int questionGroupSeq,
    boolean isStandardNnd,
    boolean isStandard,
    String standard,
    String question,
    String dataType,
    String subGroup,
    String description,
    boolean enabled,
    boolean required,
    boolean allowFutureDates,
    boolean coInfection,
    String mask,
    String toolTip,
    String defaultValue,
    String valueSet,
    String adminComments,
    String fieldLength,
    String defaultRdbTableName,
    String rdbColumnName,
    String defaultLabelInReport,
    String dataMartColumnName,
    boolean isGrouped,
    String dataLocation,
    boolean isPublished,
    String blockName,
    Integer dataMartRepeatNumber,
    boolean appearsInBatch,
    String batchLabel,
    Integer batchWidth,
    String componentBehavior,
    String componentName,
    String classCode) {

  FlattenedComponent(
      long identifier, int type, String name, boolean visible, int order, int questionGroupSeq) {
    this(
        identifier,
        type,
        name,
        visible,
        order,
        questionGroupSeq,
        false,
        false,
        null,
        null,
        null,
        null,
        null,
        false,
        false,
        false,
        false,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        false,
        null,
        false,
        null,
        null,
        false,
        null,
        null,
        null,
        null,
        null);
  }
}
