name: Build and Push modernization-test-db
on:
  push:
    tags:
      - "*SNAPSHOT*"

jobs:
  call-build-microservice-container-workflow:
    uses: CDCgov/NEDSS-Workflows/.github/workflows/Build-microservice-container.yaml@main
    with:
      microservice_name: modernization-test-db
      dockerfile_relative_path: ./cdc-sandbox/test-db
    secrets:
      CDC_NBS_SANDBOX_SHARED_SERVICES_ACCOUNTID: ${{secrets.CDC_NBS_SANDBOX_SHARED_SERVICES_ACCOUNTID}}
      ECR_REPO_BASE_NAME: ${{secrets.ECR_REPO_BASE_NAME}}
