name: Build and Push modernization-test-db to ECR
on:
  workflow_call:
  secrets:
    DATABASE_PASSWORD:
      description: "Secret named DATABASE_PASSWORD that references the test database container default password"
      required: true
  push:
    branches:
      - main
    paths:
      - "cdc-sandbox/db/**"
jobs:
  call-build-microservice-container-workflow:
    uses: CDCgov/NEDSS-Workflows/.github/workflows/Build-other-microservice-container.yaml@main
    with:
      microservice_name: modernization-test-db
      dockerfile_relative_path: ./cdc-sandbox/db
      environment_classifier: SNAPSHOT
    secrets:
      CDC_NBS_SANDBOX_SHARED_SERVICES_ACCOUNTID: ${{secrets.CDC_NBS_SANDBOX_SHARED_SERVICES_ACCOUNTID}}
      ECR_REPO_BASE_NAME: ${{secrets.ECR_REPO_BASE_NAME}}
      GIT_USER_EMAIL: ${{secrets.GIT_USER_EMAIL}}
      GIT_USER_NAME: ${{secrets.GIT_USER_NAME}}
      HELM_TOKEN: ${{secrets.HELM_TOKEN}}
    env:
      DB_PW: ${{secrets.DATABASE_PASSWORD}}
