name: Build and Push common-asset-server image to ECR
on:
  push:
    branches:
      - main
      - rel-**
    paths:
      - 'cdc-sandbox/common-asset-server/**'

jobs:
  call-build-microservice-container-workflow:
    uses: CDCgov/NEDSS-Workflows/.github/workflows/Build-other-microservice-container.yaml@main
    with:
      microservice_name: common-asset-server
      dockerfile_relative_path: ./cdc-sandbox/common-asset-server
      environment_classifier: SNAPSHOT
      update_helm_chart: true
      values_file_with_path: charts/patient-search/values-dev.yaml
    secrets:
      CDC_NBS_SANDBOX_SHARED_SERVICES_ACCOUNTID: ${{secrets.CDC_NBS_SANDBOX_SHARED_SERVICES_ACCOUNTID}}
      ECR_REPO_BASE_NAME: ${{secrets.ECR_REPO_BASE_NAME}}
      GIT_USER_EMAIL: ${{secrets.GIT_USER_EMAIL}}
      GIT_USER_NAME: ${{secrets.GIT_USER_NAME}}
      HELM_TOKEN: ${{secrets.HELM_TOKEN}}      
  call-update-helm:
    needs: call-build-microservice-container-workflow    
    uses: CDCgov/NEDSS-Workflows/.github/workflows/Update-helm-charts.yaml@main
    with:
      microservice_name: common-asset-server
      values_file_with_path: charts/patient-search/values-dev.yaml
      new_image_tag: ${{ needs.call-build-microservice-container-workflow.outputs.output_image_tag }}      
    secrets:
      GIT_USER_EMAIL: ${{secrets.GIT_USER_EMAIL}}
      GIT_USER_NAME: ${{secrets.GIT_USER_NAME}}
      HELM_TOKEN: ${{secrets.HELM_TOKEN}}  