name: Release Candidate Container Build and Deployment Preparation
on:
  workflow_dispatch:
    inputs: 
        environment:
          description: 'The environment to tag the resulting images to.  The resulting container would be tagged as <application-name>:<application-version>-<environment>.<githubsha>'
          type: choice
          required: true
          default: 'TEST'
          options:
          - TEST
        values:
          description: 'The name of the Helm chart values file to update with the resulting tag name.'
          type: choice
          required: true
          default: 'test2'
          options:
          - test2
        build-elasticsearch:
          description: 'Release a new ElasticSearch Container?'
          required: true
          type: boolean
          default: false    
        build-nifi:
          description: 'Release a new NiFi Container?'
          required: true
          type: boolean
          default: true            

jobs:   
  build-nifi-release-candidate:
    if: ${{ inputs.build-nifi == 'true' }}
    name: Build NiFi Release Candidate
    uses: CDCgov/NEDSS-Workflows/.github/workflows/Release-gradle-microservice-container.yaml@main
    with:
      microservice_name: nifi    
      build-new-container: true
      dockerfile_relative_path: -f ./cdc-sandbox/nifi/Dockerfile .
      environment_classifier: ${{inputs.environment}}
    secrets:
      CDC_NBS_SANDBOX_SHARED_SERVICES_ACCOUNTID: ${{secrets.CDC_NBS_SANDBOX_SHARED_SERVICES_ACCOUNTID}}
      ECR_REPO_BASE_NAME: ${{secrets.ECR_REPO_BASE_NAME}}
      GIT_USER_EMAIL: ${{secrets.GIT_USER_EMAIL}}
      GIT_USER_NAME: ${{secrets.GIT_USER_NAME}}
      HELM_TOKEN: ${{secrets.HELM_TOKEN}}
  prepare-nifi-release-candidate:
    name: Prepare NiFi Release Candidate Deployment
    needs: build-nifi-release-candidate
    uses: CDCgov/NEDSS-Workflows/.github/workflows/Update-helm-charts.yaml@main
    with:
      microservice_name: nifi
      values_file_with_path: charts/nifi-efs/values-${{inputs.values}}.yaml
      new_image_tag: ${{ needs.build-nifi-release-candidate.outputs.output_image_tag }}
    secrets:
      GIT_USER_EMAIL: ${{secrets.GIT_USER_EMAIL}}
      GIT_USER_NAME: ${{secrets.GIT_USER_NAME}}
      HELM_TOKEN: ${{secrets.HELM_TOKEN}}       
