# This workflow is used to verify the code quality by running tests
name: Verify Modernization UI

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "apps/modernization-ui/**"

jobs:
  pipeline:
    name: Verify and Ensure
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: ./apps/modernization-ui
        run: npm install

      - name: Lint
        working-directory: ./apps/modernization-ui
        run: npm run lint

      - name: Verify
        working-directory: ./apps/modernization-ui
        run: npm run test:all

      - name: Ensure
        working-directory: ./apps/modernization-ui
        run: npm run build
