# This workflow is used to verify the code quality by running tests
name: Verify Modernization UI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "apps/modernization-ui/**"
      - ".github/workflows/verify-modernization-ui.yaml"
  pull_request:
    paths:
      - "apps/modernization-ui/**"
      - ".github/workflows/verify-modernization-ui.yaml"

jobs:
  pipeline:
    name: Verify and Ensure
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22.x'

      - name: Install dependencies
        working-directory: ./apps/modernization-ui
        run: npm ci

      - name: Lint
        working-directory: ./apps/modernization-ui
        run: npm run lint

      - name: Check formatting
        working-directory: ./apps/modernization-ui
        run: npm run format:check

      - name: Unit Test
        working-directory: ./apps/modernization-ui
        run: npm run test:all

      - name: Build
        working-directory: ./apps/modernization-ui
        run: npm run build
