nbs:
    security:
        tokenSecret: qJ5+oDurrJnxfaAz6h4Eg1saP7NSeHuQQ/Yq4vh+mbi4B4QYThc/M+33VtPJ5O2A
        tokenIssuer: gov.cdc.nbs
        tokenExpirationMillis: 1800000 # 30 minutes
    elasticsearch:
        server: localhost
        port: 9200
        url: http://${nbs.elasticsearch.server}:${nbs.elasticsearch.port}
    uid:
        suffix: GA01
        seed: 10000000
    datasource:
        server: localhost
spring:
    profiles:
        active: default,kafka
        group:
            test: default,kafka,embeddedkafka
    jpa:
        properties:
            hibernate:
                ddl-auto: validate
                default_schema: dbo
                format_sql: true
                jdbc.time_zone: UTC
                dialect: org.hibernate.dialect.SQLServer2012Dialect
                hbm2ddl.jdbc_metadata_extraction_strategy: individually
    datasource:
        url: jdbc:sqlserver://${nbs.datasource.server}:1433;database=nbs_odse;encrypt=true;trustServerCertificate=true;
        username: sa
        password: fake.fake.fake.1234
server:
    port: 8281
